### PR TITLE
Try using getMainExecutable to address argv[0] limitations

### LINKED ISSUE #5096: Include `LLVM_SYMBOLIZER_PATH` when running Carbon in Compiler explorer?
### Description of the bug:

Currently if you crash Carbon in compiler explorer you get a stack trace without symbols, which ends up in a bug report https://github.com/carbon-language/carbon-lang/issues/5094

Expecting folks playing in compiler explorer to set up a toolchain to get a stack trace seems like a reach. If it's possible it'd be nice to set `LLVM_SYMBOLIZER_PATH` in compiler explorer so that the stack trace is immediately useful.

### PR DESCRIPTION
**Pull request by jonmeow**
When finding an executable, this validates that the returned binary is a symlink back to the same thing as /proc/self/exe, also using that as a fallback for different things.

Looking back at #3912, we started using `findProgramByName` in order to avoid path canonicalization done by `GetMainExecutable`. That created issues as in #5096, wherein an `argv[0]` that's not explicit enough (`llvm-symbolizer` instead of the full path, done in [LLVM's Signals.cpp](https://github.com/llvm/llvm-project/blob/4f60f45130c6bd96c79e468fe9927a29af760f56/llvm/lib/Support/Signals.cpp#L198)) leads to incorrect results (finding an `llvm-symbolizer` in `$PATH`).

One option to fix this would be to patch LLVM to provide an absolute path for `llvm-symbolizer`. However, I'll suggest that passing a filename in `argv[0]` is not terribly uncommon, and could be a migration limitation if we force it. The failure mode is also opaque; for example: 

```
$ /bin/sh -c "exec -a llvm-symbolizer ./bazel-bin/toolchain/carbon"
error: expected carbon-busybox symlink at `/usr/lib/llvm-19/bin/llvm-symbolizer`
```

Combined with the `setenv` of `LLVM_SYMBOLIZER_PATH` in `busybox_main.cpp`, this is intended to fix #5096.

### CODE REVIEW

**Comment by jonmeow** [comment]
Flagging this for @zygoloid @chandlerc who have been most active with this area...

A typical run of the actual binary:

```
╚╡~/dev/bin/carbon_toolchain/bin/carbon clang -- -v
clang version 21.0.0git
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/google/home/jperkins/dev/bin/carbon_toolchain/bin/../lib/carbon/../../lib/carbon/llvm/bin/
Build config: +assertions, +asan, +ubsan
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/14
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

Some example crashes (edited code to crash, note the `CheckFail<Carbon::TemplateString<5>{"FATAL"}` in the second means `setenv` is applied):

```
╚╡bazel run //toolchain compile f
INFO: Invocation ID: 1d37263c-c1c8-4340-91cc-c181d9170762
INFO: Analyzed target //toolchain:toolchain (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //toolchain:carbon up-to-date:
  bazel-bin/toolchain/carbon
INFO: Elapsed time: 6.584s, Critical Path: 6.23s
INFO: 45 processes: 1 disk cache hit, 41 internal, 3 linux-sandbox.
INFO: Build completed successfully, 45 total actions
INFO: Running command line: bazel-bin/toolchain/carbon <args omitted>
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: /usr/local/google/home/jperkins/.cache/bazel/_bazel_jperkins/85deb7d9d96f7e0e80b42618a55969d7/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/carbon compile f
 #0 0x00005570f2f22776 ___interceptor_backtrace /usr/local/google/home/jperkins/dev/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4372:13
 #1 0x00005570ff6d9d8d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:804:13
 #2 0x00005570ff6da69b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:888:1
 #3 0x00005570ff6d5410 llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x00005570ff6da9ca SignalHandler(int, siginfo_t*, void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #5 0x00007fc12bb1cdf0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fdf0)
 #6 0x00007fc12bb7195c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #7 0x00007fc12bb1ccc2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007fc12bb054ac abort ./stdlib/abort.c:81:3
 #9 0x00005570ff011e38 Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:45:3
#10 0x00005570f2ffc258 __is_long /usr/local/google/home/jperkins/dev/bin/llvm-built/bin/../include/c++/v1/string:1880:12
#11 0x00005570f2ffc258 ~basic_string /usr/local/google/home/jperkins/dev/bin/llvm-built/bin/../include/c++/v1/string:1211:9
#12 0x00005570f2ffc258 void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{char [6]{(char)70, (char)65, (char)84, (char)65, (char)76}}, Carbon::TemplateString<39>{char [40]{(char)116, (char)111, (char)111, (char)108, (char)99, (char)104, (char)97, (char)105, (char)110, (char)47, (char)100, (char)114, (char)105, (char)118, (char)101, (char)114, (char)47, (char)99, (char)111, (char)109, (char)112, (char)105, (char)108, (char)101, (char)95, (char)115, (char)117, (char)98, (char)99, (char)111, (char)109, (char)109, (char)97, (char)110, (char)100, (char)46, (char)99, (char)112, (char)112}}, 858, Carbon::TemplateString<0>{}, Carbon::TemplateString<4>{char [5]{(char)98, (char)108, (char)97, (char)104}}>() /proc/self/cwd/./common/check_internal.h:97:5
#13 0x00005570f2ffc0e9 Carbon::CompileSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/compile_subcommand.cpp:858:3
#14 0x00005570f2fefc82 Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:0:39
#15 0x00005570f2fc3ea3 Carbon::Main(int, char**) /proc/self/cwd/toolchain/install/busybox_main.cpp:89:42
#16 0x00005570f2fc06dd main /proc/self/cwd/toolchain/install/busybox_main.cpp:0:17
#17 0x00007fc12bb06ca8 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#18 0x00007fc12bb06d65 call_init ./csu/../csu/libc-start.c:128:20
#19 0x00007fc12bb06d65 __libc_start_main ./csu/../csu/libc-start.c:347:5
#20 0x00005570f2eda6a1 _start (/usr/local/google/home/jperkins/.cache/bazel/_bazel_jperkins/85deb7d9d96f7e0e80b42618a55969d7/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/carbon+0xbd676a1)
FATAL failure at toolchain/driver/compile_subcommand.cpp:858: blah

╚╡./bazel-bin/toolchain/carbon compile f
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: ./bazel-bin/toolchain/carbon compile f
 #0 0x000055ec175c6776 ___interceptor_backtrace (./bazel-bin/toolchain/carbon+0xbdaf776)
 #1 0x000055ec23d7dd8d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./bazel-bin/toolchain/carbon+0x18566d8d)
 #2 0x000055ec23d7e69b PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #3 0x000055ec23d79410 llvm::sys::RunSignalHandlers() (./bazel-bin/toolchain/carbon+0x18562410)
 #4 0x000055ec23d7e9ca SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #5 0x00007f63582dfdf0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fdf0)
 #6 0x00007f635833495c (/lib/x86_64-linux-gnu/libc.so.6+0x9495c)
 #7 0x00007f63582dfcc2 raise (/lib/x86_64-linux-gnu/libc.so.6+0x3fcc2)
 #8 0x00007f63582c84ac abort (/lib/x86_64-linux-gnu/libc.so.6+0x284ac)
 #9 0x000055ec236b5e38 Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) (./bazel-bin/toolchain/carbon+0x17e9ee38)
#10 0x000055ec176a0258 void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{"FATAL"}, Carbon::TemplateString<39>{"toolchain/driver/compile_subcommand.cpp"}, 858, Carbon::TemplateString<0>{}, Carbon::TemplateString<4>{"blah"}>() (./bazel-bin/toolchain/carbon+0xbe89258)
#11 0x000055ec176a00e9 Carbon::CompileSubcommand::Run(Carbon::DriverEnv&) (./bazel-bin/toolchain/carbon+0xbe890e9)
#12 0x000055ec17693c82 Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) (./bazel-bin/toolchain/carbon+0xbe7cc82)
#13 0x000055ec17667ea3 Carbon::Main(int, char**) busybox_main.cpp:0:0
#14 0x000055ec176646dd main (./bazel-bin/toolchain/carbon+0xbe4d6dd)
#15 0x00007f63582c9ca8 (/lib/x86_64-linux-gnu/libc.so.6+0x29ca8)
#16 0x00007f63582c9d65 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29d65)
#17 0x000055ec1757e6a1 _start (./bazel-bin/toolchain/carbon+0xbd676a1)
FATAL failure at toolchain/driver/compile_subcommand.cpp:858: blah
zsh: IOT instruction  ./bazel-bin/toolchain/carbon compile f
```

File: common/exe_path.cpp [hunk 1]
```diff
@@ -13,14 +13,40 @@
...
+  // Note this returns the canonical path, dropping symlink information that we
+  // might want. As a consequence, we use it as a last resort. However, it's
+  // also helpful to use to ensure we found the correct tool through other
+  // means.
+  std::string exe_path =
+      llvm::sys::fs::getMainExecutable(argv0, &static_for_main_addr);
+
+  llvm::StringRef argv0_ref = argv0;
+
+  char realpath_buf[PATH_MAX];
```
Comment (zygoloid) [inline common/exe_path.cpp]: It's non-portable to assume that `PATH_MAX` can be used for path buffers. I think the better thing is to pass `nullptr` as the buffer to `realpath` instead to ask it to allocate a suitably-sized buffer with `malloc`.

File: common/exe_path.h [hunk 2]
```diff
@@ -10,11 +10,12 @@
 namespace Carbon {
 
 // Computes the executable path for the given `argv[0]` value form `main`.
```
Comment (zygoloid) [inline common/exe_path.h]:
```suggestion
// Computes the executable path for the given `argv[0]` value from `main`.
```
(drive-by, but I was having real trouble understanding what this meant)

File: common/exe_path.h [hunk 3]
```diff
@@ -10,11 +10,12 @@
...
+// `argv0` is required to be null-terminated.
 //
 // A simplistic approach -- if the provided string isn't already a valid path,
 // we look it up in the PATH environment variable. Doesn't resolve any symlinks
 // and if it fails, simply returns the provided `argv0`.
```
Comment (zygoloid) [inline common/exe_path.h]: The "if it fails" part here doesn't seem to be up to date.

File: toolchain/install/busybox_info.h [hunk 4]
```diff
@@ -33,26 +43,31 @@ struct BusyboxInfo {
 // `lib/carbon/carbon-busybox` within that install.
 //
 // If unable to locate a plausible busybox binary, returns an error instead.
-inline auto GetBusyboxInfo(llvm::StringRef argv0) -> ErrorOr<BusyboxInfo> {
+inline auto GetBusyboxInfo(const char* argv0) -> ErrorOr<BusyboxInfo> {
   // Check for an override of `argv[0]` from the environment and apply it.
   if (const char* argv0_override = getenv(Argv0OverrideEnv)) {
```
Comment (zygoloid) [inline toolchain/install/busybox_info.h]: Should we be calling `unsetenv(Argv0OverrideEnv)` before we carry on and perform other work that might exec another copy of ourselves (maybe in the busybox `Main`)? Persisting this into the environment of our children seems like it'd cause problems (eg, if we try to run a symbolizer and this overrides it and instead invokes the toolchain, that'd seem bad).

File: toolchain/install/busybox_info.h [hunk 5]
```diff
@@ -24,6 +25,15 @@ struct BusyboxInfo {
   std::optional<std::string> mode;
 };
 
+// The mode is set to the initial filename used for `argv[0]`.
+static auto GetMode(const char* argv0) -> std::optional<std::string> {
```
Comment (zygoloid) [inline toolchain/install/busybox_info.h]: Don't define static functions in a header file. Maybe most of this file should be moved to a `.cpp` file?

File: common/exe_path.h (hunk 2 above)
Comment (jonmeow) [reply common/exe_path.h]: Done

File: common/exe_path.h (hunk 3 above)
Comment (jonmeow) [reply common/exe_path.h]: Done

File: toolchain/install/busybox_info.h (hunk 4 above)
Comment (jonmeow) [reply toolchain/install/busybox_info.h]: Done, but note I don't think I was changing this, and it's only for //toolchain/carbon (that single target)

Comment (jonmeow) [reply toolchain/install/busybox_info.h]: And I should add -- for //toolchain:toolchain, we set LLVM_SYMBOLIZER_PATH in contexts where this would be used. So it wouldn't affect symbolizer.

File: toolchain/install/busybox_info.h (hunk 5 above)
Comment (jonmeow) [reply toolchain/install/busybox_info.h]: Sorry, that's my mistake.

Anyways, sure refactoring out a cpp

File: common/exe_path.cpp (hunk 1 above)
Comment (jonmeow) [reply common/exe_path.cpp]: Done

File: toolchain/install/busybox_info.h [hunk 6]
```diff
@@ -6,15 +6,15 @@
...
 #include <string>
 
 #include "common/error.h"
-#include "llvm/ADT/StringRef.h"
 
 namespace Carbon {
 
+// An optional override of argv0, particularly used by `//toolchain/carbon` to
+// get desired behavior without further special-casing.
 constexpr const char* Argv0OverrideEnv = "CARBON_ARGV0_OVERRIDE";
```
Comment (zygoloid) [inline toolchain/install/busybox_info.h]: While we're factoring stuff out: this should either be `inline` or have its definition moved to the `.cpp` file too, to avoid ODR issues.
```suggestion
inline constexpr const char* Argv0OverrideEnv = "CARBON_ARGV0_OVERRIDE";
```

File: toolchain/install/busybox_info_test.cpp [hunk 7]
```diff
@@ -294,7 +315,7 @@ TEST_F(BusyboxInfoTest, EnvBinaryPathOverride) {
   auto _ = llvm::make_scope_exit([] { unsetenv(Argv0OverrideEnv); });
```
Comment (zygoloid) [inline toolchain/install/busybox_info_test.cpp]: I guess you can drop this now (or better, test that `getenv(Argv0OverrideEnv) == nullptr` after calling `GetBusyboxInfo`)

**Review by zygoloid — APPROVED** [review]
Thanks!

File: toolchain/install/busybox_info.h (hunk 6 above)
Comment (jonmeow) [reply toolchain/install/busybox_info.h]: Done -- it's used by the test (so just leaving it here).

File: toolchain/install/busybox_info_test.cpp (hunk 7 above)
Comment (jonmeow) [reply toolchain/install/busybox_info_test.cpp]: Sure, done with testing

**Review by zygoloid — APPROVED** [review]
