### PR TITLE
Fix for: missing check that deduced argument converts to type of parameter #1300

### LINKED ISSUE #1300: missing check that deduced argument converts to type of parameter
Testcase:

```
package Foo api;
fn Get[T:! ()](n: T) -> T { return n; }
fn Main() -> i32 {
  var z: i32 = 0;
  return Get(z);
}
```

This is accepted. Apparently we don't check that the value `T = i32` that we deduce is actually convertible to the type `()` declared for the binding.

### PR DESCRIPTION
**Pull request by pmqtt**
Fix #1300

### CODE REVIEW

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -1370,9 +1386,35 @@ auto TypeChecker::DeduceCallBindings(
 
   // Convert the arguments to the parameter type.
   Nonnull<const Value*> param_type = Substitute(generic_bindings, params_type);
+
+  // Test is substituted param is convertible to the original type.
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: Instead of checking this here, I think it would be better to check for a conversion in `ArgumentDeduction`, somewhere around line 665, if that works. That way we will check this for all users of deduction, and hopefully can avoid some of the complexity here in working out which things we need to check.

**Review by zygoloid — CHANGES_REQUESTED** [review]
Thanks for working on this!

**Comment by pmqtt** [comment]
Yes, I tried to implement it in ArgumentDeduction. Unfortunately, I don't remember what exactly was missing at that point, but I didn't succeed there. I can try again there!

File: explorer/interpreter/type_checker.cpp [hunk 2]
```diff
@@ -649,6 +780,22 @@ auto TypeChecker::ArgumentDeduction(
                                           << "actual: " << *arg;
     }
     const Value* subst_param_type = Substitute(deduced, param);
+    if (param->kind() == Value::Kind::VariableType) {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: I think this logic would fit better in the `case VariableType` code below rather than in `handle_non_deduced_type`, because I think we want to use it for all `VariableType` cases regardless of whether the parameter type is deduced. Perhaps we could do this check at the start of that `case`, on line 808?

File: explorer/interpreter/type_checker.cpp [hunk 3]
```diff
@@ -649,6 +780,22 @@ auto TypeChecker::ArgumentDeduction(
...
+      const auto& binding = cast<VariableType>(*param).binding();
+      if (binding.has_static_type()) {
+        if (binding.static_type().kind() != Value::Kind::TypeType &&
+            binding.static_type().kind() != Value::Kind::ConstraintType &&
+            binding.static_type().kind() != Value::Kind::InterfaceType) {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: A comment explaining why we exclude these cases would be useful. I'm not sure if this is "TODO: We don't implement proper convertibility checking for types yet" or if it's "don't check constraint types because they'll be checked separately by the caller later" or something else.

Can you use `IsTypeOfType` here?

File: explorer/interpreter/type_checker.cpp [hunk 4]
```diff
@@ -649,6 +780,22 @@ auto TypeChecker::ArgumentDeduction(
...
+          if (!IsImplicitlyConvertible(subst_param_type, &binding.static_type(),
+                                       impl_scope, true)) {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: If there is a user-defined conversion here, we'll need to invoke it at some point. But... can we ever need a user-defined conversion here? I think the answer might be no: there are no user-defined type-of-types, so there can be no user-defined conversions on types. Passing `false` for `allow_user_defined_conversions` seems like it might be safer for now.

File: explorer/interpreter/type_checker.cpp [hunk 5]
```diff
@@ -1370,9 +1531,13 @@ auto TypeChecker::DeduceCallBindings(
 
   // Convert the arguments to the parameter type.
   Nonnull<const Value*> param_type = Substitute(generic_bindings, params_type);
+
+  // Test is substituted param is convertible to the original type.
+
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
  // Convert the arguments to the deduced and substituted parameter type.
```
maybe?

File: explorer/interpreter/type_checker.cpp [hunk 6]
```diff
@@ -1299,6 +1446,21 @@ auto TypeChecker::CombineConstraints(
...
+      return &binding.static_type();
+    }
+    case Value::Kind::TupleValue: {
+      return ResolveType(cast<TupleValue>(*source).elements()[0]);
+    }
+    default:
+      return source;
+  }
+}
+
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: This is unused and can be removed.

File: explorer/interpreter/type_checker.cpp [hunk 7]
```diff
@@ -619,6 +620,136 @@ auto TypeChecker::ExpectType(SourceLocation source_loc,
     return Success();
   }
 }
+void test(Nonnull<const Value*> type) {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: Looks like a now-unused debugging aid. Please remove :)

**Review by zygoloid — COMMENTED** [review]
Thanks, this makes a lot of sense :)

**Comment by pmqtt** [comment]
@zygoloid  thank you for review!

File: explorer/interpreter/type_checker.cpp [hunk 8]
```diff
@@ -662,6 +663,21 @@ auto TypeChecker::ArgumentDeduction(
...
                     &var_type.binding()) != bindings_to_deduce.end()) {
         auto [it, success] = deduced.insert({&var_type.binding(), arg});
+
+        const Value* substituted_param_type = Substitute(deduced, param);
+        const auto& binding = cast<VariableType>(*param).binding();
+        if (binding.has_static_type()) {
+          if (!IsTypeOfType(&binding.static_type())) {
+            if (!IsImplicitlyConvertible(substituted_param_type,
+                                         &binding.static_type(), impl_scope,
+                                         false)) {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
            if (!IsImplicitlyConvertible(substituted_param_type,
                                         arg, impl_scope, false)) {
```
It seems to me that we should be checking that the argument converts to the parameter type here, not that the parameter converts to its own substituted type. Or am I missing something?

File: explorer/interpreter/type_checker.cpp [hunk 9]
```diff
@@ -674,11 +690,10 @@ auto TypeChecker::ArgumentDeduction(
                    << var_type.binding() << ":\n  " << *it->second << "\n  "
                    << *arg;
           }
+          return Success();
         }
-      } else {
-        return handle_non_deduced_type();
       }
-      return Success();
+      return handle_non_deduced_type();
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: Do we still need this change? If the binding for the `VariableType` is in `deduced`, then we're not in the "non-deduced type" case so I would think we don't need to do this.

File: explorer/interpreter/type_checker.cpp [hunk 10]
```diff
@@ -662,6 +663,21 @@ auto TypeChecker::ArgumentDeduction(
...
+        const Value* substituted_param_type = Substitute(deduced, param);
+        const auto& binding = cast<VariableType>(*param).binding();
+        if (binding.has_static_type()) {
+          if (!IsTypeOfType(&binding.static_type())) {
+            if (!IsImplicitlyConvertible(substituted_param_type,
+                                         &binding.static_type(), impl_scope,
+                                         false)) {
+              return CompilationError(source_loc)
+                     << "Could not convert argument " << *substituted_param_type
+                     << " to parameter type " << binding.static_type();
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
                     << "cannot convert deduced value " << *arg
                     << " for " << binding.name()
                     << " to parameter type " << *substituted_param_type;
```
It'd be nice to list the parameter name here too, since we have it.

File: explorer/interpreter/type_checker.cpp (hunk 9 above)
Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: you are right

File: explorer/interpreter/type_checker.cpp [hunk 11]
```diff
@@ -662,6 +663,21 @@ auto TypeChecker::ArgumentDeduction(
...
+            if (!IsImplicitlyConvertible(substituted_param_type,
+                                         arg, impl_scope, false)) {
+              return CompilationError(source_loc)
+                     << "cannot convert deduced value " << *arg
+                     << " for " << binding.name()
+                     << " to parameter type " << *substituted_param_type;
+            }
+          }
+        }
+
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
      const auto& binding = var_type.binding();
      if (std::find(bindings_to_deduce.begin(), bindings_to_deduce.end(),
                    &binding) != bindings_to_deduce.end()) {
        if (binding.has_static_type()) {
          const auto* binding_type = Substitute(deduced, &binding.static_type());
          if (!IsTypeOfType(binding_type) &&
              !IsImplicitlyConvertible(
                  arg, binding_type, impl_scope,
                  /*allow_user_defined_conversions*/ false)) {
            return CompilationError(source_loc)
                   << "cannot convert deduced value " << *arg << " for parameter "
                   << binding.name() << " to parameter type "
                   << *binding_type;
          }
        }

        auto [it, success] = deduced.insert({&binding, arg});
```

Main change here is substituting into the type of the binding rather than into the `VariableType` value. I also reversed the arguments to `IsImplicitlyConvertible`, which I got wrong in a previous suggested edit.

File: explorer/interpreter/type_checker.cpp [hunk 12]
```diff
@@ -659,6 +660,20 @@ auto TypeChecker::ArgumentDeduction(
...
+        if (!IsTypeOfType(&binding.static_type())) {
+          if (!IsImplicitlyConvertible(substituted_param_type, arg, impl_scope,
+                                       false)) {
+            return CompilationError(source_loc)
+                   << "cannot convert deduced value " << *arg << " for "
+                   << binding.name() << " to parameter type "
+                   << *substituted_param_type;
+          }
+        }
+      }
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
      const auto& binding = cast<VariableType>(*param).binding();
      if (binding.has_static_type()) {
        const Value* binding_type = Substitute(deduced, &binding.static_type());
        if (!IsTypeOfType(binding_type)) {
          if (!IsImplicitlyConvertible(arg, binding_type, impl_scope,
                                       false)) {
            return CompilationError(source_loc)
                   << "cannot convert deduced value " << *arg << " for parameter "
                   << binding.name() << " to parameter type "
                   << *binding_type;
          }
        }
      }
```

Two things here:
1) I got the argument order to `IsImplicitlyConvertible` backwards in a previous suggested edit, sorry about that.
2) I think we want to substitute into the type of the binding, not into `param`. Eg, if we have `[T:! Type, U:! ImplicitAs(T)](x: T, y: U)` then when checking the deduced argument for `U`, we want to see if it's implicitly convertible to `ImplicitAs(T)` after substituting in the deduced value for `T`. Substituting into `param` itself will result in either `param` or whatever value we already deduced for `U`.

**Review by zygoloid — APPROVED** [review]
