### PR TITLE
Fix handling of enums in overload resolution.

### LINKED ISSUE #6061: C++ Interop: Fix enums support once overload resolution (PR #5891) lands.
Error message `error: no matching function for call to X [CppOverloadingNoViableFunctionFound] `.

Test file: [toolchain/lower/testdata/interop/cpp/enum.carbon](https://github.com/carbon-language/carbon-lang/blob/508a88e2a995c9f3342b019cee6948c162004b68/toolchain/lower/testdata/interop/cpp/enum.carbon).

Tests are marked with `fail_todo_5891*`.

Context: PR #5891.

### PR DESCRIPTION
**Pull request by zygoloid**
When mapping Carbon types to C++ types, check first for the Carbon type being imported from C++ before checking whether it's an adapter for a builtin. Enums imported from C++ will be both, and it's important we map them back to the enum type rather than to their underlying (integer) type.

Fixes #6061

### CODE REVIEW

**Review by josh11b — APPROVED** [review]

File: toolchain/check/cpp_type_mapping.cpp [hunk 1]
```diff
@@ -127,9 +127,9 @@ static auto TryMapClassType(Context& context, SemIR::TypeId type_id)
 // Maps a non-wrapper (no const or pointer) Carbon type to a C++ type.
 static auto MapNonWrapperType(Context& context, SemIR::InstId inst_id,
                               SemIR::TypeId type_id) -> clang::QualType {
-  clang::QualType mapped_type = TryMapBuiltinType(context, inst_id, type_id);
+  clang::QualType mapped_type = TryMapClassType(context, type_id);
```
Comment (josh11b) [inline toolchain/check/cpp_type_mapping.cpp:135]: Add a comment explaining why it is important to check class types before builtins?
