### PR TITLE
Fix explorer crash - Assign different struct types 

### LINKED ISSUE #1392: explorer crashes on tuple assignment with duplicate field initializer
```
package P api;

fn Main() -> i32 {
  var p: auto = {.x = 0, .y = 0};
  p = {.y = 0, .y = 0};
  return 0;
}

$ bazel run explorer:explorer -- /tmp/crash.carbon
.../include/c++/v1/optional:920: _LIBCPP_ASSERT 'this->has_value()' failed. optional operator* called on a disengaged value

```

### PR DESCRIPTION
**Pull request by pmqtt**
Hope it is useful!

### CODE REVIEW

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -356,6 +356,12 @@ auto TypeChecker::FieldTypesImplicitlyConvertible(
   if (source_fields.size() != destination_fields.size()) {
     return false;
   }
+  // exist every field name in destination
```
Comment (jonmeow) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
  // Ensure every field name exists in the destination.
```

File: explorer/testdata/struct/fail_assign_different_types.carbon [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// AUTOUPDATE
+// RUN: %{not} %{explorer-run}
+// RUN: %{not} %{explorer-run-trace}
+
+package ExplorerTest api;
+
+fn Main() -> i32 {
+  var p: auto = {.x = 0, .y = 0};
+  // CHECK:STDERR: COMPILATION ERROR: {{.*}}/explorer/testdata/struct/fail_assign_different_types.carbon:[[@LINE+1]]: type error in assignment: '{.y: i32, .y: i32}' is not implicitly convertible to '{.x: i32, .y: i32}'
+  p = {.y = 0, .y = 0};
```
Comment (jonmeow) [inline explorer/testdata/struct/fail_assign_different_types.carbon]: This case should be an error because it's trying to assign the same value twice, and that should be detected before the implicit conversion: can this be tested differently?

Comment (pmqtt) [reply explorer/testdata/struct/fail_assign_different_types.carbon]: Done!

Comment (jonmeow) [reply explorer/testdata/struct/fail_assign_different_types.carbon]: I'm not seeing a change, did you miss a push?

Comment (pmqtt) [reply explorer/testdata/struct/fail_assign_different_types.carbon]: Sorry i forgot to push!

File: explorer/testdata/struct/fail_assign_different_types.carbon [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+// AUTOUPDATE
+// RUN: %{not} %{explorer-run}
+// RUN: %{not} %{explorer-run-trace}
+
+package ExplorerTest api;
+
+fn Main() -> i32 {
+  var p: auto = {.x = 0, .y = 0};
+  // CHECK:STDERR: COMPILATION ERROR: {{.*}}/explorer/testdata/struct/fail_assign_different_types.carbon:[[@LINE+1]]: type error in assignment: '{.z: i32, .y: i32}' is not implicitly convertible to '{.x: i32, .y: i32}'
+  p = {.z = 0, .y = 0};
```
Comment (jonmeow) [inline explorer/testdata/struct/fail_assign_different_types.carbon]: So, I think this gets to the crux of the test: won't this fail because of the logic on 368, because a destination field won't be found for `z`?

How about this: do `{.y = 0,}`, but remove the `.size()` check on 356. Add a TODO to your new code that it should skip defaulted fields once they're added.

I say this because the `.size()` check will need to be removed anyways once defaulted fields are supported, and your new code should provide equivalent logic.

File: explorer/interpreter/type_checker.cpp [hunk 4]
```diff
@@ -353,9 +353,8 @@ auto TypeChecker::FieldTypesImplicitlyConvertible(
     llvm::ArrayRef<NamedValue> source_fields,
     llvm::ArrayRef<NamedValue> destination_fields,
     const ImplScope& impl_scope) const -> bool {
-  if (source_fields.size() != destination_fields.size()) {
-    return false;
-  }
+  // Todo: If default fields are implemented, the
+  //       code must be adapted to skip them
```
Comment (jonmeow) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
  // TODO: If default fields are implemented, the
  // code must be adapted to skip them.
```

We do all-caps TODOs so that they're easier to grep for.

**Review by jonmeow — APPROVED** [review]
Thanks! Feel free to merge. :)
