### PR TITLE
Explorer: Report compiletime error when global variable type is abstract

### LINKED ISSUE #2747: Explorer: attempting to instantiate an `abstract` class on global variables does not error as expected
### Description of the bug:

Explorer does not error when attempting to instantiate an abstract class as a global variable.

### What did you do, or what's a simple way to reproduce the bug?

Declare an `abstract` class, and instantiate it as a global variable with Carbon Explorer
https://carbon.compiler-explorer.com/z/j4hvevfE8

### What did you expect to happen?

Explorer should generate an error, as `abstract` class are not allowed to be instantiated directly.

Note that intantiating a **local variable** does trigger the proper error, as demonstrated here: https://carbon.compiler-explorer.com/z/o6Gd33Tdh, with the error
```
RUNTIME ERROR: <source>:8: Cannot instantiate abstract class B
Compiler returned: 1
```

### What actually happened?

No error generated.

### Recommended approach

Take example from `VariableDefinition` (local variable): https://github.com/carbon-language/carbon-lang/blob/65578bd8db2ff8567db9d5393a24935291c26b12/explorer/interpreter/interpreter.cpp#L2015-L2025
Use similar logic for `VariableDeclaration`.

The changes needed for `VariableDeclaration` might be from `VariableDefinition`, but the logic should about the same.

For reference, the syntax and logic leading to instantiation of `VariableDeclaration` and `VariableDefinition` can be found in `parser.ypp`

### Resources

* https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md
* https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md
* `#contributing-help` channel on the Discord

**Note**: Anyone can work on this issue immediately, and does not need to be assigned

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Add concrete type check for Variable Declaration to report a compile time error when the variable type is abstract

Closes #2747

### CODE REVIEW

File: explorer/interpreter/interpreter.cpp [hunk 1]
```diff
@@ -2210,6 +2210,15 @@ auto Interpreter::StepDeclaration() -> ErrorOr<Success> {
...
       const auto& var_decl = cast<VariableDeclaration>(decl);
       if (var_decl.has_initializer()) {
+        auto initializer = &var_decl.binding().static_type();
+        if (const auto* dest_class = dyn_cast<NominalClassType>(initializer)) {
+          if (dest_class->declaration().extensibility() ==
+              ClassExtensibility::Abstract) {
+            return ProgramError(var_decl.source_loc())
+                   << "Cannot instantiate abstract class "
+                   << dest_class->declaration().name();
+          }
```
Comment (zygoloid) [inline explorer/interpreter/interpreter.cpp]: Please can you factor this out into a separate function, perhaps `ExpectNonAbstractType` or `ExpectConcreteType`? I expect we'll want to do this from a few different places in the type checker.

File: explorer/interpreter/interpreter.cpp [hunk 2]
```diff
@@ -2210,6 +2210,15 @@ auto Interpreter::StepDeclaration() -> ErrorOr<Success> {
     case DeclarationKind::VariableDeclaration: {
       const auto& var_decl = cast<VariableDeclaration>(decl);
       if (var_decl.has_initializer()) {
+        auto initializer = &var_decl.binding().static_type();
+        if (const auto* dest_class = dyn_cast<NominalClassType>(initializer)) {
```
Comment (zygoloid) [inline explorer/interpreter/interpreter.cpp]: This check should be performed by the type-checker, not by the interpreter. A good place would be `TypeChecker::DeclareDeclaration`, where we currently call `ExpectCompleteType`.

**Review by zygoloid — CHANGES_REQUESTED** [review]

**Review by zygoloid — COMMENTED** [review]
Please update the summary of this PR to describe what is being changed, rather than describing the problem that this change fixes. See [our documentation](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/code_review.md#write-good-change-descriptions) on how we'd like commit messages to be written.

File: explorer/interpreter/interpreter.cpp (hunk 1 above)
Comment (AmrDeveloper) [reply explorer/interpreter/interpreter.cpp]: Done

File: explorer/interpreter/interpreter.cpp (hunk 2 above)
Comment (AmrDeveloper) [reply explorer/interpreter/interpreter.cpp]: Done

**Comment by AmrDeveloper** [comment]
> Please update the summary of this PR to describe what is being changed, rather than describing the problem that this change fixes. See [our documentation](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/code_review.md#write-good-change-descriptions) on how we'd like commit messages to be written.

Done, I think we should move the check for VariableDefinition to type checker too and make it compile time error

File: explorer/interpreter/type_checker.cpp [hunk 3]
```diff
@@ -309,6 +309,21 @@ static auto ExpectCompleteType(SourceLocation source_loc,
          << "incomplete type `" << *type << "` used in " << context;
 }
 
+// Expect that a type is concrete. Issue a diagnostic if not.
+static auto ExpectConcreteType(SourceLocation source_loc,
```
Comment (Pixep) [inline explorer/interpreter/type_checker.cpp:313]: Great! Would that be useable for `VariableDefinition` as well?

Comment (AmrDeveloper) [reply explorer/interpreter/type_checker.cpp:313]: > Great! Would that be useable for `VariableDefinition` as well?

Sure once this PR is merged I will use it for VariableDefinition and move implementation from Interpreter to Type Checker

Comment (Pixep) [reply explorer/interpreter/type_checker.cpp:313]: **Edit**: Nevermind, I initially missed the conversation above 👍

**Review by zygoloid — APPROVED** [review]
