### PR TITLE
Handle runtime implicit parameters, and `self` outside of methods

### LINKED ISSUE #4356: CHECK failure when using runtime implicit parameter
### Description of the bug:

Defining a method with an improperly declared `addr` implicit parameter can cause the compiler to crash with a CHECK failure if that method is then called.

### What did you do, or what's a simple way to reproduce the bug?

```
$ cat /tmp/tb.carbon
class Cell {
  fn Put[addr NOTSELF: Self]() -> Cell;
}

fn Main() -> i32 {
  var c: Cell;
  c.Put();
}
$ bazel run -c dbg //toolchain -- compile --phase=check /tmp/tb.carbon
```

### What did you expect to happen?

Give diagnostics and not crash. Replacing `NOTSELF` with `self` leads to diagnostics, but no check failure..

### What actually happened?

```
$ bazel run -c dbg //toolchain -- compile --phase=check /tmp/tb.carbon
...
1.      Pending diagnostics:
/tmp/tb.carbon:2:10: error: `addr` can only be applied to a `self` parameter
  fn Put[addr NOTSELF: Self]() -> Cell;
         ^~~~
2.      Check::Context
          NodeStack:
            0. FunctionDefinitionStart: function2
          inst_block_stack_:
            0. block<invalid> {
                package: <namespace> = namespace [template] {
                  .Core = <unexpected>.inst+2
                  .Cell = <unexpected>.inst+3.loc1_12
                  .Main = <unexpected>.inst+27.loc5_18
                }
                <unexpected>.inst+1 = import Core
                <unexpected>.inst+3.loc1_12: type = class_decl @Cell [template = constants.%Cell] {} {}
                <unexpected>.inst+27.loc5_18: %Main.type = fn_decl @Main [template = constants.%Main] {} {
                  <unexpected>.inst+23.loc5_14: init type = call constants.%Int32() [template = i32]
                  <unexpected>.inst+24.loc5_14: type = value_of_initializer <unexpected>.inst+23.loc5_14 [template = i32]
                  <unexpected>.inst+25.loc5_14: type = converted <unexpected>.inst+23.loc5_14, <unexpected>.inst+24.loc5_14 [template = i32]
                  %return: ref i32 = var <return slot>
                }
              }
            1. block9 {
                <unexpected>.inst+30.loc6_10: type = name_ref Cell, <unexpected>.inst+3.loc1_12 [template = constants.%Cell]
                <unexpected>.inst+32.loc6_7: ref %Cell = var c
                <unexpected>.inst+33.loc6_7: ref %Cell = bind_name c, <unexpected>.inst+32.loc6_7
                <unexpected>.inst+34.loc7_3: ref %Cell = name_ref c, <unexpected>.inst+33.loc6_7
                <unexpected>.inst+35.loc7_4: %Put.type = name_ref Put, @Cell.%Put.decl [template = constants.%Put]
                <unexpected>.inst+36.loc7_8: ref %Cell = temporary_storage
              }
          pattern_block_stack_:
          param_and_arg_refs_stack:
            0. block<invalid> {}
          args_type_info_stack_:
3.      /tmp/tb.carbon:7:3: checking CallExpr
            c.Put();
            ^~~~~~~
...
#10 0x0000555570b9425c Carbon::Check::ConvertCallArgs(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, llvm::ArrayRef<Carbon::SemIR::InstId>, Carbon::SemIR::InstId, Carbon::Check::CalleeParamsInfo const&, Carbon::SemIR::SpecificId) /proc/self/cwd/toolchain/check/convert.cpp:1221:7
#11 0x0000555570b6864e Carbon::Check::PerformCall(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, llvm::ArrayRef<Carbon::SemIR::InstId>) /proc/self/cwd/toolchain/check/call.cpp:187:28
#12 0x0000555570a99d68 Carbon::Check::HandleParseNode(Carbon::Check::Context&, Carbon::Parse::NodeIdForKind<Carbon::Parse::NodeKind::CallExpr>) /proc/self/cwd/toolchain/check/handle_call_expr.cpp:32:18
#13 0x0000555570a4dd1a Carbon::Check::ProcessNodeIds(Carbon::Check::Context&, llvm::raw_ostream*, Carbon::ErrorTrackingDiagnosticConsumer&, Carbon::Parse::NodeLocConverter&) /proc/self/cwd/./toolchain/parse/node_kind.def:209:1
#14 0x0000555570a36645 Carbon::Check::CheckParseTree(llvm::MutableArrayRef<Carbon::Parse::NodeLocConverter>, Carbon::Check::(anonymous namespace)::UnitInfo&, int, llvm::raw_ostream*) /proc/self/cwd/toolchain/check/check.cpp:905:8
#15 0x0000555570a33c20 Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, llvm::MutableArrayRef<Carbon::Parse::NodeLocConverter>, bool, llvm::raw_ostream*) /proc/self/cwd/toolchain/check/check.cpp:1246:5
...
CHECK failure at toolchain/check/convert.cpp:1222: !param.runtime_index.is_valid(): Unexpected implicit parameter passed at runtime
```

### Any other information, logs, or outputs that you want to share?

This error was found by fuzz testing. I've manually minimized the example.

### PR DESCRIPTION
**Pull request by josh11b**
Closes #4356, #4359

### CODE REVIEW

File: toolchain/check/generic.cpp [hunk 1]
```diff
@@ -421,27 +421,63 @@ auto ResolveSpecificDefinition(Context& context, SemIR::SpecificId specific_id)
...
+        !context.constant_values().Get(inst_id).is_constant()) {
+      CARBON_DIAGNOSTIC(
+          ImplictParamMustBeConstant, Error,
+          "implicit parameters of functions must be constant or `self`");
+      context.emitter().Emit(inst_id, ImplictParamMustBeConstant);
+
+      ReplaceInstructionWithError(context, inst_id);
     }
   }
 }
```
Comment (zygoloid) [inline toolchain/check/generic.cpp]: These look very similar; would it make sense to combine these into a single function? Eg:
```c++
auto RequireGenericParams(Context& context, SemIR::InstBlockId block_id, bool allow_self)
    -> void {
  if (!block_id.is_valid() || block_id == SemIR::InstBlockId::Empty) {
    return;
  }
  for (auto& inst_id : context.inst_blocks().Get(block_id)) {
    // TODO: Change GetParamFromParamRefId to return the name instead of
    // inspecting param.name_id.
    auto [param_id, param] =
        SemIR::Function::GetParamFromParamRefId(context.sem_ir(), inst_id);
    if (param.name_id == SemIR::NameId::SelfValue) {
      if (!allow_self) {
        CARBON_DIAGNOSTIC(SelfParameterNotAllowed, Error,
                          "`self` parameter only allowed on functions");
        context.emitter().Emit(inst_id, SelfParameterNotAllowed);

        ReplaceInstructionWithError(context, inst_id);
      }
    } else if (!context.constant_values().Get(inst_id).is_constant()) {
      CARBON_DIAGNOSTIC(
          ImplicitParamMustBeConstant, Error,
          "parameters of generic types must be constant");
      CARBON_DIAGNOSTIC(
          ImplictParamMustBeConstantOrSelf, Error,
          "implicit parameters of functions must be constant or `self`");
      context.emitter().Emit(
          inst_id,
          allow_self ? ImplicitParamMustBeConstantOrSelf : ImplicitParamMustBeConstant);

      ReplaceInstructionWithError(context, inst_id);
    }
  }
}
```

**Review by zygoloid — APPROVED** [review]

File: toolchain/check/generic.cpp (hunk 1 above)
Comment (josh11b) [reply toolchain/check/generic.cpp]: Changing the function name, as discussed offline.

**Review by zygoloid — APPROVED** [review]
