### PR TITLE
Deduce the FacetValue for an argument for a generic FacetType parameter

### LINKED ISSUE #4868: eval.cpp:1818: phase != Phase::Template: Failed to evaluate template constant {kind: ImplWitnessAccess ...
### Description of the bug:

I derived this from the [explorer fuzzer corpus ca69be54b8273f334ab8c7db0ad454c5ff0291c9](https://github.com/carbon-language/carbon-lang/blob/7d2958ad37571d2a76deb5554daa8672cea518de/toolchain/check/fuzzer_corpus/ca69be54b8273f334ab8c7db0ad454c5ff0291c9). I introduced a check failure in #4865 once the toolchain began successfully deducing a facet value generic parameter. But when I remove the deduced parameters from the function and make them explicit, I see the same check happening on trunk.

```
// Part of the Carbon Language project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// AUTOUPDATE
// TIP: To test this file alone, run:
// TIP:   bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
// TIP: To dump output, run:
// TIP:   bazel run //toolchain/testing:file_test -- --dump_output --file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon

// --- core.carbon

package Core;

interface ImplicitAs(T:! type) {
  fn Convert[self: Self]() -> T;
}

// --- fail_fuzzer.carbon

library "[[@TEST_NAME]]";

import Core;

interface Generic(Scalar:! type) {
  fn F();
}

class GenericParam {}

class ImplsGeneric {}
impl ImplsGeneric as Generic(GenericParam) {
  fn F() {}
}

fn CallGenericMethod(T:! type, U:! Generic(T)) {
  U.F();
}

fn G() {
  CallGenericMethod(GenericParam, ImplsGeneric);
}
```

```
= toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test --test_targets_file=toolchain/testing/file_test.tests --dump_output --file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
1.      Program arguments: compile --include-diagnostic-kind --phase=check --dump-sem-ir --no-prelude-import --exclude-dump-file-prefix=/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/install/prefix_root/lib/carbon/../../lib/carbon/core core.carbon fail_fuzzer.carbon
2.      Pending diagnostics:
fail_fuzzer.carbon:22:3: error: value of type `<type of F>` is not callable [CallToNonCallable]
  U.F();
  ^~~~~
3.      Check::Context
          NodeStack:
          inst_block_stack_:
            0.  inst_block<none>        {inst12, inst13, inst21, inst42, inst47, inst55, inst60, inst84, inst118}
          pattern_block_stack_:
          param_and_arg_refs_stack:
          args_type_info_stack_:
 #0 0x000055d5e4eb23c9 ___interceptor_backtrace (/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0xb97f3c9)
 #1 0x000055d5f1c54296 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:800:13
 #2 0x000055d5f1c54d8b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:876:1
 #3 0x000055d5f1c4e8e0 llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x000055d5f1c550d3 SignalHandler(int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #5 0x00007fab72404590 (/lib/x86_64-linux-gnu/libc.so.6+0x3f590)
 #6 0x00007fab724533ac __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #7 0x00007fab724044f2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007fab723ed4ed abort ./stdlib/abort.c:81:7
 #9 0x000055d5f1524d5d Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:42:3
#10 0x000055d5e7aeaa64 void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{char [6]{(char)67, (char)72, (char)69, (char)67, (char)75}}, Carbon::TemplateString<24>{char [25]{(char)116, (char)111, (char)111, (char)108, (char)99, (char)104, (char)97, (char)105, (char)110, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)47, (char)101, (char)118, (char)97, (char)108, (char)46, (char)99, (char)112, (char)112}}, 1818, Carbon::TemplateString<24>{char [25]{(char)112, (char)104, (char)97, (char)115, (char)101, (char)32, (char)33, (char)61, (char)32, (char)80, (char)104, (char)97, (char)115, (char)101, (char)58, (char)58, (char)84, (char)101, (char)109, (char)112, (char)108, (char)97, (char)116, (char)101}}, Carbon::TemplateString<50>{char [51]{(char)70, (char)97, (char)105, (char)108, (char)101, (char)100, (char)32, (char)116, (char)111, (char)32, (char)101, (char)118, (char)97, (char)108, (char)117, (char)97, (char)116, (char)101, (char)32, (char)116, (char)101, (char)109, (char)112, (char)108, (char)97, (char)116, (char)101, (char)32, (char)99, (char)111, (char)110, (char)115, (char)116, (char)97, (char)110, (char)116, (char)32, (char)123, (char)48, (char)125, (char)32, (char)97, (char)114, (char)103, (char)48, (char)58, (char)32, (char)123, (char)49, (char)125}}, Carbon::SemIR::Inst&, Carbon::SemIR::Inst>(Carbon::SemIR::Inst&, Carbon::SemIR::Inst&&) /proc/self/cwd/./common/check_internal.h:0:5
#11 0x000055d5e7adf6dd Carbon::Check::TryEvalInstInContext(Carbon::Check::(anonymous namespace)::EvalContext&, Carbon::SemIR::InstId, Carbon::SemIR::Inst) /proc/self/cwd/toolchain/check/eval.cpp:0:11
#12 0x000055d5e7ae2370 Carbon::Check::TryEvalBlockForSpecific(Carbon::Check::Context&, Carbon::Check::SemIRLoc, Carbon::SemIR::SpecificId, Carbon::SemIR::GenericInstIndex::Region) /proc/self/cwd/toolchain/check/eval.cpp:0:0
#13 0x000055d5e7b14e35 Carbon::Check::ResolveSpecificDefinition(Carbon::Check::Context&, Carbon::Check::SemIRLoc, Carbon::SemIR::SpecificId) /proc/self/cwd/toolchain/check/generic.cpp:0:32
#14 0x000055d5e78591fc Carbon::Check::CheckUnit::CheckRequiredDefinitions() /proc/self/cwd/toolchain/check/check_unit.cpp:449:13
#15 0x000055d5e78559a4 Carbon::Check::CheckUnit::Run() /proc/self/cwd/toolchain/check/check_unit.cpp:76:12
#16 0x000055d5e783357e Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::raw_ostream*, bool) /proc/self/cwd/toolchain/check/check.cpp:0:57
#17 0x000055d5e51f2c45 release /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:232:9
#18 0x000055d5e51f2c45 ~IntrusiveRefCntPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:196:27
#19 0x000055d5e51f2c45 Carbon::CompileSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/compile_subcommand.cpp:869:3
#20 0x000055d5e51eacfd Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:0:39
#21 0x000055d5e4f4ced0 Carbon::Testing::(anonymous namespace)::ToolchainFileTest::Run(llvm::SmallVector<llvm::StringRef, 3u> const&, llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem>&, _IO_FILE*, llvm::raw_pwrite_stream&, llvm::raw_pwrite_stream&) /proc/self/cwd/toolchain/testing/file_test.cpp:0:31
#22 0x000055d5e4f77c88 Carbon::Testing::FileTestBase::ProcessTestFileAndRun(Carbon::Testing::FileTestBase::TestContext&) /proc/self/cwd/testing/file_test/file_test_base.cpp:374:3
#23 0x000055d5e4f7e49a index /usr/lib/llvm-17/bin/../include/c++/v1/variant:821:12
#24 0x000055d5e4f7e49a index /usr/lib/llvm-17/bin/../include/c++/v1/variant:1474:60
#25 0x000055d5e4f7e49a __holds_alternative<1UL, Carbon::Error, Carbon::Success> /usr/lib/llvm-17/bin/../include/c++/v1/variant:1500:14
#26 0x000055d5e4f7e49a holds_alternative<Carbon::Success, Carbon::Error, Carbon::Success> /usr/lib/llvm-17/bin/../include/c++/v1/variant:1506:10
#27 0x000055d5e4f7e49a ok /proc/self/cwd/./common/error.h:90:36
#28 0x000055d5e4f7e49a Carbon::Testing::FileTestBase::DumpOutput() /proc/self/cwd/testing/file_test/file_test_base.cpp:268:19
#29 0x000055d5e4f8dc3f Main /proc/self/cwd/testing/file_test/file_test_base.cpp:0:27
#30 0x000055d5e4f8dc3f main /proc/self/cwd/testing/file_test/file_test_base.cpp:1201:10
#31 0x00007fab723eec8a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#32 0x00007fab723eed45 call_init ./csu/../csu/libc-start.c:128:20
#33 0x00007fab723eed45 __libc_start_main ./csu/../csu/libc-start.c:347:5
#34 0x000055d5e4e6bfe1 _start (/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0xb938fe1)
CHECK failure at toolchain/check/eval.cpp:1818: phase != Phase::Template: Failed to evaluate template constant {kind: ImplWitnessAccess, arg0: inst115, arg1: element0, type: type(symbolic_constant40)} arg0: {kind: FacetAccessWitness, arg0: inst48, type: type(inst(WitnessType))}
external/bazel_tools/tools/test/test-setup.sh: line 335: 2249647 Aborted                 (core dumped) "${TEST_PATH}" "$@" 2>&1
```

edit: fixed the stack trace to be complete

### PR DESCRIPTION
**Pull request by danakj**
When a function has a generic FacetType parameter, it can depend on other FacetTypes bound as earlier parameters. To deduce the FacetValue, we need to know the impl to attach to it, which requires knowing the
full type signature of the generic FacetType parameter. To do this, after deducing other arguments to determine the value of non-generic FacetType parameters, we substitute them sequentially into later
symbolic parameters to get their full facet types, then converts the arguments to those full facet types to get the FacetValue. For example:

```
fn F(T: type, U: Interface(T));
```

Here the `T` binding is deduced to the be the caller's argument type. But the Interface(T) can not be properly deduced to a FacetValue in the first pass, and it will just be the caller's argument type directly. After the first deduce pass, we will substitute the deduced T binding into Interface(T), at which point the argument type can and will be converted to a matching FacetValue as long as an impl can be found.

Closes #4868

This is based on PRs #4881 and #4863

### CODE REVIEW

**Comment by danakj** [comment]
Still a draft because I need to clean up the diagnostic in here tomorrow.

File: toolchain/check/deduce.cpp [hunk 1]
```diff
@@ -293,36 +306,23 @@ auto DeductionContext::Deduce() -> bool {
...
     } else {
-      // The argument needs to have the same type as the parameter.
-      // TODO: Suppress diagnostics here if diagnose_ is false.
-      // TODO: Only do this when deducing against a symbolic pattern.
-      DiagnosticAnnotationScope annotate_diagnostics(&context().emitter(),
-                                                     note_initializing_param);
+      // The argument may be a runtime value (e.g. TupleLiteral of types), but
+      // is convertible to a compile-time value (e.g. TupleType). So we do this
+      // conversion here, even though we will later try convert again when we
+      // have deduced all of the bindings.
```
Comment (zygoloid) [inline toolchain/check/deduce.cpp]: I think the "runtime value" / "compile-time value" distinction here is not quite right, because the cases we care about here are primarily the ones where the constant value of the argument is *not* `ConstantId::Runtime` (eg, tuple literals with compile time values). Maybe:
```suggestion
      // The argument (e.g. a TupleLiteral of types) may be convertible to a
      // compile-time value (e.g. TupleType) that we can decompose further.
      // So we do this conversion here, even though we will later try convert
      // again when we have deduced all of the bindings.
```
... if I'm correctly understanding why this is important. (Though if that's right, I guess we'd need to do something comparable when the parameter type is symbolic.)

Just for my information, what goes wrong if we remove this conversion?

File: toolchain/check/deduce.cpp [hunk 2]
```diff
@@ -496,8 +498,46 @@ auto DeductionContext::CheckDeductionIsComplete() -> bool {
...
 
+    // If the binding is symbolic it can refer to other earlier bindings in the
+    // same generic, or from an enclosing specific. Substitute to replace those
+    // and get a non-symbolic type in order for us to know the final type that
+    // the argument needs to be converted to.
+    //
+    // Note that when typechecking a function declaration, the arguments can
+    // still be symbolic, so the substitution would also be symbolic. We are
+    // unable to get the final type for symbolic bindings until deducing with
+    // non-symbolic arguments.
```
Comment (zygoloid) [inline toolchain/check/deduce.cpp:522]: Maybe add a TODO here that we should also defer the check that all deductions for a parameter produce the same argument until we get here and perform the conversion? (In case we deduce arguments with different types that convert to the same value.)

File: toolchain/check/deduce.cpp [hunk 3]
```diff
@@ -496,8 +498,46 @@ auto DeductionContext::CheckDeductionIsComplete() -> bool {
...
       return false;
     }
-  }
 
+    // If the binding is symbolic it can refer to other earlier bindings in the
+    // same generic, or from an enclosing specific. Substitute to replace those
+    // and get a non-symbolic type in order for us to know the final type that
+    // the argument needs to be converted to.
+    //
+    // Note that when typechecking a function declaration, the arguments can
```
Comment (zygoloid) [inline toolchain/check/deduce.cpp]:
```suggestion
    // Note that when typechecking a checked generic, the arguments can
```
I think this can happen anywhere where we're performing deduction with a checked generic parameter in scope, eg:

```
class A(T:! type, N:! T) {}
// Deduces T = U in call to A.
class B[U:! type, M:! U](X:! A(U, M)) {}
```

File: toolchain/check/deduce.cpp [hunk 4]
```diff
@@ -496,8 +498,46 @@ auto DeductionContext::CheckDeductionIsComplete() -> bool {
...
+      CARBON_CHECK(!param_type_const_id.is_symbolic());
+      binding_type_id = context().GetTypeIdForTypeConstant(param_type_const_id);
+
+      // TODO: Suppress diagnostics here if `diagnose_` is false.
+      DiagnosticAnnotationScope annotate_diagnostics(
+          &context().emitter(),
+          [&](auto& builder) { NoteInitializingParam(binding_id, builder); });
+      auto converted_arg_id = ConvertToValueOfType(
+          context(), loc_id_, deduced_arg_id, binding_type_id);
+      if (converted_arg_id != SemIR::ErrorInst::SingletonInstId) {
```
Comment (zygoloid) [inline toolchain/check/deduce.cpp]: If conversion fails, I think we should avoid producing a `Specific` whose arguments have the wrong types, since that would cause problems downstream. So I think we should either:
- replace `deduced_arg_id` with `converted_arg_id` even if it's an `ErrorInst`, or
- `return false` here if conversion fails.

In general, I somewhat lean towards the first option, as it should propagate the information that we encountered an error to consumers of the deduction, allowing them to suppress diagnostics. But at least in the case where conversion fails because we deduce a type and it can't be converted to its constraint, that really seems like it ought to result in a "deduction failed" outcome rather than a "your program is invalid" outcome.

I think this is closely connected to the TODO a few lines above: if we're producing an error diagnostic, then propagating the `ErrorInst` seems like the right behavior -- we did already emit a diagnostic, so we do want to suppress any follow-on diagnostics (eg, deduction failure errors). But in whichever cases we make `ConvertToValueOfType` not produce an error, we should treat deduction as having failed. So for now, let's propagate the `ErrorInst` that we get back from `ConvertToValueOfType`, and once we make it avoid producing an error in at least some conversions, we can also turn those conversion failures into deduction failures.

File: toolchain/check/eval.cpp [hunk 5]
```diff
@@ -1893,10 +1893,21 @@ static auto TryEvalInstInContext(EvalContext& eval_context,
...
     case CARBON_KIND(SemIR::AsCompatible inst): {
-      return eval_context.GetConstantValue(inst.source_id);
+      auto value = eval_context.GetConstantValue(inst.source_id);
+      if (!value.is_constant()) {
+        return value;
+      }
+      auto value_inst = eval_context.insts().Get(
+          eval_context.constant_values().GetInstId(value));
+      value_inst.SetType(inst.type_id);
+      auto phase = value.is_symbolic() ? Phase::Symbolic : Phase::Template;
```
Comment (zygoloid) [inline toolchain/check/eval.cpp]: Hm. OK, this is tricky:
- If `AsCompatible` converts from a non-symbolic type to a symbolic type, the phase of the result should be `Phase::Symbolic`.
- If `AsCompatible` converts from a symbolic type to a non-symbolic type, then we can't determine what the phase should be without walking the value of the constant.

For example:
```carbon
class C(T:! type) {
  extend adapt i32;
}
fn F(T:! type) {
  // `42 as i32` has template phase.
  // Value of `c` should have symbolic phase.
  let c: C(T) = (42 as i32) as C(T);
  // Value of `n` should have template phase.
  let n: i32 = ((42 as i32) as C(T)) as i32;
}
```

If we want to do this efficiently when possible, I think we'd say: if the phase of the new type is `>=` the phase of the old constant, then the resulting phase is the phase of the new type. Otherwise, I suppose we will need to do something like the recursive re-evaluation of the constant that you were previously doing here (or perhaps separately track the phase of the value and type portions of a constant, but that seems like a lot of work).

File: toolchain/check/testdata/builtin_conversions/no_prelude/convert_class_type_to_generic_facet_value.carbon [hunk 6]
```diff
@@ -0,0 +1,403 @@
...
+  CallGenericMethod(GenericParam, ImplsGeneric);
+}
+
+fn PassThroughToGenericMethod(T:! type, U:! Generic(T)) {
+  CallGenericMethod(T, U);
+}
+
+fn H() {
+  PassThroughToGenericMethod(GenericParam, ImplsGeneric);
+}
```
Comment (zygoloid) [inline toolchain/check/testdata/builtin_conversions/no_prelude/convert_class_type_to_generic_facet_value.carbon:34]: I think it'd be good to also test the case where `T` is deduced after `U`, so we can't do the conversion eagerly:
```carbon
fn CallGenericMethod[T:! type](U:! Generic(T), t: T) {}

fn G(t: GenericParam) {
  CallGenericMethod(GenericParam, t);
}
```

**Review by zygoloid — COMMENTED** [review]
Thanks, this generally looks really good.

File: toolchain/check/deduce.cpp (hunk 1 above)
Comment (danakj) [reply toolchain/check/deduce.cpp]: When the argument is a `TupleLiteral` of types, then `context().constant_values().Get(arg_id)` gives `NotConstant` as the constant value, and thus `context().constant_values().GetConstantInstId()` sees it is not symbolic nor template, and returns `None`. Then `result_arg_ids_[index.index]` is not set at all for the argument. And then a lot of tests fail. If we _do_ the conversion then `TupleLiteral` is converted to `TupleType` and we get a value in `result_arg_ids_[index.index]`.

Here's a concrete example from toolchain/check/testdata/deduce/tuple.carbon. You can see the error we get in the test output:
```
// --- tuple_value.carbon

library "[[@TEST_NAME]]";

class HasPair(Pair:! (i32, i32)) {}

// CHECK:STDERR: tuple_value.carbon:[[@LINE+7]]:27: error: argument for generic parameter is not a compile-time constant [CompTimeArgumentNotConstant]
// CHECK:STDERR: fn F[A:! i32, B:! i32](h: HasPair((A, B))) -> i32 { return B; }
// CHECK:STDERR:                           ^~~~~~~~~~~~~~~
// CHECK:STDERR: tuple_value.carbon:[[@LINE-5]]:15: note: initializing generic parameter `Pair` declared here [InitializingGenericParam]
// CHECK:STDERR: class HasPair(Pair:! (i32, i32)) {}
// CHECK:STDERR:               ^~~~
// CHECK:STDERR:
fn F[A:! i32, B:! i32](h: HasPair((A, B))) -> i32 { return B; }
```
When we get to deducing the `(i32, i32)` parameter of `HasPair` we have these as param and arg:
```
(gdb) call Dump(context(), param_id)
inst49: {kind: SymbolicBindingPattern, arg0: entity_name6, type: type(inst45)}
  - type type(inst45): (i32, i32); {kind: TupleType, arg0: type_block2, type: type(TypeType)}
  - value symbolic_constant22: {inst: inst50, generic: generic1, index: generic_inst_in_decl1, .Self: false}
(gdb) call Dump(context(), arg_id)
inst80: {kind: TupleLiteral, arg0: inst_block26, type: type(inst45)}
  - type type(inst45): (i32, i32); {kind: TupleType, arg0: type_block2, type: type(TypeType)}
  - value runtime
```
You can see that the argument's value is 'runtime' there. The `loc_id_` is `tuple_value.carbon:13:41` which puts us at the call to `HasPair((A, B))` in the type expression of `h:`.

> (Though if that's right, I guess we'd need to do something comparable when the parameter type is symbolic.)

Right... In the example above, the parameter has a symbolic value, but its type is not symbolic. I can try construct an example where it is and see what happens. We should in theory hit this `CompTimeArgumentNotConstant` error.

File: toolchain/check/testdata/builtin_conversions/no_prelude/convert_class_type_to_generic_facet_value.carbon (hunk 6 above)
Comment (danakj) [reply toolchain/check/testdata/builtin_conversions/no_prelude/convert_class_type_to_generic_facet_value.carbon:34]: I believe that will depend on our ability to deduce through a FacetAccessType (the `T` in `t: T`), which is done in https://github.com/carbon-language/carbon-lang/pull/4865/commits/389016f7dc72032cb1b335029d6095e894b93694 but which needs to be rebased on top of all this other work. I will add a note to add the test there.

File: toolchain/check/deduce.cpp (hunk 2 above)
Comment (danakj) [reply toolchain/check/deduce.cpp:522]: Done.

File: toolchain/check/deduce.cpp (hunk 4 above)
Comment (danakj) [reply toolchain/check/deduce.cpp]: Done, and added a test that fails this deduction.

File: toolchain/check/eval.cpp (hunk 5 above)
Comment (danakj) [reply toolchain/check/eval.cpp]: Hm ok thanks, I will copy this comment over to #4881 and work on that there.

File: toolchain/check/deduce.cpp [hunk 7]
```diff
@@ -496,8 +498,51 @@ auto DeductionContext::CheckDeductionIsComplete() -> bool {
...
+      DiagnosticAnnotationScope annotate_diagnostics(
+          &context().emitter(),
+          [&](auto& builder) { NoteInitializingParam(binding_id, builder); });
+      auto converted_arg_id = ConvertToValueOfType(
+          context(), loc_id_, deduced_arg_id, binding_type_id);
+      // Replace the deduced arg with its value converted to the parameter
+      // type.
+      CARBON_CHECK(converted_arg_id == SemIR::ErrorInst::SingletonInstId ||
+                       converted_arg_id.has_value(),
+                   "Compile-time constant value converted to runtime value?");
```
Comment (zygoloid) [inline toolchain/check/deduce.cpp]: This CHECK doesn't match the corresponding message -- the check fails only if `ConvertToValueOfType` returns `InstId::None`, which should never happen, not even if the result is a runtime value. If you want to check whether the instruction still has a constant value, you could do that with something like `context.constant_values().Get(converted_arg_id).is_constant()`.

And in fact, I think you should test that, because the conversion of the deduced argument to the parameter type can be non-constant. Eg:
```
class X(Ts:! (type, type)) {}
class Y {
  impl i32 as ImplicitAs(Y) {
    // Runtime conversion function
    fn Convert[self: Self]() -> Y { return {}; }
  }
}
fn F[Ts:! (type, type)](A:! Ts.0, x: X(Ts));
fn G(x: X(Y, Y)) {
  F(0 as i32, x);
}
```
Here, I think we will deduce `A = 0 as i32`, `Ts = (Y, Y)`, and then in this final conversion step, will substitute into the type of `A` to get `(Y, Y).0` which evaluates to `Y`, and then convert `0 as i32` to `Y`, which will call the runtime conversion function and produce a non-constant argument.

So I think we need a final test here that the argument we deduced is constant, with a diagnostic if not.

File: toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon [hunk 8]
```diff
@@ -0,0 +1,265 @@
...
+impl ImplsGeneric as Generic(GenericParam) {
+  fn F() {}
+}
+
+fn CallGenericMethod(T:! type, U:! Generic(T)) {}
+
+fn G() {
+  // CHECK:STDERR: fail_convert_class_type_to_generic_facet_value.carbon:[[@LINE+7]]:3: error: `Core.ImplicitAs` implicitly referenced here, but package `Core` not found [CoreNotFound]
+  // CHECK:STDERR:   CallGenericMethod(WrongGenericParam, ImplsGeneric);
+  // CHECK:STDERR:   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Comment (zygoloid) [inline toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon]: Is this the error you were expecting here? Maybe this shouldn't be a `no_prelude` test.

Comment (danakj) [reply toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon]: Yes and no. With the prelude you get "unable to convert, does not implement ImplicitAs...". But that requires adding the whole prelude to the test. I saw that we have other no_prelude tests that have this error in them as well in similar situations (example: https://github.com/carbon-language/carbon-lang/blob/a735a4e463ee638e299cc3061198bd9d487bebc8/toolchain/check/testdata/var/no_prelude/fail_init_type_mismatch.carbon#L12).

It does require this extra secret knowledge that this error means it tried to do a conversion we were not expecting it to attempt at all. But it makes debugging so much better. Do you have an opinion on which way to go, given all of that?

Comment (zygoloid) [reply toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon]: I'm a little uncomfortable that the exact failure path we're testing isn't one that we expect developers to actually encounter. We also might end up moving some of the builtin conversions into the prelude over time, which might mean this ends up testing less than we intend. But that's a bit hypothetical and I don't feel strongly about it.

Hm, an alternative would be to add a "mini prelude" that contains only `ImplicitAs` to this test, eg:
```
// --- core.carbon

package Core api;

interface ImplicitAs(T:! type) {
  fn Convert[self: Self]() -> T;
}

// --- your_test.carbon

import Core;
```
... should work. I'm not sure if it's worth doing that in this case.

Comment (danakj) [reply toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon]: Right, yeah, I was doing that when I was debugging as well! But removed it since I saw this error elsewhere and I was hesitant about creating work for future people if this interface might change. Sounds like this isn't worrying you so much, so I will take that approach I guess.

Comment (danakj) [reply toolchain/check/testdata/builtin_conversions/no_prelude/fail_convert_class_type_to_generic_facet_value.carbon]: I've done this, and just want to note that the error isn't spectacular in this case:
```
  // CHECK:STDERR: fail_convert_class_type_to_generic_facet_value.carbon:[[@LINE+10]]:3: error: cannot implicitly convert from `type` to `Generic(WrongGenericParam)` [ImplicitAsConversionFailure]
  // CHECK:STDERR:   CallGenericMethod(WrongGenericParam, ImplsGeneric);
  // CHECK:STDERR:   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The problem is it's trying to convert `ImplsGeneric` of type `type` to `Generic(WrongGenericParam)` but it's showing the type of `ImplsGeneric`, which probably makes sense if I was passing in a non-type value to something like this instead: `fn CallGenericMethod[T:! type, U:! Generic(T)](x: T, y: U) {}`.

I will file an issue about it.

File: toolchain/check/deduce.cpp (hunk 7 above)
Comment (danakj) [reply toolchain/check/deduce.cpp]: Nice, yes, I made a few fixes and changes to the test but we do indeed produce a runtime value. If we use that value then we will fail the
```
    CARBON_CHECK(result[i].has_value());
```
In `eval.cpp` at the end of `TryEvalBlockForSpecific()`.

A slight modification to this test however causes a different crash. If we make the `A` parameter of `F` into a runtime binding (drop the `!`) then we crash at `toolchain/check/context.cpp:1338`:
```
FATAL failure at toolchain/check/context.cpp:1338: Type refers to non-type inst {kind: TupleAccess, arg0: inst19, arg1: element0, type: type(TypeType)}
```

I will try to address this in a follow-up PR.

File: toolchain/check/deduce.cpp [hunk 9]
```diff
@@ -507,8 +510,60 @@ auto DeductionContext::CheckDeductionIsComplete() -> bool {
...
+      DiagnosticAnnotationScope annotate_diagnostics(
+          &context().emitter(),
+          [&](auto& builder) { NoteInitializingParam(binding_id, builder); });
+      auto converted_arg_id = ConvertToValueOfType(
+          context(), loc_id_, deduced_arg_id, binding_type_id);
+      // Replace the deduced arg with its value converted to the parameter
+      // type. The conversion of the argument type must produce a constant value
+      // to be used in deduction.
+      if (context().constant_values().Get(converted_arg_id).is_constant()) {
+        deduced_arg_id = converted_arg_id;
```
Comment (danakj) [inline toolchain/check/deduce.cpp:550]: One question here. We can't use the runtime value in the else case. But just leaving it as the original value - that would perhaps allow runtime conversions for a deduced generic type. Do we want to prevent that by setting the deduced arg to the Error instruction in the else case below?

Comment (zygoloid) [reply toolchain/check/deduce.cpp:550]: Yes, setting the argument to Error after issuing the error makes sense to me.

Comment (danakj) [reply toolchain/check/deduce.cpp:550]: Ok, thanks done.

File: toolchain/check/deduce.cpp (hunk 7 above)
Comment (danakj) [reply toolchain/check/deduce.cpp]: This crash is addressed in https://github.com/carbon-language/carbon-lang/pull/4910

**Comment by danakj** [comment]
bump for review @zygoloid

**Review by zygoloid — APPROVED** [review]
Thanks!
