### PR TITLE
Fix C++ function params and return values printed in SemIR

### LINKED ISSUE #5449: C++ function params and return values not printed in the SemIR anymore
### Description of the bug:

Parameters and return values were printed in the SemIR for the C++ function declarations as well, but they are not printed anymore.

E.g. in `toolchain/check/testdata/interop/cpp/function_decl.carbon`:
 
- Case 1: Function params:

```c++
// --- single_int_param_function_decl.h

auto foo(int b) -> void;
```

Before: `// CHECK:STDOUT: fn @foo[](%b.param_patt: %i32);`

Now: `// CHECK:STDOUT: fn @foo();`

- Case 2: Return values

```c++
// --- int_return_function_decl.h

auto foo_int() -> int;
```

Before: `// CHECK:STDOUT: fn @foo_int[]() -> %i32;`

Now: `// CHECK:STDOUT: fn @foo_int();`

The tests still work, the issue seems to be only in the printed SemIR. 

It is still useful to be able to see the C++ parameter/return values types, especially for the ongoing efforts of enabling these types.

### PR DESCRIPTION
**Pull request by ivanaivanovska**
Fix `pattern_block_id` and `call_params_id` for C++ function decl import, to get the correct SemIR printout for the C++ functions i.e. 

1) Fill in missing parameter info in the function decls:
```
// CHECK:STDOUT:   %foo.decl: %foo.type = fn_decl @foo [concrete = constants.%foo] {
// CHECK:STDOUT:     %a.patt: %pattern_type.2f8 = binding_pattern a [concrete]
// CHECK:STDOUT:     %a.param_patt: %pattern_type.2f8 = value_param_pattern %a.patt, call_param0 [concrete]
// CHECK:STDOUT:   } {
// CHECK:STDOUT:     %a.param: %i16 = value_param call_param0
// CHECK:STDOUT:     %.1: type = splice_block %i16 [concrete = constants.%i16] {
// CHECK:STDOUT:       %int_16: Core.IntLiteral = int_value 16 [concrete = constants.%int_16]
// CHECK:STDOUT:       %i16: type = class_type @Int, @Int(constants.%int_16) [concrete = constants.%i16]
// CHECK:STDOUT:     }
// CHECK:STDOUT:     %a: %i16 = bind_name a, %a.param
// CHECK:STDOUT:   }
```
2) Print the params and return values:

```
// CHECK:STDOUT: fn @foo_short() -> %i16;
```

```
// CHECK:STDOUT: fn @foo(%a.param: %i16);
```

Closes #5449

### CODE REVIEW

**Comment by ivanaivanovska** [comment]
CC: @geoffromer @bricknerb

File: toolchain/check/import_cpp.cpp [hunk 1]
```diff
@@ -357,40 +359,52 @@ static auto MakeParamPatternsBlockId(Context& context, SemIR::LocId loc_id,
...
-  SemIR::CallParamIndex next_index(0);
   llvm::SmallVector<SemIR::InstId> params;
   params.reserve(clang_decl.parameters().size());
   for (const clang::ParmVarDecl* param : clang_decl.parameters()) {
     clang::QualType param_type = param->getType().getCanonicalType();
-    SemIR::TypeId type_id =
-        GetPatternType(context, MapType(context, param_type).type_id);
+
+    // Marks the start a region of insts, needed for the type
+    // expression created later with the call of EndSubpatternAsExpr.
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]:
```suggestion
    // Mark the start of a region of insts, needed for the type expression
    // created later with the call of `EndSubpatternAsExpr()`.
```

File: toolchain/check/import_cpp.cpp [hunk 2]
```diff
@@ -357,40 +359,52 @@ static auto MakeParamPatternsBlockId(Context& context, SemIR::LocId loc_id,
...
+        (param_name.empty())
+            // Translate an unnamed parameter to an underscore to
+            // match Carbon's naming of unnamed/unused function params.
+            ? SemIR::NameId::Underscore
+            : SemIR::NameId::ForIdentifier(
+                  context.sem_ir().identifiers().Add(param_name));
+
+    // TODO: Fix this once templates are supported.
+    bool is_template = false;
+    // TODO: Fix this once templates are supported.
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]:
```suggestion
    // TODO: Fix this once generics are supported.
```

File: toolchain/check/import_cpp.cpp [hunk 3]
```diff
@@ -446,18 +461,27 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
   }
+  context.pattern_block_stack().Push();
   auto param_patterns_id =
       MakeParamPatternsBlockId(context, loc_id, *clang_decl);
   if (!param_patterns_id.has_value()) {
+    context.pattern_block_stack().Pop();
     return SemIR::ErrorInst::InstId;
   }
   auto return_slot_pattern_id = GetReturnType(context, loc_id, clang_decl);
+  auto pattern_block_id = context.pattern_block_stack().Pop();
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: If you can't rearrange the code so that `Pop()` is called in one place, consider using `llvm::make_scope_exit()` to make sure we call `Pop()`.

**Review by bricknerb — COMMENTED** [review]
Can we extract more logic from `HandleAnyBindingPattern()` so we can reuse it instead of doing it here, so we can more easily maintain this in case the logic changes?

File: toolchain/check/import_cpp.cpp [hunk 4]
```diff
@@ -446,18 +461,27 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
   if (SemIR::ErrorInst::InstId == return_slot_pattern_id) {
     return SemIR::ErrorInst::InstId;
   }
 
+  context.inst_block_stack().Push();
```
Comment (geoffromer) [inline toolchain/check/import_cpp.cpp]: I think you need to move this up, at least above `GetReturnType`, but preferably to the beginning of the function, because this block needs to hold all the non-pattern insts emitted as part of the function declaration. Right now the type insts for the return type are getting lost.

(Those insts don't really belong here, but we don't have a better place for them yet, so this code should be consistent with the native-Carbon code).

File: toolchain/check/import_cpp.cpp (hunk 1 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 2 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 3 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: I added a lambda function which is called at the error exit cases only, to prevent calling `Pop()` at any scope exit. PTAL.

File: toolchain/check/import_cpp.cpp (hunk 4 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Thanks @geoffromer once again for the suggestion and explanation! Now I also get the type instructions for the return types. I moved it up just after the unsupported cases. PTAL.

**Comment by ivanaivanovska** [comment]
> Can we extract more logic from `HandleAnyBindingPattern()` so we can reuse it instead of doing it here, so we can more easily maintain this in case the logic changes?

I added a TODO for now to land the changes faster and unblock waiting PRs. Will look into it as a follow-up.

File: toolchain/check/import_cpp.cpp [hunk 5]
```diff
@@ -446,18 +463,31 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
   if (SemIR::ErrorInst::InstId == return_slot_pattern_id) {
-    return SemIR::ErrorInst::InstId;
+    return pop_blocks_and_exit();
   }
+  auto pattern_block_id = context.pattern_block_stack().Pop();
+
+  auto call_params_id =
+      CalleePatternMatch(context, SemIR::InstBlockId::None, param_patterns_id,
+                         return_slot_pattern_id);
+  auto decl_block_id = context.inst_block_stack().Pop();
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Avoid using `auto` here and in other places where it's not trivially clear from the code what is the type.

File: toolchain/check/import_cpp.cpp (hunk 3 above)
Comment (bricknerb) [reply toolchain/check/import_cpp.cpp]: IIUC, you do want to call `Pop()` for both stacks on every code path.
The lambda function helps with code deduplication, but it's still easy to not call `Pop()` and corrupt the state.

I was thinking on something like (you can have multiple scopes for different stacks if you need to `Pop()` them in different places.
```
context.inst_block_stack().Push();
SemIR::InstBlockId inst_block_id;
{
  auto scope_exit = llvm::make_scope_exit([&] { inst_block_id = context.inst_block_stack().Pop(); }
  ...
}
```

File: toolchain/check/import_cpp.cpp (hunk 5 above)
Comment (danakj) [reply toolchain/check/import_cpp.cpp]: We use `auto` pretty much everywhere in this codebase FWIW, we don't follow this rule.

Comment (bricknerb) [reply toolchain/check/import_cpp.cpp]: Should we add this to `docs/project/cpp_style_guide.md`?
This seems to go against https://google.github.io/styleguide/cppguide.html#Type_deduction.
Personally, I find it takes longer to understand the code, but if this is the convention, might as well be consistent and have it in our style guide.

File: toolchain/check/import_cpp.cpp (hunk 3 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done, PTAL.

File: toolchain/check/import_cpp.cpp [hunk 6]
```diff
@@ -446,18 +464,33 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
+  auto pattern_block_id = SemIR::InstBlockId::Empty;
+  auto param_patterns_id = SemIR::InstBlockId::Empty;
+  auto return_slot_pattern_id = SemIR::InstId::None;
+  auto call_params_id = SemIR::InstBlockId::Empty;
+  {
+    auto scope_exit = llvm::make_scope_exit([&] {
+      decl_block_id = context.inst_block_stack().Pop();
+      pattern_block_id = context.pattern_block_stack().Pop();
+    });
+    param_patterns_id = MakeParamPatternsBlockId(context, loc_id, *clang_decl);
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Can you merge this with line 472?
There's a tradeoff here since on one hand we don't need `scope_exit` to call this function and on the other hand we do rely on the `Push()` to have been called.

File: toolchain/check/import_cpp.cpp [hunk 7]
```diff
@@ -465,27 +466,29 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
-  auto call_params_id =
-      CalleePatternMatch(context, SemIR::InstBlockId::None, param_patterns_id,
-                         return_slot_pattern_id);
-  auto decl_block_id = context.inst_block_stack().Pop();
 
+  auto decl_block_id = SemIR::InstBlockId::Empty;
+  auto pattern_block_id = SemIR::InstBlockId::Empty;
+  auto param_patterns_id = SemIR::InstBlockId::Empty;
+  auto return_slot_pattern_id = SemIR::InstId::None;
+  auto call_params_id = SemIR::InstBlockId::Empty;
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: All these don't rely on the `Push()` above so it might make it simpler to move them above the `Push()` call so that the `Push()` call is closer to where we define the lambda that calls `Pop()`.

File: toolchain/check/import_cpp.cpp [hunk 8]
```diff
@@ -446,18 +464,33 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
+  {
+    auto scope_exit = llvm::make_scope_exit([&] {
+      decl_block_id = context.inst_block_stack().Pop();
+      pattern_block_id = context.pattern_block_stack().Pop();
+    });
+    param_patterns_id = MakeParamPatternsBlockId(context, loc_id, *clang_decl);
+    if (!param_patterns_id.has_value()) {
+      return SemIR::ErrorInst::InstId;
+    }
+    return_slot_pattern_id = GetReturnType(context, loc_id, clang_decl);
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Do we need to do this after `MakeParamPatternsBlockId()` is called?
Do we need to do this before `CalleePatternMatch()` is called?
Do we need to do this only if  `MakeParamPatternsBlockId()` succeeded?

If not, can we merge this with line 473?
See the tradeoff above.

File: toolchain/check/import_cpp.cpp [hunk 9]
```diff
@@ -446,18 +464,33 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
-    return SemIR::ErrorInst::InstId;
+  context.inst_block_stack().Push();
+  context.pattern_block_stack().Push();
+
+  auto decl_block_id = SemIR::InstBlockId::Empty;
+  auto pattern_block_id = SemIR::InstBlockId::Empty;
+  auto param_patterns_id = SemIR::InstBlockId::Empty;
+  auto return_slot_pattern_id = SemIR::InstId::None;
+  auto call_params_id = SemIR::InstBlockId::Empty;
+  {
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Have you considered putting this entire scope in a function (we already declare all the return values above)?
If we do that, we might just need to return success/failure in addition to populating the fields, and then we can just call `Pop()` after the function call once instead of the scope exit.
WDYT?

Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Yes, I think this looks best, thanks for the suggestion. PTAL.

File: toolchain/check/import_cpp.cpp [hunk 10]
```diff
@@ -351,53 +353,67 @@ static auto MapType(Context& context, clang::QualType type) -> TypeExpr {
...
-             (param_name.empty())
-                 // Translate an unnamed parameter to an underscore to
-                 // match Carbon's naming of unnamed/unused function params.
-                 ? SemIR::NameId::Underscore
-                 : SemIR::NameId::ForIdentifier(
-                       context.sem_ir().identifiers().Add(param_name)),
-         .parent_scope_id = SemIR::NameScopeId::None});
-    SemIR::InstId binding_pattern_id = AddInstInNoBlock(
+    SemIR::NameId name_id =
+        (param_name.empty())
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Remove extra parenthesis.
```suggestion
        param_name.empty()
```

File: toolchain/check/import_cpp.cpp [hunk 11]
```diff
@@ -427,6 +444,28 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
   return param_pattern_id;
 }
 
+// Returns parameter patterns block id, the return slot pattern id, and the
+// call parameters block id for the given function declaration.
+// Returns false if the function declaration has an unsupported parameter type.
+static auto GetFunctionParams(Context& context, SemIR::LocId loc_id,
+                              clang::FunctionDecl* clang_decl,
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: I believe this can be const.
```suggestion
                              const clang::FunctionDecl* clang_decl,
```

File: toolchain/check/import_cpp.cpp [hunk 12]
```diff
@@ -427,6 +444,28 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
...
+                              SemIR::InstBlockId& param_patterns_id,
+                              SemIR::InstId& return_slot_pattern_id,
+                              SemIR::InstBlockId& call_params_id) -> bool {
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: Consider returning all of these instead of using output parameters.
You can have a dedicated struct for that.
You can make it optional to clarify success or add a bool to the struct if you want to be able to use some of the values even on failure.

From [the style guide](https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs):
> Prefer using return values over output parameters

File: toolchain/check/import_cpp.cpp [hunk 13]
```diff
@@ -446,18 +485,25 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
-  auto return_slot_pattern_id = GetReturnType(context, loc_id, clang_decl);
-  if (SemIR::ErrorInst::InstId == return_slot_pattern_id) {
+
+  context.inst_block_stack().Push();
+  context.pattern_block_stack().Push();
+
+  auto param_patterns_id = SemIR::InstBlockId::Empty;
+  auto return_slot_pattern_id = SemIR::InstId::None;
+  auto call_params_id = SemIR::InstBlockId::Empty;
+  auto success =
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]:
```suggestion
  bool success =
```

File: toolchain/check/import_cpp.cpp [hunk 14]
```diff
@@ -446,18 +485,25 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
+      GetFunctionParams(context, loc_id, clang_decl, param_patterns_id,
+                        return_slot_pattern_id, call_params_id);
+
+  auto decl_block_id = context.inst_block_stack().Pop();
+  auto pattern_block_id = context.pattern_block_stack().Pop();
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: nit: I think popping `pattern_block_stack` before `inst_block_stack` to reverse the order you pushed it makes sense, though it definitely doesn't really matter as long as you don't have any code in between.

File: toolchain/check/import_cpp.cpp [hunk 15]
```diff
@@ -427,6 +444,28 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
   return param_pattern_id;
 }
 
+// Returns parameter patterns block id, the return slot pattern id, and the
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]:
```suggestion
// Returns parameter patterns block id, the return slot pattern id and the
```

File: toolchain/check/import_cpp.cpp (hunk 5 above)
Comment (bricknerb) [reply toolchain/check/import_cpp.cpp]: FTR, this is discusses in https://discord.com/channels/655572317891461132/821113559755784242/1379886216010403973.

**Review by bricknerb — APPROVED** [review]

File: toolchain/check/import_cpp.cpp [hunk 16]
```diff
@@ -464,30 +485,22 @@ static auto ImportFunctionDecl(Context& context, SemIR::LocId loc_id,
...
   context.inst_block_stack().Push();
   context.pattern_block_stack().Push();
 
-  auto decl_block_id = SemIR::InstBlockId::Empty;
-  auto pattern_block_id = SemIR::InstBlockId::Empty;
   auto param_patterns_id = SemIR::InstBlockId::Empty;
   auto return_slot_pattern_id = SemIR::InstId::None;
   auto call_params_id = SemIR::InstBlockId::Empty;
-  {
-    auto scope_exit = llvm::make_scope_exit([&] {
```
Comment (danakj) [inline toolchain/check/import_cpp.cpp]: I was going to say every time I found myself reaching for this, Jon has nudged me into factoring the code out into another function and then it wasn't needed anymore - I see you've done similar here, so that's nice :)

File: toolchain/check/import_cpp.cpp (hunk 12 above)
Comment (danakj) [reply toolchain/check/import_cpp.cpp]: +1 for this, I would suggest making a little struct type to return here. It can live just above the function in an anonymous namespace.

File: toolchain/check/import_cpp.cpp (hunk 10 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 11 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 12 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 14 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 15 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 13 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: no bool return anymore.

**Comment by ivanaivanovska** [comment]
@bricknerb I applied the latest review suggestions now. It there are no further remarks, please help merge the PR (I still have no access). Thanks.

File: toolchain/check/import_cpp.cpp [hunk 17]
```diff
@@ -427,6 +444,38 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
...
+  SemIR::InstId return_slot_pattern_id;
+  SemIR::InstBlockId call_params_id;
+};
+}  // namespace
+
+// Returns the function parameters for the given function declaration. Returns
+// `std::nullopt` if the function declaration has an unsupported parameter
+// type.
+static auto GetFunctionParams(Context& context, SemIR::LocId loc_id,
+                              const clang::FunctionDecl* clang_decl)
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: I believe this function has some side effects, so it might be better to make that clear in its name and comments.

**Review by bricknerb — APPROVED** [review]

File: toolchain/check/import_cpp.cpp (hunk 17 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: I tried to improve the naming and the description. Please provide concrete suggestions if further modifications are needed.

File: toolchain/check/import_cpp.cpp [hunk 18]
```diff
@@ -427,6 +444,45 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
...
+  if (!param_patterns_id.has_value()) {
+    return std::nullopt;
+  }
+  auto return_slot_pattern_id = GetReturnType(context, loc_id, clang_decl);
+  if (SemIR::ErrorInst::InstId == return_slot_pattern_id) {
+    return std::nullopt;
+  }
+  // TODO: Add support for implicit parameters.
+  auto call_params_id =
+      CalleePatternMatch(context, SemIR::InstBlockId::None, param_patterns_id,
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]:
```suggestion
      CalleePatternMatch(context, /*implicit_param_patterns_id=*/SemIR::InstBlockId::None, param_patterns_id,
```

File: toolchain/check/import_cpp.cpp [hunk 19]
```diff
@@ -427,6 +444,45 @@ static auto GetReturnType(Context& context, SemIR::LocId loc_id,
...
+                         return_slot_pattern_id);
+  return FunctionParamsInsts{param_patterns_id, return_slot_pattern_id,
+                             call_params_id};
```
Comment (bricknerb) [inline toolchain/check/import_cpp.cpp]: How about creating the returned struct in the beginning and populating its fields instead of defining local variables for each field and aggregating them here?

**Review by bricknerb — APPROVED** [review]

File: toolchain/check/import_cpp.cpp (hunk 19 above)
Comment (danakj) [reply toolchain/check/import_cpp.cpp]: I have seen others recommend the opposite, and I think I would too - it makes it harder to forget to set some field if you construct it this way.

Comment (danakj) [inline toolchain/check/import_cpp.cpp]: Our style guide prefers two things here:
1. Avoid writing the type name if it's not necessary (it's inferred from the return type here)
2. use designated initializers

```suggestion
  return {{.param_patterns_id = param_patterns_id,
      .return_slot_pattern_id = return_slot_pattern_id,
      .call_params_id = call_params_id}};
```

**Comment by bricknerb** [comment]
> @bricknerb I applied the latest review suggestions now. It there are no further remarks, please help merge the PR (I still have no access). Thanks.

FTR, I think we should wait for another approver first. Probably @geoffromer.

File: toolchain/check/import_cpp.cpp (hunk 18 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done.

File: toolchain/check/import_cpp.cpp (hunk 19 above)
Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: Done, thanks.

Comment (ivanaivanovska) [reply toolchain/check/import_cpp.cpp]: I find it cleaner this way as well, so leaving them as they are.

**Review by geoffromer — APPROVED** [review]
