### PR TITLE
Narrow the CRC scope in file_test

### LINKED ISSUE #5042: `CARBON_CHECK()` causes test timeout in a language server test
### Description of the bug:

When adding a simple `CARBON_CHECK(ptr != nullptr);` the following test run timeouts:

```
bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/language_server/testdata/document_symbol/nested.carbon
```

Output of the test (after it timed out):

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //toolchain/testing:file_test
-----------------------------------------------------------------------------
Running tests with 128 thread(s)
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.	bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/language_server/testdata/document_symbol/nested.carbon
1.	Program arguments: --include-diagnostic-kind language-server
2.	Check::Context
          NodeStack:
          inst_block_stack_:
            0.	inst_block<none>	{inst12}
          pattern_block_stack_:
          param_and_arg_refs_stack:
          args_type_info_stack_:
 #0 0x000055aa41c4328b backtrace (/usr/local/google/home/brickner/.cache/bazel/_bazel_brickner/ea6b91bc246d550975e63f83247d1a54/sandbox/linux-sandbox/141/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0x10cba28b)
 #1 0x000055aa4ea5a4a6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:803:8
 #2 0x000055aa4ea5b04b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:875:1
 #3 0x000055aa4ea54b7d llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x000055aa4ea58cbc llvm::sys::CleanupOnSignal(unsigned long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:370:1
 #5 0x000055aa4e98c47e (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:73:5
 #6 0x000055aa4e98cad1 CrashRecoverySignalHandler(int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:0:51
 #7 0x00007ff3a3ab6590 (/lib/x86_64-linux-gnu/libc.so.6+0x3f590)
 #8 0x00007ff3a3b053ac __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #9 0x00007ff3a3ab64f2 raise ./signal/../sysdeps/posix/raise.c:27:6
#10 0x00007ff3a3a9f4ed abort ./stdlib/abort.c:81:7
#11 0x000055aa4e3000ed Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:42:3
#12 0x000055aa4443693d void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{char [6]{(char)67, (char)72, (char)69, (char)67, (char)75}}, Carbon::TemplateString<30>{char [31]{(char)116, (char)111, (char)111, (char)108, (char)99, (char)104, (char)97, (char)105, (char)110, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)95, (char)117, (char)110, (char)105, (char)116, (char)46, (char)99, (char)112, (char)112}}, 144, Carbon::TemplateString<21>{char [22]{(char)109, (char)121, (char)95, (char)112, (char)111, (char)105, (char)110, (char)116, (char)101, (char)114, (char)32, (char)33, (char)61, (char)32, (char)110, (char)117, (char)108, (char)108, (char)112, (char)116, (char)114}}, Carbon::TemplateString<0>{}>() /proc/self/cwd/./common/check_internal.h:102:1
#13 0x000055aa44432dd2 Carbon::Check::CheckUnit::InitPackageScopeAndImports() /proc/self/cwd/toolchain/check/check_unit.cpp:0:3
#14 0x000055aa44432145 Carbon::Check::CheckUnit::Run() /proc/self/cwd/toolchain/check/check_unit.cpp:0:0
#15 0x000055aa444161dc Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::raw_ostream*, bool) /proc/self/cwd/toolchain/check/check.cpp:0:70
#16 0x000055aa4440636a release /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:232:9
#17 0x000055aa4440636a ~IntrusiveRefCntPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:196:27
#18 0x000055aa4440636a Carbon::LanguageServer::Context::File::SetText(Carbon::LanguageServer::Context&, std::__1::optional<long>, llvm::StringRef) /proc/self/cwd/toolchain/language_server/context.cpp:150:3
#19 0x000055aa443fd327 Carbon::LanguageServer::HandleDidOpenTextDocument(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&) /proc/self/cwd/toolchain/language_server/handle_text_document.cpp:22:7
#20 0x000055aa443f1a27 void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value)::operator()(Carbon::LanguageServer::Context&, llvm::json::Value) const /proc/self/cwd/toolchain/language_server/incoming_messages.cpp:0:5
#21 0x000055aa443f1755 ~Value /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/JSON.h:382:14
#22 0x000055aa443f1755 __invoke<(lambda at toolchain/language_server/incoming_messages.cpp:56:7) &, Carbon::LanguageServer::Context &, llvm::json::Value> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:394:7
#23 0x000055aa443f1755 __call<(lambda at toolchain/language_server/incoming_messages.cpp:56:7) &, Carbon::LanguageServer::Context &, llvm::json::Value> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:487:9
#24 0x000055aa443f1755 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:185:16
#25 0x000055aa443f1755 std::__1::__function::__func<void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value), std::__1::allocator<void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value)>, void (Carbon::LanguageServer::Context&, llvm::json::Value)>::operator()(Carbon::LanguageServer::Context&, llvm::json::Value&&) /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:12
#26 0x000055aa443dfcec ~Value /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/JSON.h:382:14
#27 0x000055aa443dfcec Carbon::LanguageServer::IncomingMessages::onNotify(llvm::StringRef, llvm::json::Value) /proc/self/cwd/toolchain/language_server/incoming_messages.cpp:105:5
#28 0x000055aa444d474c handleMessage /proc/self/cwd/external/+llvm_project+llvm-project/clang-tools-extra/clangd/JSONTransport.cpp:195:0
#29 0x000055aa444d474c clang::clangd::(anonymous namespace)::JSONTransport::loop(clang::clangd::Transport::MessageHandler&) /proc/self/cwd/external/+llvm_project+llvm-project/clang-tools-extra/clangd/JSONTransport.cpp:119:16
#30 0x000055aa443dadfc getPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/Error.h:282:12
#31 0x000055aa443dadfc operator bool /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/Error.h:242:16
#32 0x000055aa443dadfc Carbon::LanguageServer::Run(_IO_FILE*, llvm::raw_ostream&, llvm::raw_ostream&, llvm::raw_ostream*, Carbon::DiagnosticConsumer&) /proc/self/cwd/toolchain/language_server/language_server.cpp:64:7
#33 0x000055aa41fe6e92 Carbon::LanguageServerSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/language_server_subcommand.cpp:30:18
#34 0x000055aa41f9065d index /usr/lib/llvm-16/bin/../include/c++/v1/variant:818:12
#35 0x000055aa41f9065d valueless_by_exception /usr/lib/llvm-16/bin/../include/c++/v1/variant:813:12
#36 0x000055aa41f9065d __destroy /usr/lib/llvm-16/bin/../include/c++/v1/variant:875:1
#37 0x000055aa41f9065d ~__dtor /usr/lib/llvm-16/bin/../include/c++/v1/variant:875:1
#38 0x000055aa41f9065d ~variant /usr/lib/llvm-16/bin/../include/c++/v1/variant:1396:22
#39 0x000055aa41f9065d ~ErrorOr /proc/self/cwd/./common/error.h:79:21
#40 0x000055aa41f9065d Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:137:1
#41 0x000055aa41cd928c Carbon::Testing::(anonymous namespace)::ToolchainFileTest::Run(llvm::SmallVector<llvm::StringRef, 3u> const&, llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem>&, _IO_FILE*, llvm::raw_pwrite_stream&, llvm::raw_pwrite_stream&) /proc/self/cwd/toolchain/testing/file_test.cpp:0:31
#42 0x000055aa41d2f9b6 Carbon::Testing::ProcessTestFileAndRun(Carbon::Testing::FileTestBase*, std::__1::mutex*, bool, bool) /proc/self/cwd/testing/file_test/run_test.cpp:0:50
#43 0x000055aa41d288b2 operator() /proc/self/cwd/testing/file_test/file_test_base.cpp:0:28
#44 0x000055aa41d288b2 void llvm::function_ref<void ()>::callback_fn<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0::operator()() const::'lambda'()>(long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#45 0x000055aa4e98c2c9 operator() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#46 0x000055aa4e98c2c9 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:426:3
#47 0x000055aa41d2802b operator() /proc/self/cwd/testing/file_test/file_test_base.cpp:374:29
#48 0x000055aa41d2802b __invoke<(lambda at testing/file_test/file_test_base.cpp:360:16) &> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:394:23
#49 0x000055aa41d2802b __call<(lambda at testing/file_test/file_test_base.cpp:360:16) &> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:487:9
#50 0x000055aa41d2802b operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:185:16
#51 0x000055aa41d2802b std::__1::__function::__func<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0, std::__1::allocator<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0>, void ()>::operator()() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:12
#52 0x000055aa41d27a28 std::__1::__deferred_assoc_state<void, std::__1::__async_func<std::__1::function<void ()>>>::__execute() /usr/lib/llvm-16/bin/../include/c++/v1/future:918:15
#53 0x000055aa41d27d27 std::__1::__function::__func<std::__1::shared_future<void> llvm::ThreadPoolInterface::asyncImpl<void>(std::__1::function<void ()>, llvm::ThreadPoolTaskGroup*)::'lambda'(), std::__1::allocator<std::__1::shared_future<void> llvm::ThreadPoolInterface::asyncImpl<void>(std::__1::function<void ()>, llvm::ThreadPoolTaskGroup*)::'lambda'()>, void ()>::operator()() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:5
#54 0x000055aa4ea935e8 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:0:16
#55 0x000055aa4ea935e8 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:1156:12
#56 0x000055aa4ea935e8 llvm::StdThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:100:5
#57 0x000055aa4ea96360 GenericThreadProxy<std::__1::tuple<(lambda at external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:45:26)> > /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:0:7
#58 0x000055aa4ea96360 void* llvm::thread::ThreadProxy<std::__1::tuple<llvm::StdThreadPool::grow(int)::$_0>>(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/thread.h:55:5
#59 0x00007ff3a3b036c2 start_thread ./nptl/pthread_create.c:447:8
#60 0x00007ff3a3b7e128 clone3 ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:80:0
CHECK failure at toolchain/check/check_unit.cpp:144: my_pointer != nullptr
-- Test timed out at 2025-02-28 13:57:48 UTC --
```

### What did you do, or what's a simple way to reproduce the bug?

_No response_

### What did you expect to happen?

_No response_

### What actually happened?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by jonmeow**
This narrows the scope of the CRC to try to get better behavior around mutex lock releasing on crash. Closes #5042.

This breaks apart `ProcessTestFileAndRun` because we need to process the test file for `SET-CAPTURE-CONSOLE-OUTPUT`. The test file processing should more reliably not crash than the core `Run` logic though, so should be reasonably safe to put outside the CRC.

Also support --threads=1 for disabling threading. This is the flipside for me of reducing how much is in the CRC: make it easier to run on a single thread if the CRC gets in the way of debugging. This also means a typical copy-paste execution of a single test will be single-threaded.

### CODE REVIEW

File: testing/file_test/file_test_base.cpp [hunk 1]
```diff
@@ -329,88 +329,146 @@ class FileTestEventListener : public testing::EmptyTestEventListener {
...
+  // Load expected output.
+  test.test_result = ProcessTestFile(test_instance->test_name(),
+                                     absl::GetFlag(FLAGS_autoupdate));
+  if (test.test_result->ok()) {
+    // Execution must be serialized for either serial tests or console
+    // output.
+    std::unique_lock<std::mutex> output_lock;
+
+    if (((*test.test_result)->capture_console_output ||
+         !test_instance->AllowParallelRun())) {
```
Comment (geoffromer) [inline testing/file_test/file_test_base.cpp]: I could be missing something, but it seems like this has a redundant layer of parentheses.

```suggestion
    if ((*test.test_result)->capture_console_output ||
         !test_instance->AllowParallelRun()) {
```

File: testing/file_test/file_test_base.cpp [hunk 2]
```diff
@@ -329,88 +329,146 @@ class FileTestEventListener : public testing::EmptyTestEventListener {
...
+      output_lock = std::unique_lock<std::mutex>(output_mutex);
+    }
 
+    auto run_test_file = [&] {
```
Comment (geoffromer) [inline testing/file_test/file_test_base.cpp]: Have you considered moving this above `output_lock`? That would substantially reduce the textual size of the critical section, making it easier to see the overall structure (for example, it was hard for me to tell if the critical section ended before the next one on line 407 started).

File: testing/file_test/file_test_base.cpp [hunk 3]
```diff
@@ -329,88 +329,146 @@ class FileTestEventListener : public testing::EmptyTestEventListener {
...
+  // Guard access to both `llvm::errs` and `crashed`.
+  bool crashed = false;
+  std::mutex output_mutex;
+
+  for (auto& test : tests_) {
+    if (!test.registered_test->should_run()) {
+      continue;
+    }
+
+    pool->async([&single_threaded, &output_mutex, &crashed, &test] {
```
Comment (geoffromer) [inline testing/file_test/file_test_base.cpp]:
```suggestion
    pool->async([single_threaded, &output_mutex, &crashed, &test] {
```

I don't think this `&` is necessary, and it makes me worry that `single_threaded` might get mutated.

FWIW I think it would be fine to use `[&]` here instead (it's clear that the lambda's scope is limited enough to make that safe); what threw me off was the fact that the code seems to go out of its way to specify a reference capture for this specific variable.

**Review by danakj — APPROVED** [review]
LGTM

File: testing/file_test/file_test_base.cpp [hunk 4]
```diff
@@ -329,88 +329,146 @@ class FileTestEventListener : public testing::EmptyTestEventListener {
...
-                       << (test_file.run_result.success ? "true" : "false")
-                       << "\n--- Autoupdate differs: "
-                       << (test.autoupdate_differs ? "true" : "false") << "\n";
-        } else {
-          llvm::errs() << (test.autoupdate_differs ? "!" : ".");
-        }
-      });
-      if (thread_crashed) {
+  // Guard access to both `llvm::errs` and `crashed`.
+  bool crashed = false;
```
Comment (geoffromer) [inline testing/file_test/file_test_base.cpp]: Did you consider using `std::atomic<bool>` here instead? I usually advise against using atomics because they can be very subtle, but in this case the usage is local and simple enough that I think an atomic might actually be safer, because we wouldn't have to worry about forgetting to lock the mutex.

I don't feel strongly about this, though; it's up to you.

File: testing/file_test/file_test_base.cpp [hunk 5]
```diff
@@ -329,88 +329,146 @@ class FileTestEventListener : public testing::EmptyTestEventListener {
...
-          llvm::errs() << "\n--- Exit with success: "
-                       << (test_file.run_result.success ? "true" : "false")
-                       << "\n--- Autoupdate differs: "
-                       << (test.autoupdate_differs ? "true" : "false") << "\n";
-        } else {
-          llvm::errs() << (test.autoupdate_differs ? "!" : ".");
-        }
-      });
-      if (thread_crashed) {
+  // Guard access to both `llvm::errs` and `crashed`.
```
Comment (danakj) [inline testing/file_test/file_test_base.cpp]: I was wondering while reading if GUARDED_BY and REQUIRES would be useful here. I've not actually written code with them before though.

https://clang.llvm.org/docs/ThreadSafetyAnalysis.html

File: testing/file_test/file_test_base.cpp (hunk 2 above)
Comment (jonmeow) [reply testing/file_test/file_test_base.cpp]: Refactored to a helper function.

File: testing/file_test/file_test_base.cpp (hunk 4 above)
Comment (jonmeow) [reply testing/file_test/file_test_base.cpp]: Done.

File: testing/file_test/file_test_base.cpp (hunk 3 above)
Comment (jonmeow) [reply testing/file_test/file_test_base.cpp]: Switched to `[&]`

File: testing/file_test/file_test_base.cpp (hunk 5 above)
Comment (jonmeow) [reply testing/file_test/file_test_base.cpp]: We don't own the things we're trying to lock, many different systems touch output, so it's an awkward fit for what we're trying to lock here. We'd basically need to add helpers around things like `llvm::errs()`, and even then we should expect incomplete coverage because there are uses that are too indirect to capture.

That said, we also don't enable `-fsanitize=thread` so I think annotations would probably be brittle. If you think this would be worthwhile to change, it seems out of the scope of this PR, so perhaps discuss it on #infra?

**Review by geoffromer — APPROVED** [review]
