### PR TITLE
Set class static type before base class lookup

### LINKED ISSUE #2929: Assertion failure in `optional::operator*`
### Description of the bug:

A simple test program crashes the Explorer because it invokes `operator*` on `nullopt`.

### What did you do, or what's a simple way to reproduce the bug?

The following test program reproduces the problem

```
package EmptyIdentifier impl;

class EmptyIdentifier{
  extend base: EmptyIdentifier;

}
fn Main() -> i32 { return 0; }
```

### What did you expect to happen?

I expected either a successful run of the program or (more likely) a diagnostic explaining a problem with the program.

### What actually happened?

A crash with the error message "/usr/lib/llvm-14/bin/../include/c++/v1/optional:943: _LIBCPP_ASSERT 'this->has_value()' failed. optional operator* called on a disengaged value" followed by a stack trace.

### Any other information, logs, or outputs that you want to share?

The stack trace is as follows:

```
/usr/lib/llvm-14/bin/../include/c++/v1/optional:943: _LIBCPP_ASSERT 'this->has_value()' failed. optional operator* called on a disengaged value
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
 #0 0x000056222bc795fd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/llvm-project/llvm/lib/Support/Unix/Signals.inc:602:11
 #1 0x000056222bc79bab PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/llvm-project/llvm/lib/Support/Unix/Signals.inc:675:1
 #2 0x000056222bc76ea6 llvm::sys::RunSignalHandlers() /proc/self/cwd/external/llvm-project/llvm/lib/Support/Signals.cpp:104:5
 #3 0x000056222bc7a9a5 SignalHandler(int) /proc/self/cwd/external/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f0ac5695f90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #5 0x00007f0ac56e4ccc __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #6 0x00007f0ac5695ef2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00007f0ac5680472 abort ./stdlib/./stdlib/abort.c:81:7
 #8 0x000056222bd6a37f (/usr/local/google/home/gromer/.cache/bazel/_bazel_gromer/6b556be8ddbdbba287a2e1ef86f733d5/execroot/carbon/bazel-out/k8-dbg/bin/explorer/explorer+0x73737f)
 #9 0x000056222b940d6b std::__1::optional<Carbon::Value const*>::operator*() const & /usr/lib/llvm-14/bin/../include/c++/v1/optional:943:9
#10 0x000056222b940ce9 Carbon::Declaration::static_type() const /proc/self/cwd/./explorer/ast/declaration.h:65:54
#11 0x000056222b95ce61 Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)::operator()(Carbon::AstNode const&) const /proc/self/cwd/./explorer/ast/value_node.h:82:11
#12 0x000056222b95ce1d decltype(static_cast<Carbon::ClassDeclaration>(fp)(static_cast<Carbon::AstNode const&>(fp0))) std::__1::__invoke<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)&, Carbon::AstNode const&>(Carbon::ClassDeclaration&&, Carbon::AstNode const&) /usr/lib/llvm-14/bin/../include/c++/v1/type_traits:3640:7
#13 0x000056222b95cdd2 Carbon::Value const& std::__1::__invoke_void_return_wrapper<Carbon::Value const&, false>::__call<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)&, Carbon::AstNode const&>(Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)&, Carbon::AstNode const&) /usr/lib/llvm-14/bin/../include/c++/v1/__functional/invoke.h:30:9
#14 0x000056222b95cd92 std::__1::__function::__alloc_func<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&), std::__1::allocator<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)>, Carbon::Value const& (Carbon::AstNode const&)>::operator()(Carbon::AstNode const&) /usr/lib/llvm-14/bin/../include/c++/v1/__functional/function.h:180:9
#15 0x000056222b95bee1 std::__1::__function::__func<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&), std::__1::allocator<Carbon::ValueNodeView::ValueNodeView<Carbon::ClassDeclaration, void>(Carbon::ClassDeclaration const*)::'lambda1'(Carbon::AstNode const&)>, Carbon::Value const& (Carbon::AstNode const&)>::operator()(Carbon::AstNode const&) /usr/lib/llvm-14/bin/../include/c++/v1/__functional/function.h:354:5
#16 0x000056222ba5efaa std::__1::__function::__value_func<Carbon::Value const& (Carbon::AstNode const&)>::operator()(Carbon::AstNode const&) const /usr/lib/llvm-14/bin/../include/c++/v1/__functional/function.h:507:9
#17 0x000056222ba5ef4d std::__1::function<Carbon::Value const& (Carbon::AstNode const&)>::operator()(Carbon::AstNode const&) const /usr/lib/llvm-14/bin/../include/c++/v1/__functional/function.h:1184:5
#18 0x000056222b9ea002 Carbon::ValueNodeView::static_type() const /proc/self/cwd/./explorer/ast/value_node.h:118:46
#19 0x000056222b9db1dd Carbon::TypeChecker::TypeCheckExpImpl(Carbon::Expression*, Carbon::ImplScope const&) /proc/self/cwd/explorer/interpreter/type_checker.cpp:3520:49
#20 0x000056222ba8a021 Carbon::TypeChecker::TypeCheckExp(Carbon::Expression*, Carbon::ImplScope const&)::$_9::operator()() const /proc/self/cwd/explorer/interpreter/type_checker.cpp:2936:43
#21 0x000056222b9d2e30 decltype(fp()) Carbon::RunWithExtraStack<Carbon::TypeChecker::TypeCheckExp(Carbon::Expression*, Carbon::ImplScope const&)::$_9>(Carbon::TypeChecker::TypeCheckExp(Carbon::Expression*, Carbon::ImplScope const&)::$_9) /proc/self/cwd/./explorer/interpreter/stack_space.h:0:12
#22 0x000056222b9bd29c Carbon::TypeChecker::TypeCheckExp(Carbon::Expression*, Carbon::ImplScope const&) /proc/self/cwd/explorer/interpreter/type_checker.cpp:2936:10
#23 0x000056222b9e59e7 Carbon::TypeChecker::TypeCheckTypeExp(Carbon::Expression*, Carbon::ImplScope const&, bool) /proc/self/cwd/explorer/interpreter/type_checker.cpp:4314:3
#24 0x000056222b9ffecd Carbon::TypeChecker::DeclareClassDeclaration(Carbon::ClassDeclaration*, Carbon::TypeChecker::ScopeInfo const&) /proc/self/cwd/explorer/interpreter/type_checker.cpp:5215:9
#25 0x000056222ba033f1 Carbon::TypeChecker::DeclareDeclaration(Carbon::Declaration*, Carbon::TypeChecker::ScopeInfo const&) /proc/self/cwd/explorer/interpreter/type_checker.cpp:6405:7
#26 0x000056222ba1341c Carbon::TypeChecker::TypeCheck(Carbon::AST&) /proc/self/cwd/explorer/interpreter/type_checker.cpp:6258:5
#27 0x000056222b91eba4 Carbon::AnalyzeProgram(Carbon::Arena*, Carbon::AST, Carbon::TraceStream*, llvm::raw_ostream*) /proc/self/cwd/explorer/interpreter/exec_program.cpp:59:3
#28 0x000056222b914b6c Carbon::ParseAndExecuteHelper(std::__1::function<Carbon::ErrorOr<Carbon::AST> (Carbon::Arena*)>, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::TraceStream*, llvm::raw_ostream*)::$_3::operator()() const /proc/self/cwd/explorer/parse_and_execute/parse_and_execute.cpp:62:9
#29 0x000056222b9151b5 decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecuteHelper(std::__1::function<Carbon::ErrorOr<Carbon::AST> (Carbon::Arena*)>, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::TraceStream*, llvm::raw_ostream*)::$_3>(Carbon::ParseAndExecuteHelper(std::__1::function<Carbon::ErrorOr<Carbon::AST> (Carbon::Arena*)>, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::TraceStream*, llvm::raw_ostream*)::$_3)::'lambda'()::operator()() const /proc/self/cwd/./explorer/interpreter/stack_space.h:39:54
#30 0x000056222b915185 void llvm::function_ref<void ()>::callback_fn<decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecuteHelper(std::__1::function<Carbon::ErrorOr<Carbon::AST> (Carbon::Arena*)>, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::TraceStream*, llvm::raw_ostream*)::$_3>(Carbon::ParseAndExecuteHelper(std::__1::function<Carbon::ErrorOr<Carbon::AST> (Carbon::Arena*)>, std::__1::basic_string_view<char, std::__1::char_traits<char> >, Carbon::TraceStream*, llvm::raw_ostream*)::$_3)::'lambda'()>(long) /proc/self/cwd/external/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:5
#31 0x000056222bb1beb9 llvm::function_ref<void ()>::operator()() const /proc/self/cwd/external/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:5
#32 0x000056222bb1be93 Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0::operator()() const /proc/self/cwd/explorer/interpreter/stack_space.cpp:45:7
#33 0x000056222bb1be45 void llvm::function_ref<void ()>::callback_fn<Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0>(long) /proc/self/cwd/external/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:5
#34 0x000056222bb1beb9 llvm::function_ref<void ()>::operator()() const /proc/self/cwd/external/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:5
#35 0x000056222bc391ba llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /proc/self/cwd/external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:427:3
#36 0x000056222bc3963f RunSafelyOnThread_Dispatch(void*) /proc/self/cwd/external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:510:29
#37 0x000056222bc39ee9 auto void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...)::operator()<void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) const /proc/self/cwd/external/llvm-project/llvm/include/llvm/Support/thread.h:44:9
#38 0x000056222bc39e65 decltype(static_cast<auto>(fp)(static_cast<auto>(fp0)...)) std::__1::__invoke_constexpr<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) /usr/lib/llvm-14/bin/../include/c++/v1/type_traits:3648:7
#39 0x000056222bc39e13 decltype(auto) std::__1::__apply_tuple_impl<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, 0ul, 1ul>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, std::__1::__tuple_indices<0ul, 1ul>) /usr/lib/llvm-14/bin/../include/c++/v1/tuple:1595:1
#40 0x000056222bc39d92 decltype(auto) std::__1::apply<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&) /usr/lib/llvm-14/bin/../include/c++/v1/tuple:1604:1
#41 0x000056222bc39d2c void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*) /proc/self/cwd/external/llvm-project/llvm/include/llvm/Support/thread.h:41:5
#42 0x000056222bc39ac5 void* llvm::thread::ThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*> >(void*) /proc/self/cwd/external/llvm-project/llvm/include/llvm/Support/thread.h:56:5
#43 0x00007f0ac56e2fd4 start_thread ./nptl/./nptl/pthread_create.c:442:8
#44 0x00007f0ac576366c clone3 ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:83:0
Aborted
```

### PR DESCRIPTION
**Pull request by geoffromer**
This avoids a crash when a class inherits from itself.

Closes #2929

### CODE REVIEW

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -5186,9 +5186,24 @@ auto TypeChecker::DeclareClassDeclaration(Nonnull<ClassDeclaration*> class_decl,
     *trace_stream_ << "** declaring class " << class_decl->name() << "\n";
   }
   Nonnull<SelfDeclaration*> self = class_decl->self();
-
   ImplScope class_scope(scope_info.innermost_scope);
 
+  // The base class and member declarations may refer to the class, so we must
+  // set the static type before we start processing them. We can't set the
+  // constant value until later, but the base class declaration doesn't need it.
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp:5193]: It looks like the error we get in the new test is appearing because we try to look at the constant value when evaluating the base class declaration, and it's not there. Maybe that's worth mentioning here -- this comment makes it sound like it'd be fine if the constant value were set early, but I think our diagnosis of inheritance cycles currently relies on that not being done. And conversely, I think there are correct cases (eg, CRTP) when we would want to use the constant value of the derived class in the base class declaration that won't work because it's not set yet.

**Review by zygoloid — APPROVED** [review]
Eventually we should remove `base_class` and `class_vtable` from `NominalClassType` entirely (this will be necessary in order to support incomplete class types); when that's done we can (and probably should) also set the constant value of the class early. That'd allow things like C++'s CRTP to be used.

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (geoffromer) [reply explorer/interpreter/type_checker.cpp:5193]: Good point; I've added a check that the base class is complete, which should make this less brittle. I don't know if that handles the CRTP case, but we can cross that bridge when we come to it.

**Review by zygoloid — APPROVED** [review]
