### PR TITLE
Parse invalid lambdas without crashing

### LINKED ISSUE #6823: Lambda `fn`  parsing crashes on invalid input
### Description of the bug:

The compiler crashes on this input:
```
require j%-fn->>
```

### What did you do, or what's a simple way to reproduce the bug?

```
echo -e 'require j%-fn->>' | ./bazel-bin/toolchain/carbon compile -
```

### What did you expect to happen?

Compilation should fail with a diagnostic

### What actually happened?

The check on [toolchain/parse/parse.cpp:68](https://github.com/carbon-language/carbon-lang/blob/067378ba3708fce5c673d260dbb2341623b7165c/toolchain/parse/parse.cpp#L68) fails. This happens because the `tree` object isn't in a valid state.

```
FATAL failure at toolchain/parse/parse.cpp:68: Invalid tree returned by Parse(): NodeId #node9 couldn't be extracted as a InfixOperatorPercent.
```

## Generalisation
Crashing seems to be caused by any string that matches the regular expression `require [A-Za-z0-9][+/%&^]-fn->>`.

## Compiler output
```
$ ./bazel-bin/toolchain/carbon compile /tmp/crash.carbon 
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: ./bazel-bin/toolchain/carbon compile /tmp/crash.carbon
1.      Carbon version: 0.0.0-0.dev+unknown
2.      Pending diagnostics:
/tmp/crash.carbon:1:10: error: whitespace missing around binary operator
require j%-fn->>
         ^

/tmp/crash.carbon:1:16: error: expected expression
require j%-fn->>
               ^

/tmp/crash.carbon:1:16: error: whitespace missing before binary operator
require j%-fn->>
               ^

/tmp/crash.carbon:1:17: error: expected expression
require j%-fn->>
                ^

/tmp/crash.carbon:1:17: error: expected `=>` or `{` after return type
require j%-fn->>
                ^

/tmp/crash.carbon:1:17: error: expected `impls` in `require` declaration
require j%-fn->>
                ^
3.      Filename: /tmp/crash.carbon
4.      Parser stack:
        cursor  position_ @ 1:17: token token8 : FileEnd
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  carbon    0x0000555af2294059
1  carbon    0x0000555af229458b
2  carbon    0x0000555af2291983
3  carbon    0x0000555af22956b9
4  libc.so.6 0x00007f0b67b43df0
5  libc.so.6 0x00007f0b67b9895c
6  libc.so.6 0x00007f0b67b43cc2 gsignal + 18
7  libc.so.6 0x00007f0b67b2c4ac abort + 34
8  carbon    0x0000555ae921b81c
9  carbon    0x0000555ae907ddd6
10 carbon    0x0000555ae907d922
11 carbon    0x0000555ae72a26eb
12 carbon    0x0000555ae72a2605
13 carbon    0x0000555ae72984a9
14 carbon    0x0000555ae7297ed7
15 carbon    0x0000555ae7292b60
16 carbon    0x0000555ae729103f
17 carbon    0x0000555ae72507d6
18 carbon    0x0000555ae7219227
19 carbon    0x0000555ae7216d6d
20 libc.so.6 0x00007f0b67b2dca8
21 libc.so.6 0x00007f0b67b2dd65 __libc_start_main + 133
22 carbon    0x0000555ae7216ca1
FATAL failure at toolchain/parse/parse.cpp:68: Invalid tree returned by Parse(): NodeId #node9 couldn't be extracted as a InfixOperatorPercent. Trace:
Aggregate N6Carbon5Parse13InfixOperatorIL_ZNS0_8NodeKind20InfixOperatorPercentEENS_3Lex17TokenIndexForKindIL_ZNS3_9TokenKind7PercentEEEEEE: begin
NodeIdInCategory Expr: kind PrefixOperatorMinus consumed
NodeIdInCategory Expr error: kind LambdaIntroducer doesn't match
Aggregate N6Carbon5Parse13InfixOperatorIL_ZNS0_8NodeKind20InfixOperatorPercentEENS_3Lex17TokenIndexForKindIL_ZNS3_9TokenKind7PercentEEEEEE: error
Error: LambdaIntroducer node left unconsumed.
Aborted                    (core dumped) ./bazel-bin/toolchain/carbon compile /tmp/crash.carbon
```

### PR DESCRIPTION
**Pull request by MK4070**
Fixes a compiler crash that occurs when a malformed lambda is provided as an operand to an operator that strictly expects an expression

Changes:
- Emits an `InvalidParse` dummy node at the current position to act as a placeholder for the missing body
- Changed state transitions so that `LambdaIntroducer` gets properly wrapped into a `Lambda` node

Closes #6823

### CODE REVIEW

File: toolchain/parse/handle_lambda.cpp [hunk 1]
```diff
@@ -87,8 +87,14 @@ auto HandleLambdaBody(Context& context) -> void {
                       "expected `=>` or `{{` after return type");
     context.emitter().Emit(*context.position(),
                            ExpectedLambdaBodyAfterReturnType);
+
+    // adding dummy for missing body without consuming the current token
```
Comment (danakj) [inline toolchain/parse/handle_lambda.cpp]: Comments should be sentences, including capitals and punctuation

Comment (MK4070) [reply toolchain/parse/handle_lambda.cpp]: fixed in latest commit

**Comment by danakj** [comment]
Can we add a test that would have crashed before this change?

**Comment by MK4070** [comment]
While verifying the added test, the existing `fail_expected_body.carbon` test revealed an identical error-recovery bug.

When a lambda is malformed right after the introducer or parameters (e.g., the `var x: auto = fn ;` case in the test), the parser correctly emits an error but immediately aborts via `context.ReturnErrorOnState()`.

While this early abort doesn't crash the compiler (it bypasses the strict AST verifier and hits a semantic TODO instead)
```
> echo -e 'fn F() { var x: auto = fn ; }' | ./bazel-bin/toolchain/carbon compile -
<stdin>:1:17: error: semantics TODO: `HandleAutoTypeLiteral`
fn F() { var x: auto = fn ; }
                ^~~~

<stdin>:1:27: error: expected `->`, `=>`, or `{`
fn F() { var x: auto = fn ; }
```

Current implementation generates the following parse tree-
```
- filename: fail_expected_body.carbon
  parse_tree: [
    {kind: 'FileStart', text: ''},
        {kind: 'FunctionIntroducer', text: 'fn'},
        {kind: 'IdentifierNameMaybeBeforeSignature', text: 'F'},
          {kind: 'ExplicitParamListStart', text: '('},
        {kind: 'ExplicitParamList', text: ')', subtree_size: 2},
      {kind: 'FunctionDefinitionStart', text: '{', subtree_size: 5},
        {kind: 'VariableIntroducer', text: 'var'},
            {kind: 'IdentifierNameNotBeforeSignature', text: 'x'},
            {kind: 'AutoTypeLiteral', text: 'auto'},
          {kind: 'VarBindingPattern', text: ':', subtree_size: 3},
        {kind: 'VariablePattern', text: 'var', subtree_size: 4},
        {kind: 'VariableInitializer', text: '='},
        {kind: 'LambdaIntroducer', text: 'fn'},  <--------------------
      {kind: 'VariableDecl', text: ';', has_error: yes, subtree_size: 8},
    {kind: 'FunctionDefinition', text: '}', subtree_size: 14},
    {kind: 'FileEnd', text: ''},
  ]
```
This parse tree output reveals two issues-
- Broken Contract: It leaves a dangling `LambdaIntroducer` without a closing Lambda node.
- Cascading Errors: It swallows structural tokens during recovery. Specifically, it consumes the `;` intended for the variable declaration, which deprives the parent scope of its terminator.

Adding a similar fix for this leads to a more granular parse tree
```
- filename: fail_expected_body.carbon
  parse_tree: [
    {kind: 'FileStart', text: ''},
        {kind: 'FunctionIntroducer', text: 'fn'},
        {kind: 'IdentifierNameMaybeBeforeSignature', text: 'F'},
          {kind: 'ExplicitParamListStart', text: '('},
        {kind: 'ExplicitParamList', text: ')', subtree_size: 2},
      {kind: 'FunctionDefinitionStart', text: '{', subtree_size: 5},
        {kind: 'VariableIntroducer', text: 'var'},
            {kind: 'IdentifierNameNotBeforeSignature', text: 'x'},
            {kind: 'AutoTypeLiteral', text: 'auto'},
          {kind: 'VarBindingPattern', text: ':', subtree_size: 3},
        {kind: 'VariablePattern', text: 'var', subtree_size: 4},
        {kind: 'VariableInitializer', text: '='},
          {kind: 'LambdaIntroducer', text: 'fn'},
          {kind: 'InvalidParse', text: ';', has_error: yes},
        {kind: 'Lambda', text: 'fn', has_error: yes, subtree_size: 3},
      {kind: 'VariableDecl', text: ';', subtree_size: 10},
    {kind: 'FunctionDefinition', text: '}', subtree_size: 16},
    {kind: 'FileEnd', text: ''},
  ]
```

In the first tree, the parser marks the entire variable declaration as erroneous (has_error: yes on `VariableDecl`). 
In the second tree, the error is isolated specifically to the right side of the assignment (the `Lambda` and `InvalidParse` nodes), leaving the `VariableDecl` itself without an error flag.

File: toolchain/parse/testdata/lambda/lambda.carbon [hunk 2]
```diff
@@ -14,6 +14,37 @@ var a: auto = fn [T:! type] (x: T) -> T { return x; };
 var b: auto = fn (x: i32) => x;
 var c: auto = fn { };
 
+// --- fail_unconsumed_lambda_introducer.carbon
+
+// Tests that the compiler does not crash when a LambdaIntroducer (`fn`)
```
Comment (CarbonInfraBot) [inline toolchain/parse/testdata/lambda/lambda.carbon]: **[diff]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>
```suggestion
// Tests that the compiler does not crash when a LambdaIntroducer (`fn`)
```

**Comment by danakj** [comment]
I would suggest [setting up pre-commit](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/contribution_tools.md#running-pre-commit) to run locally before pushing to save round trips through CI.

**Review by danakj — APPROVED** [review]
LGTM
