### PR TITLE
Tolerate incomplete interface when stringifying ImplWitnessAccess

### LINKED ISSUE #5727: Crash when using type as facet
### Description of the bug:

_No response_

### What did you do, or what's a simple way to reproduce the bug?

`bazel run toolchain -- compile tmp.carbon`, where `tmp.carbon` consists of:

```
interface Match {
  let Continuation:! type;
  fn Op[C:! Continuation](continuation: C);
}
```

### What did you expect to happen?

This code shouldn't compile, because it uses `Continuation` as a facet but its type doesn't guarantee that it's a facet.

### What actually happened?

The toolchain crashes

### Any other information, logs, or outputs that you want to share?

Output log:

```
INFO: Invocation ID: 3dcd6bdb-69eb-44b0-9fec-d7d48cfc4e97
INFO: Analyzed target //toolchain:toolchain (3 packages loaded, 341 targets configured).
INFO: Found 1 target...
Target //toolchain:carbon up-to-date:
  bazel-bin/toolchain/carbon
INFO: Elapsed time: 54.675s, Critical Path: 49.58s
INFO: 233 processes: 4 action cache hit, 50 disk cache hit, 42 internal, 141 linux-sandbox.
INFO: Build completed successfully, 233 total actions
INFO: Running command line: bazel-bin/toolchain/carbon <args omitted>
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /usr/local/google/home/gromer/.cache/bazel/_bazel_gromer/8a041fe50f7cc71fb747988ccfbd3528/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/carbon compile tmp2.carbon
1.      Carbon version: 0.0.0-0.dev+72cd8717e.dirty
2.      Pending diagnostics:
3.      Check::Context
          filename: tmp2.carbon
          NodeStack:
            0. InterfaceDefinitionStart: interface0
            1. FunctionIntroducer: no value
            2. IdentifierNameBeforeParams: name2
            3. ImplicitParamListStart: no value
            4. ImplicitParamList: inst_block12
            5. ExplicitParamListStart: no value
            6. IdentifierNameNotBeforeParams: name4
          inst_block_stack_:
            0.  inst_block<none>        {inst14, inst15, inst17}
            1.  inst_block4     {inst19, inst22}
            2.  inst_block<none>        {}
            3.  inst_block13    {inst42}
          pattern_block_stack_:
            0.  inst_block<none>        {inst40}
          param_and_arg_refs_stack:
            0.  inst_block<none>        {}
          args_type_info_stack_:
            0.  inst_block<none>        {inst22}
4.      tmp2.carbon:3:27: Checking LetBindingPattern
            fn Op[C:! Continuation](continuation: C);
                                    ^~~~~~~~~~~~~~~
 #0 0x00005635b11664b6 ___interceptor_backtrace /usr/local/google/home/gromer/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4497:13
 #1 0x00005635bdbd033d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:804:13
 #2 0x00005635bdbd0c6b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:888:1
 #3 0x00005635bdbcba80 llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x00005635bdbd113a SignalHandler(int, siginfo_t*, void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #5 0x00007f57e2baadf0 (/lib/x86_64-linux-gnu/libc.so.6+0x3fdf0)
 #6 0x00007f57e2bff95c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #7 0x00007f57e2baacc2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f57e2b934ac abort ./stdlib/abort.c:81:3
 #9 0x00005635bd4eb4be Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:45:3
#10 0x00005635b1279163 __is_long /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/string:1892:12
#11 0x00005635b1279163 ~basic_string /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/string:1228:9
#12 0x00005635b1279163 void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{"CHECK"}, Carbon::TemplateString<30>{"./toolchain/base/value_store.h"}, 107, Carbon::TemplateString<13>{"id.index >= 0"}, Carbon::TemplateString<3>{"{0}"}, Carbon::SemIR::InstBlockId&>(Carbon::SemIR::InstBlockId&) /proc/self/cwd/./common/check_internal.h:97:5
#13 0x00005635b1278f81 Carbon::ValueStore<Carbon::SemIR::InstBlockId>::Get(Carbon::SemIR::InstBlockId) const /proc/self/cwd/./toolchain/base/value_store.h:0:5
#14 0x00005635b426b7e3 Carbon::SemIR::Stringify(Carbon::SemIR::File const&, Carbon::SemIR::(anonymous namespace)::StepStack&) /proc/self/cwd/./toolchain/sem_ir/inst_kind.def:75:1
#15 0x00005635b4266b7c begin /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/SmallVector.h:268:45
#16 0x00005635b4266b7c end /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/SmallVector.h:270:27
#17 0x00005635b4266b7c ~SmallVector /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/SmallVector.h:1203:46
#18 0x00005635b4266b7c ~StepStack /proc/self/cwd/toolchain/sem_ir/stringify.cpp:46:7
#19 0x00005635b4266b7c Carbon::SemIR::StringifyConstantInst(Carbon::SemIR::File const&, Carbon::SemIR::InstId) /proc/self/cwd/toolchain/sem_ir/stringify.cpp:692:1
#20 0x00005635b30e2854 insert /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/string:3118:10
#21 0x00005635b30e2854 operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> > /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/string:4089:26
#22 0x00005635b30e2854 Carbon::Check::DiagnosticEmitter::ConvertArg(llvm::Any) const /proc/self/cwd/toolchain/check/diagnostic_emitter.cpp:73:16
#23 0x00005635b30e96da reset /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/__memory/unique_ptr.h:297:21
#24 0x00005635b30e96da ~unique_ptr /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/__memory/unique_ptr.h:269:71
#25 0x00005635b30e96da ~Any /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/Any.h:28:16
#26 0x00005635b30e96da llvm::Any Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::MakeAny<Carbon::Check::TypeOfInstId>(Carbon::Check::TypeOfInstId) /proc/self/cwd/./toolchain/diagnostics/diagnostic_emitter.h:398:25
#27 0x00005635b310fbf8 Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Build<Carbon::Diagnostics::BoolAsSelect, Carbon::Check::TypeOfInstId, Carbon::Diagnostics::BoolAsSelect, Carbon::SemIR::TypeId>(Carbon::Check::LocIdForDiagnostics, Carbon::Diagnostics::DiagnosticBase<Carbon::Diagnostics::BoolAsSelect, Carbon::Check::TypeOfInstId, Carbon::Diagnostics::BoolAsSelect, Carbon::SemIR::TypeId> const&, std::__1::type_identity<Carbon::Diagnostics::BoolAsSelect>::type, std::__1::type_identity<Carbon::Check::TypeOfInstId>::type, std::__1::type_identity<Carbon::Diagnostics::BoolAsSelect>::type, std::__1::type_identity<Carbon::SemIR::TypeId>::type) /proc/self/cwd/./toolchain/diagnostics/diagnostic_emitter.h:392:46
#28 0x00005635b310f96d operator() /proc/self/cwd/toolchain/check/convert.cpp:0:34
#29 0x00005635b310f96d Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder llvm::function_ref<Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder ()>::callback_fn<Carbon::Check::Convert(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, Carbon::Check::ConversionTarget, Carbon::SemIR::InstId)::$_2>(long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#30 0x00005635b31fe9cc Carbon::Check::PerformImplLookup(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::ConstantId, Carbon::SemIR::AssociatedEntityType, Carbon::SemIR::InstId, llvm::function_ref<Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder ()>) /proc/self/cwd/toolchain/check/member_access.cpp:221:12
#31 0x00005635b31fe48a Carbon::Check::PerformCompoundMemberAccess(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, Carbon::SemIR::InstId, llvm::function_ref<Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder ()>) /proc/self/cwd/toolchain/check/member_access.cpp:674:11
#32 0x00005635b321f0f1 Carbon::Check::BuildUnaryOperator(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::Check::Operator, Carbon::SemIR::InstId, llvm::function_ref<Carbon::Diagnostics::Emitter<Carbon::Check::LocIdForDiagnostics>::Builder ()>) /proc/self/cwd/toolchain/check/operator.cpp:45:22
#33 0x00005635b30f8dcd Carbon::Check::Convert(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, Carbon::Check::ConversionTarget, Carbon::SemIR::InstId) /proc/self/cwd/toolchain/check/convert.cpp:1268:15
#34 0x00005635b30fec35 operator== /proc/self/cwd/./toolchain/base/index_base.h:69:22
#35 0x00005635b30fec35 Carbon::Check::ExprAsType(Carbon::Check::Context&, Carbon::SemIR::LocId, Carbon::SemIR::InstId, bool) /proc/self/cwd/toolchain/check/convert.cpp:1505:20
#36 0x00005635b3080fc0 Carbon::Check::HandleAnyBindingPattern(Carbon::Check::Context&, Carbon::Parse::NodeId, Carbon::Parse::NodeKind) /proc/self/cwd/toolchain/check/handle_binding_pattern.cpp:35:7
#37 0x00005635b3080e36 Carbon::Check::HandleParseNode(Carbon::Check::Context&, Carbon::Parse::NodeIdForKind<Carbon::Parse::NodeKind::LetBindingPattern>) /proc/self/cwd/toolchain/check/handle_binding_pattern.cpp:266:3
#38 0x00005635b304afbf Carbon::Check::CheckUnit::ProcessNodeIds() /proc/self/cwd/./toolchain/parse/node_kind.def:0:1
#39 0x00005635b3044ef3 Carbon::Check::CheckUnit::Run() /proc/self/cwd/toolchain/check/check_unit.cpp:92:7
#40 0x00005635b302a516 Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, llvm::ArrayRef<llvm::function_ref<Carbon::Parse::TreeAndSubtrees const& ()>>, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::StringRef, llvm::raw_ostream*, bool) /proc/self/cwd/toolchain/check/check.cpp:384:5
#41 0x00005635b12464d0 Carbon::CompileSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/compile_subcommand.cpp:967:3
#42 0x00005635b1237930 index /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/variant:728:12
#43 0x00005635b1237930 valueless_by_exception /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/variant:725:89
#44 0x00005635b1237930 __destroy /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/variant:779:1
#45 0x00005635b1237930 ~__dtor /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/variant:779:1
#46 0x00005635b1237930 ~variant /usr/local/google/home/gromer/llvm-project/build/bin/../include/c++/v1/variant:1237:74
#47 0x00005635b1237930 ~ErrorOr /proc/self/cwd/./common/error.h:79:21
#48 0x00005635b1237930 Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:145:1
#49 0x00005635b1208c53 Carbon::Main(int, char**) /proc/self/cwd/toolchain/install/busybox_main.cpp:89:42
#50 0x00005635b120543d main /proc/self/cwd/toolchain/install/busybox_main.cpp:0:17
#51 0x00007f57e2b94ca8 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#52 0x00007f57e2b94d65 call_init ./csu/../csu/libc-start.c:128:20
#53 0x00007f57e2b94d65 __libc_start_main ./csu/../csu/libc-start.c:347:5
#54 0x00005635b111d961 _start (/usr/local/google/home/gromer/.cache/bazel/_bazel_gromer/8a041fe50f7cc71fb747988ccfbd3528/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/carbon+0xc7f8961)
CHECK failure at ./toolchain/base/value_store.h:107: id.index >= 0: inst_block<none>
```

### PR DESCRIPTION
**Pull request by geoffromer**
Closes #5727

### CODE REVIEW

File: toolchain/sem_ir/stringify.cpp [hunk 1]
```diff
@@ -420,35 +420,41 @@ class Stringifier {
   auto StringifyInst(InstId /*inst_id*/, ImplWitnessAccess inst) -> void {
     auto witness_inst_id =
         sem_ir_->constant_values().GetConstantInstId(inst.witness_id);
+    bool pushed_specific = false;
```
Comment (danakj) [inline toolchain/sem_ir/stringify.cpp]:
```suggestion
    bool pushed_associated_entity = false;
```

File: toolchain/sem_ir/stringify.cpp [hunk 2]
```diff
@@ -420,35 +420,41 @@ class Stringifier {
...
-                                    .Get(associated_const->assoc_const_id)
-                                    .name_id);
-      } else if (auto function_decl =
-                     sem_ir_->insts().TryGetAs<FunctionDecl>(entity_inst_id)) {
-        const auto& function =
-            sem_ir_->functions().Get(function_decl->function_id);
-        step_stack_->PushNameId(function.name_id);
-      } else {
-        step_stack_->PushInstId(entity_inst_id);
+      if (interface.associated_entities_id.has_value()) {
```
Comment (danakj) [inline toolchain/sem_ir/stringify.cpp]: I am worried about the fact this will no longer be false for being-defined-interfaces, as we're changing things to allow referencing things inside the interface during its definition.

Also the `TODO: element` path is now obsolete, I think. `TryGetSpecificInterfaceForImplWitness` says to handle `ImplWitness` but we have no test that sees such a thing. `ImplWitnessAccess` on a concrete `ImplWitness` is going to eval to [whatever it's accessing](https://github.com/carbon-language/carbon-lang/blob/72cd8717e38cac12636d2fc6b950bc5c282f8860/toolchain/check/eval_inst.cpp#L258-L259), or [an error](https://github.com/carbon-language/carbon-lang/blob/72cd8717e38cac12636d2fc6b950bc5c282f8860/toolchain/check/eval_inst.cpp#L267), so we are never left with an `ImplWitnessAccess` instruction with an `ImplWitness` inside to stringify.

So what if we do the following:
- Make the TryGetSpecificInterfaceForImplWitness path non-conditional, drop the if there.
- Keep this if here, but invert it. When there's no associated_entities_id, stringify to a "TODO: element %N in incomplete %I" (note addition of **incomplete** in the string.
- Then we should be able to drop the boolean local too.

WDYT?

Comment (geoffromer) [reply toolchain/sem_ir/stringify.cpp]: Sure, that seems to work.

File: toolchain/sem_ir/stringify.cpp [hunk 3]
```diff
@@ -420,10 +420,14 @@ class Stringifier {
   auto StringifyInst(InstId /*inst_id*/, ImplWitnessAccess inst) -> void {
     auto witness_inst_id =
         sem_ir_->constant_values().GetConstantInstId(inst.witness_id);
-    if (auto specific_interface =
-            TryGetSpecificInterfaceForImplWitness(witness_inst_id)) {
-      const auto& interface =
-          sem_ir_->interfaces().Get(specific_interface->interface_id);
+    auto specific_interface =
+        TryGetSpecificInterfaceForImplWitness(witness_inst_id);
```
Comment (danakj) [inline toolchain/sem_ir/stringify.cpp]: Cool, then we can get rid of the whole optional:

```suggestion
    auto lookup = sem_ir_->insts().GetAs<LookupImplWitness>(witness_inst_id);
    auto specific_interface = sem_ir_->specific_interfaces().Get(
          lookup.query_specific_interface_id);
```

And `TryGetSpecificInterfaceForImplWitness` can be removed.

File: toolchain/sem_ir/stringify.cpp [hunk 4]
```diff
@@ -420,10 +420,14 @@ class Stringifier {
...
+    const auto& interface =
+        sem_ir_->interfaces().Get(specific_interface->interface_id);
```
Comment (danakj) [inline toolchain/sem_ir/stringify.cpp]:
```suggestion
        sem_ir_->interfaces().Get(specific_interface.interface_id);
```

**Review by danakj — APPROVED** [review]
Thanks! LGTM
