### PR TITLE
Produce helpful diagnostics when converting to a facet fails

### LINKED ISSUE #5027: Convert error for converting to a FacetValue is confusing
### Description of the bug:

The error for conversion prints an error saying:
```
error: cannot implicitly convert from `type` to `A & B` [ImplicitAsConversionFailure]
note: type `type` does not implement interface `Core.ImplicitAs(A & B)` [MissingImplInMemberAccessNote]
```
The name `type` in both of these messages should really be the type value being converted, not its type which is just `TypeType` aka `type`.

In most conversion errors, printing the type is helpful (and values can be runtime values). But for type values this is not the case.

### What did you do, or what's a simple way to reproduce the bug?

_No response_

### What did you expect to happen?

_No response_

### What actually happened?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by danakj**
When converting to a facet there are three different failure modes:

1. You provided a non-type value. Only types can convert to facets. So we tell you that we found a non-type value.
2. You provided a facet type (which has type TypeType) which does not have witnesses for the the target facet's type. So we tell you that the type `T` implements `X` but needs to implement `Y`.
2. You provided a (non-facet-type) concrete type (of type TypeType) which does not implement the target facet's type (which is a FacetType). So we tell you that we need the type to implement the FacetType but it does not.
3. You provided a FacetAccessType (which is of type TypeType also, but we special case this), whose underlying FacetType is not compatible with the target facet's type. So we tell you that we need the type to implement `X` but found a FacetAccessType `T` which implements `Y`.

Closes #5027

### CODE REVIEW

File: toolchain/check/convert.cpp [hunk 1]
```diff
@@ -1213,11 +1213,43 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
+                                  target.kind == ConversionTarget::ExplicitAs
+                                      ? ExplicitAsConversionFailure
+                                      : ImplicitAsConversionFailure,
+                                  expr_id, target.type_id);
+      if (sem_ir.types().Is<SemIR::FacetType>(target.type_id)) {
+        if (auto facet_access_type =
+                context.insts().TryGetAs<SemIR::FacetAccessType>(expr_id)) {
+          CARBON_DIAGNOSTIC(
+              ConversionFailureFacetAccessTypeToFacetNote, Note,
+              "expected type implementing {1}; found type {0} implementing {2}",
```
Comment (josh11b) [inline toolchain/check/convert.cpp]: Why `{1}` before `{0}`?

File: toolchain/check/convert.cpp [hunk 2]
```diff
@@ -1213,11 +1213,43 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
+              SemIR::TypeId, SemIR::TypeId, SemIR::TypeId);
+          builder.Note(loc_id, ConversionFailureFacetAccessTypeToFacetNote,
+                       context.types().GetTypeIdForTypeInstId(expr_id),
```
Comment (josh11b) [inline toolchain/check/convert.cpp]: I think it is better to pass an `InstId` and use `InstIdAsType` in the diagnostic instead of `SemIR::TypeId`

File: toolchain/check/testdata/facet/min_prelude/fail_todo_call_combined_impl_witness.carbon [hunk 3]
```diff
@@ -39,15 +39,21 @@ fn G[T:! A & Empty & B](t: T) {
   // TODO: Qualified lookup of `AA` and `BB` should also be possible here, using
   // the witnesses found in type deduction.
 
-  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+7]]:3: error: cannot implicitly convert value of type `Empty & A & B` to `A` [ImplicitAsConversionFailure]
+  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+10]]:3: error: cannot implicitly convert value of type `Empty & A & B` to `A` [ImplicitAsConversionFailure]
+  // CHECK:STDERR:   T.(A.AA)();
+  // CHECK:STDERR:   ^~~~~~~~
+  // CHECK:STDERR: fail_todo_call_combined_impl_witness.carbon:[[@LINE+7]]:3: note: expected type implementing `A`; found non-type value [ConversionFailureNonTypeToFacetNote]
```
Comment (josh11b) [inline toolchain/check/testdata/facet/min_prelude/fail_todo_call_combined_impl_witness.carbon]: `T` is a facet, it doesn't seem like it should be getting the "found non-type value" error.

File: toolchain/check/testdata/interface/no_prelude/fail_member_lookup.carbon [hunk 4]
```diff
@@ -45,7 +45,10 @@ fn F() {
 
 interface Different {}
 
-// CHECK:STDERR: fail_member_lookup.carbon:[[@LINE+7]]:24: error: cannot implicitly convert value of type `Different` to `Interface` [ImplicitAsConversionFailure]
+// CHECK:STDERR: fail_member_lookup.carbon:[[@LINE+10]]:24: error: cannot implicitly convert value of type `Different` to `Interface` [ImplicitAsConversionFailure]
+// CHECK:STDERR: fn G(U:! Different) -> U.(Interface.T);
+// CHECK:STDERR:                        ^~~~~~~~~~~~~~~
+// CHECK:STDERR: fail_member_lookup.carbon:[[@LINE+7]]:24: note: expected type implementing `Interface`; found non-type value [ConversionFailureNonTypeToFacetNote]
```
Comment (josh11b) [inline toolchain/check/testdata/interface/no_prelude/fail_member_lookup.carbon]: This is another case that seems misleading to say "non-type value" to describe `U` which is a facet.

File: toolchain/check/convert.cpp [hunk 5]
```diff
@@ -1213,11 +1213,43 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
       CARBON_DIAGNOSTIC(ExplicitAsConversionFailure, Error,
                         "cannot convert value of type {0} to {1} with `as`",
                         TypeOfInstId, SemIR::TypeId);
-      return context.emitter().Build(loc_id,
-                                     target.kind == ConversionTarget::ExplicitAs
-                                         ? ExplicitAsConversionFailure
-                                         : ImplicitAsConversionFailure,
-                                     expr_id, target.type_id);
+      auto builder =
+          context.emitter().Build(loc_id,
```
Comment (josh11b) [inline toolchain/check/convert.cpp]: These notes end up making the diagnostic quite long. In any of these cases, could we replace the error with a different error instead of adding a note?

File: toolchain/check/convert.cpp (hunk 1 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: was just matching the parameter order from the error itself, switched.

File: toolchain/check/convert.cpp (hunk 2 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Done, thanks. Also noticed I can use a TypeOfInstId in one case.

File: toolchain/check/testdata/facet/min_prelude/fail_todo_call_combined_impl_witness.carbon (hunk 3 above)
Comment (danakj) [reply toolchain/check/testdata/facet/min_prelude/fail_todo_call_combined_impl_witness.carbon]: Good catch, fixed.

File: toolchain/check/testdata/interface/no_prelude/fail_member_lookup.carbon (hunk 4 above)
Comment (danakj) [reply toolchain/check/testdata/interface/no_prelude/fail_member_lookup.carbon]: Yep, fixed.

File: toolchain/check/convert.cpp (hunk 5 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: I thought about this, but then I thought we have to double the number of diagnostics as well, to handle implicit and `as`. But maybe we can use `BoolAsSelect` and combine things.

Comment (danakj) [reply toolchain/check/convert.cpp]: Ok done in the last commit! I tried a bunch of different versions, especially for the ConversionFailureTypeToFacet message, this was as good as I could get at the moment without making things too redundant.

**Review by danakj — COMMENTED** [review]
PTAL

File: toolchain/check/convert.cpp [hunk 6]
```diff
@@ -1208,19 +1208,60 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
-                                         : ImplicitAsConversionFailure,
-                                     expr_id, target.type_id);
+      bool explicit_as = target.kind == ConversionTarget::ExplicitAs;
+      auto type_of_expr_id = context.insts().Get(expr_id).type_id();
+      if (target.type_id == SemIR::TypeType::SingletonTypeId ||
+          sem_ir.types().Is<SemIR::FacetType>(target.type_id)) {
+        if (context.types().Is<SemIR::FacetType>(type_of_expr_id)) {
+          CARBON_DIAGNOSTIC(
+              ConversionFailureFacetToFacet, Error,
+              "cannot{0:| implicitly} convert type {1} that implements {2} to "
```
Comment (zygoloid) [inline toolchain/check/convert.cpp]: Usually when we talk about "convert[ing] X to Y", X describes a source expression, and Y describes a target type, so we're talking about something like `X as Y` or `let v: Y = X;`. But here, "type implementing <facet>" is a type, but it's not the target type of the conversion: converting an expression `X` to type `T` where `T:! Y` would be a "conversion to a type (T) implementing Y". So I find this phrasing inconsistent. At the same time, I do like that we say "type implementing Y" in this diagnostic, because I think that gives the reader a good clue about what's going on.

I suggest that we change the word "to" to "into" in these diagnostics, so that we use "convert X to Y" to mean a conversion of source expression X to target type Y, and we use "convert X into Y" to mean a conversion of source expression X to a target expression described by Y. So for example "convert expression X to type Y" and "convert expression X into expression of type Y" would mean the same thing.

tl;dr:
```suggestion
              "cannot{0:| implicitly} convert type {1} that implements {2} into "
```
here and in the next 3 diagnostics.

File: toolchain/check/convert.cpp [hunk 7]
```diff
@@ -1208,19 +1208,60 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
+                                         explicit_as, expr_id, expr_id,
+                                         target.type_id);
+        } else if (auto facet_access_type =
+                       context.insts().TryGetAs<SemIR::FacetAccessType>(
+                           expr_id)) {
+          CARBON_DIAGNOSTIC(
+              ConversionFailureFacetAccessTypeToFacet, Error,
+              "cannot{0:| implicitly} convert type {1} that implements {2} to "
+              "type implementing {3}{0: with `as`|}",
+              BoolAsSelect, InstIdAsType, TypeOfInstId, SemIR::TypeId);
```
Comment (zygoloid) [inline toolchain/check/convert.cpp]: This appears to be identical to the previous diagnostic text; can we use the same `CARBON_DIAGNOSTIC` in both cases?

File: toolchain/check/convert.cpp [hunk 8]
```diff
@@ -1208,19 +1208,60 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
+          return context.emitter().Build(
+              loc_id, ConversionFailureFacetAccessTypeToFacet, explicit_as,
+              expr_id, facet_access_type->facet_value_inst_id, target.type_id);
+        } else if (type_of_expr_id == SemIR::TypeType::SingletonTypeId) {
+          CARBON_DIAGNOSTIC(
+              ConversionFailureTypeToFacet, Error,
+              "cannot{0:| implicitly} convert type {1} to type implementing "
+              "{2}{0: with `as`|}; type {1} does not implement the required "
+              "interface(s)",
```
Comment (zygoloid) [inline toolchain/check/convert.cpp]: The `; type {1} does not implement the required interface(s)` part here is inconsistent with the prior diagnostic. Since they're diagnosing the same case with the only difference being whether the source type has locally-known constraints, it seems like the diagnostics ought to present the same information.

In discussion with @josh11b, we think the right place to produce this extra information about missing `impl`s would be to produce notes as part of impl lookup that describe exactly which impls are missing (as well as which impls we tried but failed to use and potentially why) -- though not as part of this PR. Once those notes are added, this extra information would be redundant, so let's omit it here:
```suggestion
              "{2}{0: with `as`|}",
```
(This diagnostic could then also be combined with the previous two with another select, but maybe it's not worthwhile.)

File: toolchain/check/convert.cpp [hunk 9]
```diff
@@ -1208,19 +1208,60 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
-                        "cannot convert value of type {0} to {1} with `as`",
-                        TypeOfInstId, SemIR::TypeId);
-      return context.emitter().Build(loc_id,
-                                     target.kind == ConversionTarget::ExplicitAs
-                                         ? ExplicitAsConversionFailure
-                                         : ImplicitAsConversionFailure,
-                                     expr_id, target.type_id);
+      bool explicit_as = target.kind == ConversionTarget::ExplicitAs;
+      auto type_of_expr_id = context.insts().Get(expr_id).type_id();
+      if (target.type_id == SemIR::TypeType::SingletonTypeId ||
```
Comment (zygoloid) [inline toolchain/check/convert.cpp:1264]: [No action requested]

As a general thought, perhaps the conversion between facet types should be treated like a `final impl`, so that we diagnose these first three cases in `PerformBuiltinConversion` rather than here. Doing these checks here in this PR makes sense though, given that it matches the current behavior.

(As noted below, we'll eventually want impl lookup to explain what went wrong, and that'll be easier to do if we produce the diagnostics as part of the code that performs impl lookup rather than after we try a user-defined conversion.)

File: toolchain/check/convert.cpp (hunk 7 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Yes but we have linters that prevent us from using the same name twice, so it would have to move out of the `if` branches which seemed weird to me since it would be only used sometimes. So, I think we shouldn't, WDYT?

Comment (zygoloid) [reply toolchain/check/convert.cpp]: Moving it to an outer scope seems fine to me. If you prefer you could factor out a function to emit the diagnostic; we do that in some places in order to keep the `CARBON_DIAGNOSTIC` next to the `Emit` call.

File: toolchain/check/convert.cpp (hunk 9 above)
Comment (danakj) [reply toolchain/check/convert.cpp:1264]: This would disallow the user to add their own impl ImplicitAs/As to convert between facet types right? I think that would be good. I am going to file an issue to track this idea cuz it sounds like it needs a proposal: https://github.com/carbon-language/carbon-lang/issues/5122

File: toolchain/check/convert.cpp (hunk 6 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Thanks, I also struggled with this. I like the direction here.

File: toolchain/check/convert.cpp (hunk 8 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Done.

I think combining them is a bit of a pain cuz it's more than just a bool, we also have to conditionally construct a FacetAccessType, so we have to also conditionally unwrap the optional, it just makes for a lot of conditions. That said, I can combine two other diagnostics, and I did combine these branches a little more.

File: toolchain/check/convert.cpp (hunk 7 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Done, I combined these into one branch.

**Review by danakj — COMMENTED** [review]
Thanks, PTAL

File: toolchain/check/convert.cpp (hunk 7 above)
Comment (josh11b) [reply toolchain/check/convert.cpp]: I think @zygoloid was suggesting something different, where just the `CARBON_DIAGNOSTIC(`...`)` and `context.emitter().Build(`...`)` inside the `if` branch would be moved into a different function (a much smaller change from what you had before).

Comment (danakj) [reply toolchain/check/convert.cpp]: I moved them all as a group since they will also be moving as a group over to PerformBuiltinConversion in the future, and addressed combining the diagnostics by merging if branches.

File: toolchain/check/convert.cpp [hunk 10]
```diff
@@ -1123,6 +1123,59 @@ static auto PerformCopy(Context& context, SemIR::InstId expr_id, bool diagnose)
...
+                        "cannot{0:| implicitly} convert type {1} "
+                        "into type implementing {2}{0: with `as`|}",
+                        BoolAsSelect, InstIdAsType, SemIR::TypeId);
+      return context.emitter().Build(
+          loc_id, ConversionFailureTypeToFacet,
+          target.kind == ConversionTarget::ExplicitAs, expr_id, target.type_id);
+    }
+  } else {
+    CARBON_DIAGNOSTIC(
+        ConversionFailureNonTypeToTypeOrFacet, Error,
```
Comment (josh11b) [inline toolchain/check/convert.cpp]: Here is a case where leaning into the fact that types are facets makes things more concise without introducing confusion.
```suggestion
        ConversionFailureNonTypeToFacet, Error,
```

File: toolchain/check/convert.cpp [hunk 11]
```diff
@@ -1208,59 +1261,21 @@ auto Convert(Context& context, SemIR::LocId loc_id, SemIR::InstId expr_id,
...
-              ConversionFailureNonTypeToTypeOrFacet, Error,
-              "cannot{0:| implicitly} convert non-type value of type {1} to "
-              "{2:|type implementing }{3}{0: with `as`|}",
-              BoolAsSelect, TypeOfInstId, BoolAsSelect, SemIR::TypeId);
-          return context.emitter().Build(
-              loc_id, ConversionFailureNonTypeToTypeOrFacet, explicit_as,
-              expr_id, target.type_id == SemIR::TypeType::SingletonTypeId,
-              target.type_id);
-        }
+        return DiagnoseConversionFailureToConstraintValue(context, loc_id,
```
Comment (josh11b) [inline toolchain/check/convert.cpp:1268]: Add "// TODO" to move this into `PerformBuiltinConversion` (ideally with a reference to https://github.com/carbon-language/carbon-lang/issues/5122).

**Review by josh11b — APPROVED** [review]

File: toolchain/check/convert.cpp (hunk 10 above)
Comment (danakj) [reply toolchain/check/convert.cpp]: Done

File: toolchain/check/convert.cpp (hunk 11 above)
Comment (danakj) [reply toolchain/check/convert.cpp:1268]: Good idea, done.
