### PR TITLE
Fix crash in lowering vptr initialization

### LINKED ISSUE #5094: Crash lowering `extend: base`
### Description of the bug:

I was playing around with the toolchain on Compiler Explorer and managed to crash it. I was fiddling around trying to get it to initialize an object from a derived class, and it kept asking for an instance of `.base` to be provided, and so I tried providing `{}` as an empty literal, and it crashed.

Here is the code that I wrote:

```carbon
package sample;

base class Thing {
    virtual fn Greet[self: Self]() -> i32;
}

class Concrete {
    extend base: Thing;
    fn Create(n: i32) -> Self {
        return { .n = n, .base = {} };
    }
    fn Greet[self: Self]() -> i32 {
        return self.n;
    }
    var n: i32;
}

fn Main() -> i32 {
    let c: Concrete = Concrete.Create(5);
    return 0;
}
```

And here is the compiler output:

```
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/carbon-trunk/bin/carbon compile --output=/app/output.s --asm-output <source>
1.	Pending diagnostics:
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  carbon    0x000060fbf35e51d8
1  carbon    0x000060fbf35e2d2d
2  carbon    0x000060fbf35e5751
3  libc.so.6 0x00007c1587642520
4  libc.so.6 0x00007c15876969fc pthread_kill + 300
5  libc.so.6 0x00007c1587642476 raise + 22
6  libc.so.6 0x00007c15876287f3 abort + 211
7  carbon    0x000060fbf32fa396
8  carbon    0x000060fbef5b3393
9  carbon    0x000060fbef5b3268
10 carbon    0x000060fbef5c74a6
11 carbon    0x000060fbef5c742e
12 carbon    0x000060fbef5c0635
13 carbon    0x000060fbef5c01bc
14 carbon    0x000060fbef5b410b
15 carbon    0x000060fbef5b1dab
16 carbon    0x000060fbef5b10cb
17 carbon    0x000060fbee3175ea
18 carbon    0x000060fbee3137f9
19 carbon    0x000060fbee312126
20 carbon    0x000060fbee30b73f
21 carbon    0x000060fbee2e93e7
22 libc.so.6 0x00007c1587629d90
23 libc.so.6 0x00007c1587629e40 __libc_start_main + 128
24 carbon    0x000060fbee2e6f25
FATAL failure at toolchain/lower/file_context.cpp:178: Missing value: inst117 specific<none> {kind: ClassElementAccess, arg0: inst78, arg1: element1, type: type(inst16)}
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

And  here is a Compiler Explorer link:

https://carbon.compiler-explorer.com/z/ofe7nfbrM

### PR DESCRIPTION
**Pull request by dwblaikie**
Seems the instructions got emitted out of order & that caused problems
for lowering. This was because most of the initialization instructions
were added to a PendingBlock, but the vptr initialization instructions
were added to the (non-pending) block directly.

(I don't fully understand the pending stuff (is there a different test I
could/should write that demonstrates the vptr init instructions not
being discarded because they didn't go in the pending block (before this
patch)), or the out of order instruction problem (could we add more
robust checking for instruction ordering?) - but perhaps this is
adequate understanding for this bug fix at least)

Fixes #5094

### CODE REVIEW

**Comment by danakj** [comment]
> (I don't fully understand the pending stuff

My understanding here is that all instructions that are part of the initialization of storage should go in the init block. Sometimes the storage can be elided entirely and then all those instructions which would not be necessary can go away together. So if the instruction is part of initialization is goes in, if it would be needed regardless, it does not. The changes you made here seem aligned and correct to me - but letting josh review :)

File: toolchain/check/convert.cpp [hunk 1]
```diff
@@ -501,14 +501,14 @@ static auto ConvertStructToStructOrClass(Context& context,
...
                                               .index = SemIR::ElementIndex(i)});
       auto vtable_ptr_id = AddInst<SemIR::VtablePtr>(
-          context, value_loc_id, {.type_id = dest_field.type_id});
+          *target.init_block, value_loc_id, {.type_id = dest_field.type_id});
       auto init_id =
-          AddInst<SemIR::InitializeFrom>(context, value_loc_id,
+          AddInst<SemIR::InitializeFrom>(*target.init_block, value_loc_id,
                                          {.type_id = dest_field.type_id,
                                           .src_id = vtable_ptr_id,
                                           .dest_id = dest_id});
```
Comment (zygoloid) [inline toolchain/check/convert.cpp]: Generally the init block shouldn't contain operations with side effects, just instructions that are being used to compute the `init_id` -- that is, to compute the location being initialized. In principle, the right thing to do would be to add the `ClassElementAccess` to the `init_block`, and then insert the init block before we create the `InitializeFrom` instruction, because that instruction is using `init_id` as an operand and has side effects. But in practice we may as well insert the init block before we create any of these instructions and add the instructions directly into the context, saving the work of performing a copy, since we know we're always going to insert the init block anyway.

Comment (dwblaikie) [reply toolchain/check/convert.cpp]: ah, OK - sure, I'm open to that (bit more performance, bit of a cost in maintainability - dependence on the class init always being emitted, etc) - made the change in https://github.com/carbon-language/carbon-lang/pull/5184/commits/f8d40a5d4fb1e8b20e575c4db8f28c42f2c277a3 - though I wanted to make sure the assertion was working there and realized why I'd commented it out: The constexpr checking in CARBON_CHECK ( https://github.com/carbon-language/carbon-lang/blob/0d3d82947873473fbcfde7fb4c1699af8ff8c7b6/common/check_internal.h#L19 ) triggers because the non-type template parameter is constexpr within the template specialization. 

(we discussed this offline and you mentioned static_assert which I thought might apply - but it's not quite the right fit. The condition under which ToClass should be true is a runtime one - so it needs to be checked only within that controlling condition. I could repeat part of that condition inside the CHECK, which would ensure the total condition isn't constexpr, but involves duplicating part of the condition which is unfortunate. Could introduce an identity non-constexpr function for cases like this? For now I've made a named local non-const variable to workaround the issue)

File: toolchain/check/convert.cpp [hunk 2]
```diff
@@ -499,7 +499,9 @@ static auto ConvertStructToStructOrClass(Context& context,
                             dest_elem_fields.size()});
   for (auto [i, dest_field] : llvm::enumerate(dest_elem_fields)) {
     if (dest_field.name_id == SemIR::NameId::Vptr) {
-      // CARBON_CHECK(ToClass, "Only classes should have vptrs.");
+      bool NonConstexprToClass = ToClass;
+      CARBON_CHECK(NonConstexprToClass, "Only classes should have vptrs.");
```
Comment (zygoloid) [inline toolchain/check/convert.cpp]: Hm. How would you feel about something like this:
```suggestion
      if constexpr (!ToClass) {
        CARBON_FATAL("Only classes should have vptrs.");
      }
```

**Review by zygoloid — APPROVED** [review]

File: toolchain/check/convert.cpp (hunk 2 above)
Comment (dwblaikie) [reply toolchain/check/convert.cpp]: I'm open to it (applied in 26bd460) - both feel a bit awkward, but such is the way of things.
