### PR TITLE
Prevent generic bindings in binding types

### LINKED ISSUE #2783: Prevent generic bindings in types
### Description of the bug:

According to explorer:
1) `var x: (T: type);` -- "the type of a binding pattern cannot contain bindings"
2) `var x: (T:! type);` -- valid
3) `var x: (T:! type) = 0;` -- "type error in initializer of variable: 'i32' is not implicitly convertible to 'T'"

Per [#syntax discussion](https://discord.com/channels/655572317891461132/709488742942900284/1098318068725334066) we'll disallow (2), with the rule that types cannot contain binding patterns. Note that making this an error will also change (3).

### What did you do, or what's a simple way to reproduce the bug?

```
fn Main() {
  var x: (T:! type);
  return 0;
}
```

There's probably also a related scenario for:

```
fn Foo(x: (T:! type)) {}
```

### What did you expect to happen?

Should be a compile error

### What actually happened?

Code compiles

### Any other information, logs, or outputs that you want to share?

Should probably wait on #2782 and adjust the logic there (I'm thinking bool require_binding to an enum Bindings // Required, Disallowed, Mixable), also replacing the VisitPatterns call that does the current "the type of a binding pattern cannot contain bindings"

### PR DESCRIPTION
**Pull request by jonmeow**
Adds TODO #2788 for the bigger refactoring.

Fixes #2783

### CODE REVIEW

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -4138,16 +4138,25 @@ auto TypeChecker::TypeCheckPattern(
     }
     *trace_stream_ << "\n";
   }
-  if (require_irrefutable) {
-    switch (p->kind()) {
-      case PatternKind::AutoPattern:
-      case PatternKind::ExpressionPattern:
+  switch (p->kind()) {
+    case PatternKind::AutoPattern:
```
Comment (geoffromer) [inline explorer/interpreter/type_checker.cpp:4142]: To the extent that `auto` is a pattern at all, I think it's irrefutable. This is a pre-existing problem, so I'm fine with leaving this as-is if it's not easy to fix.

File: explorer/interpreter/type_checker.h [hunk 2]
```diff
@@ -37,6 +37,22 @@ using GlobalMembersMap =
 
 class TypeChecker {
  public:
+  enum class PatternRefutability {
```
Comment (geoffromer) [inline explorer/interpreter/type_checker.h]: I keep tying myself in knots trying to figure out things like whether "refutable" and "irrefutable" are mutually exclusive, and whether there's a superset/subset relationship among the enumerators (this could matter for figuring out whether there might be missing cases in `TypeCheckPattern`), and if so in which direction (which depends if we're thinking of them as sets of _requirements_ or sets of _patterns that have some property_).

To clarify all that, here's my suggestion:
- Document that values of this type represent a set of requirements that `TypeCheckPattern` must impose on the pattern.
- Rename the type `PatternRequirements`.
- Rename `Refutable` to `None` (because it imposes no requirements).
- Rename `BindingType` to `NoBindings`, and document it as a requirement that the pattern not contain binding subpatterns (with a TODO noting that the cases that need this should probably be expressions rather than patterns).

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp:4142]: Can you please clarify, what kind of change are you looking for? We already discussed `auto` as a pattern and I filed #2788 to make it not-a-pattern because it's substantial work. Is this overlapping with #2788?

File: explorer/interpreter/type_checker.h (hunk 2 above)
Comment (jonmeow) [reply explorer/interpreter/type_checker.h]: Done, except for `NoBindings`.

> Rename `BindingType` to `NoBindings`, and document it as a requirement that the pattern not contain binding subpatterns (with a TODO noting that the cases that need this should probably be expressions rather than patterns).

In order to discourage use for other purposes, I prefer the purpose-specific name. I think `NoBindings` sounds more generic. I believe removing the enum value would be the right action, as already reflected by the TODO around #2788.

There is only one use and we're already trying to get rid of it, so I think it's better to be explicit about the intent that this is about #2788, rather than more broadly saying "cases that need this". If more uses are added, I think that's the point where more generic phrasing should be put in to use -- or the additional uses should just be refused, making the refactoring blocking.

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (geoffromer) [reply explorer/interpreter/type_checker.cpp:4142]: The fix I'd hope for would be to delete this line, so that `auto` is handled by the default case, which means it's treated as an irrefutable pattern that doesn't contain a binding. If that doesn't work for some reason, I'm curious to know why, but I don't think it's worth investing much time trying to fix it right now.

**Review by geoffromer — APPROVED** [review]

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp:4142]: Ah, I see now, you're objecting to the fix from #2782: requiring names where we expect bindings.

Here are a few examples of how that would crop up, and associated bugs:

- `fn F(auto)` -- Expects a type instead of a value to be passed in.
  - `F(i32)` is valid.
  - `F(3)` gives: COMPILATION ERROR: test.carbon:6: mismatch in non-deduced types, `i32` is not implicitly convertible to `type`
- `class C(auto)` -- Same as fn
- `for (auto in x)` -- Doesn't use pattern syntax: "SYNTAX ERROR: test.carbon:9: syntax error, unexpected AUTO, expecting identifier"
- `var auto = 3`, `let` similarly
  - Local (statement): valid
  - Global (declaration): Doesn't use pattern syntax, same error as `for`

I think there needs to be a clear decision on whether `auto` should be a pattern, and whether these syntaxes should be supported. For now, I'm going to leave these as disallowed because I think the introduction of `unused` and advice for `_` from #2022 should be interpreted as saying the above should not be treated as valid syntax.

I'll note this discussion on Discord for others to weigh in, since that's where discussion led to #2788.

Comment (geoffromer) [reply explorer/interpreter/type_checker.cpp:4142]: Repeating a clarification from Discord: I agree that the behavior implemented in #2782 (disallowing `fn F(auto)`, etc) is the behavior that we want. I see now that deleting this line would revert that behavior, so I retract the suggestion.
