### PR TITLE
Fix string literal parsing escaped whitespace

### LINKED ISSUE #2132: toolchain string literal parser mishandles trailing \t in multiline string literals
The toolchain string literal parser incorrectly treats

```
var s: String = """
\t
""";
```

as a string with contents `"\n"` instead of as a string with contents `"\t\n"`, because the `\t` gets expanded before whitespace at the end of the line is removed.

### PR DESCRIPTION
**Pull request by clavin**
The toolchain misinterprets escaped whitespace characters as unescaped when trimming trailing whitespace on a line. This PR adds a variable to track the length of the string after escaping the most recent escape, making sure we don't backup past that character, whatever it is.

I did try the approach mentioned in #2132 of not backing up `end_of_regular_text` number of characters, but this caused problems on lines like <kbd>tab</kbd> <kbd>space</kbd> <kbd>tab</kbd> (those characters literally, not escaped) where it would leave the first tab since that is processed in a different iteration of that loop.

P.S. I added a test case for this bug. I kept getting mixed up in the test output which one was the expected value, so I also changed a variable name there for clarity. I hope that's alright. 😊

(Aside: I'm conscious of the fact that this loop that parses the segments in a line has no state currently, but I am adding state to it in this PR. Is that an important property to have in this code? Or am I just thinking too much about it? 😄)

Fixes #2132.

### CODE REVIEW

**Comment by ghost** [comment]
> (Aside: I'm conscious of the fact that this loop that parses the segments in a line has no state currently, but I am adding state to it in this PR. Is that an important property to have in this code? Or am I just thinking too much about it? 😄)

The implementation in place was designed for fast processing. Adding state maybe will cause slow benchmarking tests. This issue appears closable without concern for benchmarking. I'm not a lead. Thanks for the PR.

File: toolchain/lexer/string_literal.cpp [hunk 1]
```diff
@@ -377,10 +382,13 @@ static auto ExpandEscapeSequencesAndRemoveIndent(
...
-        // Trailing whitespace before a newline doesn't contribute to the string
-        // literal value.
+        // Trailing whitespace in the source before a newline doesn't contribute
+        // to the string literal value. However, escaped whitespace (like `\t`)
+        // and any whitespace just before that does contribute.
         while (!result.empty() && result.back() != '\n' &&
-               IsSpace(result.back())) {
+               IsSpace(result.back()) &&
+               (last_escape_length == 0 ||
+                result.length() > last_escape_length + 1)) {
```
Comment (zygoloid) [inline toolchain/lexer/string_literal.cpp]: I think there's an off-by-one error here. For example, given `"""\n\\t \n"""` I think we'll have a `last_escape_length` of `1` after processing the `\t`, and `result.length()` of 2 after skipping past the `' '`, so we won't trim the trailing `' '`. If I'm right, removing the `+ 1` should fix this, and the check for `last_escape_length == 0` then becomes redundant too.
```suggestion
               result.length() > last_escape_length) {
```

**Review by zygoloid — COMMENTED** [review]
Thanks for working on this!

File: toolchain/lexer/string_literal.cpp (hunk 1 above)
Comment (clavin) [reply toolchain/lexer/string_literal.cpp]: Thanks for catching this! You are completely correct. I've incorporated your suggestion & added a test for your example as well. 🙂

**Review by zygoloid — APPROVED** [review]
