### PR TITLE
Explorer: Fuzzer issue around integer overflow

### LINKED ISSUE #2732: Fuzzer issue around integer overflow
### Description of the bug:

This is just integer overflow by multiplication, but other forms might be appropriate to handle similarly, maybe by doing math with APInt then bound-checking for a runtime error.

### What did you do, or what's a simple way to reproduce the bug?

```
package EmptyIdentifier impl;

fn Main() -> i32
{
  return 1000000000 * 1000000000;
}
```

### What did you expect to happen?

Should have a runtime error from Carbon, not the sanitizer.

### What actually happened?

interpreter.cpp:219:69: runtime error: signed integer overflow: 1000000000 * 1000000000 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior interpreter.cpp:219:69 in

### Any other information, logs, or outputs that you want to share?

Case 270183876 for those with access to the current fuzzer reporting.

### PR DESCRIPTION
**Pull request by poorna2152**
Closes #2732

### CODE REVIEW

File: explorer/interpreter/interpreter.cpp [hunk 1]
```diff
@@ -208,23 +209,34 @@ auto Interpreter::EvalPrim(Operator op, Nonnull<const Value*> /*static_type*/,
...
+          if (op1.getSExtValue() == 0) {
+            return ProgramError(source_loc) << "division by zero";
+          }
+          result = op0.sdiv(op1);
+        }
+      }
+      if (result.isSignedIntN(32)) {
+        return arena_->New<IntValue>(result.getSExtValue());
+      } else {
+        return ProgramError(source_loc) << "Integer overflow";
```
Comment (zygoloid) [inline explorer/interpreter/interpreter.cpp]: Explorer error messages generally start with a lowercase letter:
```suggestion
        return ProgramError(source_loc) << "integer overflow";
```

**Review by zygoloid — COMMENTED** [review]
Thank you, this looks great! Just one trivial thing then I think this is good to land.

File: explorer/interpreter/interpreter.cpp (hunk 1 above)
Comment (poorna2152) [reply explorer/interpreter/interpreter.cpp]: Thanks!. updated.

**Review by zygoloid — APPROVED** [review]
