### PR TITLE
Fix: Issue #1394

### LINKED ISSUE #1394: explorer crashes attempting Value -> TupleValue cast
````
// Generated by proto_to_carbon.

package EmptyIdentifier impl;

fn apply[T:! Type, U:! Type](f: T, EmptyIdentifier: U)
{
match (true[true]) {}
}

fn EmptyIdentifier() -> apply(true, true);

fn Main() -> i32 {
  return 0;
}

explorer: external/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = Carbon::TupleValue, From = Carbon::Value]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

### LINKED ISSUE #1395: explorer crashes when using a function with invalid definition for specifying return type of another function
```
package P api;

fn f() {
  var auto = true.g();
}

fn h() -> f() {
}

fn Main() -> i32 {
  return 0;
}

CHECK failure at ./explorer/ast/expression.h:54: static_type_.has_value()
```

### PR DESCRIPTION
**Pull request by pmqtt**
Fix: #1394
Fix: #1395

### CODE REVIEW

**Comment by jonmeow** [comment]
I think in reality we don't really have support for compile-time evaluation of functions, which is what `apply(true, true)` is doing. I'm hesitant to start introducing metaprogramming this way; instead, function calls in return types should probably be rejected because they aren't a type.

**Comment by jonmeow** [comment]
i.e., I think this code should be invalid because it requires metaprogramming in the form of compile-time function calls:

```
fn Foo() -> Type {
  return i32;
}

// The below call to Foo() is the issue.
fn Main() -> Foo() {
  return 0;
}
```

@geoffromer in case I'm mixing up the direction of explorer here.

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -2679,6 +2679,74 @@ auto TypeChecker::TypeCheckTypeExp(Nonnull<Expression*> type_expression,
   return type;
 }
 
+auto TypeChecker::TypeCheckTypeReturnDeclExp(
+    Nonnull<Expression*> type_expression, const ImplScope& impl_scope)
+    -> ErrorOr<Nonnull<const Value*>> {
+  CARBON_RETURN_IF_ERROR(TypeCheckExp(type_expression, impl_scope));
+  Nonnull<const Value*> type;
+  if (type_expression->kind() == ExpressionKind::CallExpression) {
```
Comment (jonmeow) [inline explorer/interpreter/type_checker.cpp]: Note, this special-casing on CallExpression is what concerns me, I think a call to IsType should more be more precise.

This may not address a part of #1394 though if taking that approach; I'm not sure if there's still some issue with `match (true[true])`

Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: Just to explain, the error is not due to match(true[true]). Also the following code causes a crash
```carbon
fn test(){
   "a"["1"];
}
fn foo() -> test();
```
The reason is a bit more subtle:
The method **TypeChecker::TypeCheck(AST& ast) -> ErrorOr<Success> ** first executes DeclareDeclaration for the complete AST. When the declaration **fn foo()->test()** is visited, via DeclareCallable the method **TypeCheckTypeExp** is called for the ReturnType of the callable. Unfortunately this method calls InterpExp before the method body of fn test() has been checked and tries to execute it.
Therefore the new method **TypeCheckTypeReturnDeclExp** has been introduced to not execute the **InterpExp** call under certain conditions.

I hope it is understandable!

Comment (geoffromer) [reply explorer/interpreter/type_checker.cpp]: After this change, what will happen with code like this?

```
fn test() -> i32 {
  "a"["1"];
}
fn foo() -> test();
```

Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: Sorry, I have thought too short! I think it is not possible to handle all X even with the current structure of the explorer. 

```carbon
fn test() -> X //
{
  "a"["1"];
}
fn foo() -> test();
```
The question is now what is the bug, is it the declaration **fn foo() -> test();**  or that "a"["1"] is not caught and crashed?

Comment (geoffromer) [reply explorer/interpreter/type_checker.cpp]: I think for now we should disallow any return type expression that involves a function call, regardless of whether the function type-checks. We'll need to revisit that rule when we start adding metaprogramming support, but at that point we'll presumably have a metaprogramming design to guide us on how to handle cases like this.

Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp]: I think `-> test()` is the issue. Again, we haven't really discussed metaprogramming -- I'm going to say no metaprogramming for now.

I suspect we don't have any tests checking the behavior right now of whether `fn foo() -> test()` is working, but if we do it should be fine to switch them to disallow it.

Note, while this example may seem to work okay, I'm suggesting we shouldn't embark on it this way because metaprogramming quickly becomes complex. For a few examples:

Simple indirection:

```
fn test() -> Type {
  return ();
}

fn Main() -> test() {
  return 0;
}
```

Globals:

```
var x: Type = i32;

fn test() -> Type {
  // This should probably be invalid because of referencing a non-local variable.
  // But similar with `let` would probably be okay, right?
  return x;
}

fn Main() -> test() {
  return 0;
}
```

More indirection:

```
fn test1() -> Type {
  return i32;
}

fn test2() -> Type {
  return test1();
}

fn Main() -> test2() {
  return 0;
}
```

Random compilation (would this be allowed? it's non-deterministic):

```
fn test() -> Type {
  if (Rand()) {
    return ();
  } else {
    return i32;
  }
}

fn Main() -> test() {
  return 0;
}
```

Printing during compilation (would this be allowed? it's non-deterministic too, since printing is an external API call):

```
fn test() -> Type {
  Print("blah");
  return i32;
}

fn Main() -> test() {
  return 0;
}
```

Adding metaprogramming really requires more comprehensive design and testing, and I think we shouldn't enter into it here. Compile-time function calling is one metaprogramming approach, and while we may allow it in some manner, we may want something closer to the `constexpr` boundaries that C++ has. Providing something without that boundary doesn't seem worth the cost of sorting through the issues it creates.

Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: Ok! I think however the bug should be quite difficult to eliminate, I am just not sure whether InterpExp must not be called. Unfortunately 
**fn t() -> Foo(i32){}** is not so easy to distinguish from **fn t -> print(X)**... But I will try it!

Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp]: I haven't thought about the fix too much, but the answer is probably in constraining expressions that InterpExp would evaluate.

Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: From testdata/instantiation_at_compile_time.carbon
```carbon
package ExplorerTest api;

class C(T:! Type) {}

fn F(T:! Type) -> Type {
  return C(T);
}

fn Main() -> i32 {
  var v: F(i32) = {};
  var w: C(i32) = v;
  return 0;
}
```
should this code valid after my fix? If so, I think we have a logic problem!

Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp]: No, it should not -- `F(i32)` is also compile-time metaprogramming. I think that test can be changed to a fail test, where `var v: F(i32)` is invalid.

File: explorer/interpreter/interpreter.cpp [hunk 2]
```diff
@@ -788,6 +788,10 @@ auto Interpreter::CallFunction(const CallExpression& call,
           alt.alt_name(), alt.choice_name(), arg));
     }
     case Value::Kind::FunctionValue: {
+      if (phase() == Phase::CompileTime) {
+        return ProgramError(call.source_loc())
+               << " function call not allowed here";
```
Comment (geoffromer) [inline explorer/interpreter/interpreter.cpp]:
```suggestion
               << " function call not allowed in this context";
```

**Review by geoffromer — COMMENTED** [review]
Looks good to me. Just one suggestion to make the error a little clearer.

File: explorer/interpreter/interpreter.cpp (hunk 2 above)
Comment (geoffromer) [reply explorer/interpreter/interpreter.cpp]: I assume the tests will need to be updated to match this.

Comment (pmqtt) [reply explorer/interpreter/interpreter.cpp]: oh sorry! I forgot!

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (pmqtt) [reply explorer/interpreter/type_checker.cpp]: Thanks!

File: explorer/interpreter/interpreter.cpp [hunk 3]
```diff
@@ -788,6 +788,10 @@ auto Interpreter::CallFunction(const CallExpression& call,
           alt.alt_name(), alt.choice_name(), arg));
     }
     case Value::Kind::FunctionValue: {
+      if (phase() == Phase::CompileTime) {
+        return ProgramError(call.source_loc())
+               << " function call not allowed in this context";
```
Comment (jonmeow) [inline explorer/interpreter/interpreter.cpp]:
```suggestion
               << "Function would be called at compile-time";
```

Prefix space shouldn't be there (note how it results in a double space in error messages)

And I think we can actually be more specific here; "in this context" seems ambiguous to me.

**Review by jonmeow — COMMENTED** [review]
Looking at these tests, I think it'd be good to clean them up with respect to the behavior change. I'd suggest not creating a 'crash' directory because we typically group tests by features, and "crash" is very encompassing. Also note, we aren't using dashes in filenames.

To go through files:

- explorer/testdata/assoc_const/fail_unknown_value.carbon
  - Remove, it's failing because the type is a function. There is no associated constant being tested here.
- explorer/testdata/assoc_const/fail_unknown_value_specified_in_constraint.carbon
   - Remove, same reason.
- explorer/testdata/crash/issue-1394.carbon
   - Rename to function/fail_return_type_is_call.carbon
   - We generally use naming around the feature being tested (such as "function" or "generic_class"), not the error being prevented ("crash").
- explorer/testdata/crash/issue-1394_function_call_as_var_type.carbon
  - Rename to function/fail_var_type_is_call.carbon
- explorer/testdata/function/auto_return/fail_modify_arg_type.carbon
  - Rename to function/fail_param_type_is_call.carbon
  - Note this no longer offers a significant test of `auto`, it'd probably be good to just change that to `Type`
- explorer/testdata/function/auto_return/fail_modify_return_type.carbon
  - Remove, it's testing the same thing as explorer/testdata/crash/issue-1394.carbon
- explorer/testdata/function/auto_return/fail_type.carbon
  - Remove, it's testing the same thing as issue-1394_function_call_as_var_type.carbon
- explorer/testdata/generic_class/fail_instantiation_at_compile_time.carbon
  - Remove, it's testing the same thing as issue-1394_function_call_as_var_type.carbon
- explorer/testdata/generic_class/fail_use_at_compile_time.carbon
  - Keep, since it's checking with generics
- explorer/testdata/generic_function/fail_call_at_compile_time.carbon
  - Keep, since it's checking with generics
- explorer/testdata/member_access/fail_evaluate_type_before_dot.carbon
  - Remove, it's testing the same thing as issue-1394_function_call_as_var_type.carbon
  - This test is actually the one that caught my eye the most because it _was_ testing several things, all of which no longer work.

So I'm suggesting only keeping five tests:

- function/fail_return_type_is_call.carbon
- function/fail_var_type_is_call.carbon
- function/fail_param_type_is_call.carbon
- generic_class/fail_use_at_compile_time.carbon
- generic_function/fail_call_at_compile_time.carbon

Does that seem reasonable? It does delete a fair bit of test code, but I'm probably more hesitant to keep tests around that aren't providing distinct behavior (and, in some cases, have a lot of code which might imply there's something more distinct happening)

**Review by jonmeow — APPROVED** [review]
