### PR TITLE
Start handling stack depth issues in explorer

### LINKED ISSUE #2795: Handle highly nested scopes
### Description of the bug:

If there are a bunch of nested scopes, ResolveNames hits a stack overflow.

This is probably a general problem in the explorer. Rather than trying to address this in ResolveNames, it may be better to do something like trying to limit the depth of the AST. But the ResolveNames approach may be sufficient -- it'd require checking code once ResolveNames is "fixed" to see if there are other situations that have similar results.

Note, while the toolchain has gone non-recursive by maintaining its own stack, I don't think that's an approach we want to adopt on the interpreter side. But there may be other techniques that would be appropriate here.

### What did you do, or what's a simple way to reproduce the bug?

Generate a file which contains:

`if true then ... else 0` nested a few hundred times.

### What did you expect to happen?

An error from #2793

### What actually happened?

Crashes in ResolveNames recursion.

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by jonmeow**
Adds stack space handling similar to Clang's approach, but with more support for forwarding return values. Refactors ParseAndExecute for better sharing, and for centralization of the InitStackSpace handling.

Fixes #2795

### CODE REVIEW

File: explorer/interpreter/resolve_names.cpp [hunk 1]
```diff
@@ -109,6 +136,12 @@ class NameResolver {
 
 }  // namespace
 
+// Encapsulates checking the stack and erroring if needed. This should be called
+// at the start of recursive functions.
+#define CARBON_RETURN_IF_STACK_LIMITED(loc) \
```
Comment (geoffromer) [inline explorer/interpreter/resolve_names.cpp]: It seems problematic that if we have trouble with stack overflow in other places (`TypeChecker` seems like a plausible suspect) we'll need to duplicate all this machinery, presumably with a different macro name.

Here's an alternative approach to consider: we could add an `int stack_depth` parameter to every function that we're worried could be involved in a stack overflow, and define a function `IncrementAndCheckStackDepth(int& depth, SourceLocation loc)` that behaves like `VerifyUnderLimit`, but also increments `depth`. We don't have to worry about decrementing it, because it's passed by value. We could also wrap `stack_depth` in a class that just provides an `IncrementAndCheckStackDepth` method, for better encapsulation etc.

This would mean we can use the same mechanism everywhere, and we don't need to use a macro at all. The main downside, of course, is that we have to add an extra parameter to a lot of functions.

Alternatively, somewhere near the start of the program we could store the stack pointer in a global variable, and then define a `CheckStackSize` free function that compares the current stack pointer to the global variable. This approach is conceptually gross, but it's fully general (within the call tree where we wrote to the global variable), and doesn't require any changes to the application logic other than adding the checks. It measures stack size rather than stack depth, but that seems like it should be close enough for these purposes. 

What do you think?

File: explorer/interpreter/resolve_names.cpp [hunk 2]
```diff
@@ -95,11 +95,38 @@ class NameResolver {
...
+   public:
+    explicit ScopedStackStep(NameResolver* parent) : parent_(parent) {
+      ++parent_->stack_depth_;
+    }
+    ~ScopedStackStep() { --parent_->stack_depth_; }
+
+    auto VerifyUnderLimit(SourceLocation loc) -> ErrorOr<Success> {
+      if (parent_->stack_depth_ >= StackDepthLimit) {
+        return ProgramError(loc)
+               << "Exceeded recursion limit (" << StackDepthLimit << ")";
```
Comment (zygoloid) [inline explorer/interpreter/resolve_names.cpp]: Most explorer diagnostics start with a lowercase letter.

File: explorer/parse_and_execute_test.cpp [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    AddPrelude("explorer/data/prelude.carbon", &arena, &ast.declarations,
+               &ast.num_prelude_declarations);
+    TraceStream trace_stream;
+
+    // Use llvm::nulls() to suppress output from the Print intrinsic.
+    CARBON_ASSIGN_OR_RETURN(
+        ast, AnalyzeProgram(&arena, ast, &trace_stream, &llvm::nulls()));
+    return ExecProgram(&arena, ast, &trace_stream, &llvm::nulls());
+  }
+};
```
Comment (zygoloid) [inline explorer/parse_and_execute_test.cpp]: This unit test will add some maintenance overhead for future refactorings of explorer internals; it might be cheaper for overall maintenance to either check in a script to generate the test below or just create and check in the ~2000-line test as a normal FileCheck test. But I don't feel strongly about this. Feel free to land this either way.

**Review by zygoloid — DISMISSED** [review]

File: explorer/interpreter/resolve_names.cpp (hunk 1 above)
Comment (zygoloid) [reply explorer/interpreter/resolve_names.cpp]: Clang uses the "compare the stack pointer" approach, and even has a fallback path that "allocates new stack space" (spawns a thread for the rest of the computation). It's pretty messy, but it works, even in the presence of one recursive function calling into another one.

Another approach that perhaps we should consider would be to put a depth limit into the initial AST construction in the parser, and then only add explicit depth limits in places where we do recursion on something other than the structure of the AST (eg, template instantiation and impl selection).

File: explorer/parse_and_execute_test.cpp (hunk 3 above)
Comment (jonmeow) [reply explorer/parse_and_execute_test.cpp]: Regarding maintenance, this is close to what the fuzzer does (and I've refactored towards this), so the main _new_ overhead would be for changing the error message. The flipside though is that it's much easier to identify/modify the depth of the test with it in code like this (and I have, to nudge at more stack issues).

Also, Git has scaling issues with large files so I'm reticent to follow a design pattern which relies on large files to reproduce issues, and we should expect more similar recursion tests. I'm already hesitant about the fuzzer corpus causing repo scaling issues.

File: explorer/interpreter/resolve_names.cpp (hunk 2 above)
Comment (jonmeow) [reply explorer/interpreter/resolve_names.cpp]: Done

File: explorer/interpreter/resolve_names.cpp (hunk 1 above)
Comment (jonmeow) [reply explorer/interpreter/resolve_names.cpp]: I've gone with something closer to the Clang approach, which should scale out more. This is a little more work, but sounds like it's more desirable.

I think a depth limit on the AST would require more changes to handle it. To the extent that we already have Clone, and there's the request to add debugging printing of the AST, adding some more generic form of recursion that could handle both of those use-cases plus a depth examination may be best. But I'm trying to avoid that right now. :)

**Review by jonmeow — COMMENTED** [review]
Revamped the change.

File: explorer/parse_and_execute_test.cpp (hunk 3 above)
Comment (jonmeow) [reply explorer/parse_and_execute_test.cpp]: Went a step further and also merged in main.cpp logic, so now everything's more uniform.

**Comment by jonmeow** [comment]
Just to note -- I've made a couple small changes to this PR in anticipation of the test refactoring discussing on #infra. I'm hoping to reduce merge conflicts pending review.

File: explorer/fuzzing/ast_to_proto.cpp [hunk 4]
```diff
@@ -10,7 +10,7 @@
 #include "explorer/ast/expression.h"
 #include "llvm/Support/Casting.h"
 
-namespace Carbon {
+namespace Carbon::Testing {
```
Comment (geoffromer) [inline explorer/fuzzing/ast_to_proto.cpp]: The changes in this file, and a few other files with similar changes, seem unrelated to the topic of this PR. Are these the changes to avoid merge conflicts you alluded to?

File: explorer/interpreter/stack_space.h [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+
+#ifndef CARBON_EXPLORER_INTERPRETER_STACK_SPACE_H_
+#define CARBON_EXPLORER_INTERPRETER_STACK_SPACE_H_
+
+#include <functional>
+#include <optional>
+
+namespace Carbon {
+
+namespace Internal {
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h:14]: Rather than having an `Internal` namespace, I suggest adding an `// Implementation details only below here` comment, basically demarcating the boundary where we'd split the .h and .cc files if C++ didn't make us put the template code in this header. That way the first thing the reader sees is the public API.

File: explorer/interpreter/stack_space.h [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+auto IsStackSpaceNearlyExhausted() -> bool;
+
+// Starts a thread to run the function.
+auto RunWithStackSpaceHelper(std::function<void()> fn) -> void;
+
+}  // namespace Internal
+
+// Starts a new thread with initialized stack space. This should be called
+// before RunWithStackSpace so that execution is occurring with known stack
+// space.
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: This makes it sound like this function doesn't actually run `fn`, it just somehow prepares for the `RunWithStackSpace` call that actually will run `fn`. But judging from the function body, this actually does run `fn`. But if that's the case, the name and comment seem misleading, and I don't understand how to choose between this function and `RunWithStackSpace`

File: explorer/interpreter/stack_space.h [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+//         <function body>
+//       });
+template <typename ReturnType>
+auto InitStackSpace(std::function<ReturnType()> fn) -> ReturnType {
+  std::optional<ReturnType> result;
+  Internal::RunWithStackSpaceHelper([&] { result = fn(); });
+  return std::move(*result);
+}
+
+// Runs a function. May start a thread if more stack space is desirable.
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: I thought our goal here was to detect when the Carbon program is consuming too many resources, so that we don't waste too much time when the fuzzer discovers how to create an infinite loop in the Carbon code. This seems like it's doing the opposite, enabling us to spend more resources in those cases. Have I misunderstood the intent?

File: explorer/interpreter/stack_space.h [hunk 8]
```diff
@@ -0,0 +1,57 @@
+// Part of the Carbon Language project, under the Apache License v2.0 with LLVM
+// Exceptions. See /LICENSE for license information.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#ifndef CARBON_EXPLORER_INTERPRETER_STACK_SPACE_H_
+#define CARBON_EXPLORER_INTERPRETER_STACK_SPACE_H_
+
+#include <functional>
```
Comment (zygoloid) [inline explorer/interpreter/stack_space.h]: Can you use `llvm::function_ref` instead?

File: explorer/interpreter/resolve_names.cpp [hunk 9]
```diff
@@ -259,377 +260,404 @@ auto NameResolver::AddExposedNames(const Declaration& declaration,
...
-      for (FieldInitializer& init :
-           cast<StructTypeLiteral>(expression).fields()) {
-        CARBON_RETURN_IF_ERROR(
-            ResolveNames(init.expression(), enclosing_scope));
-        if (!member_names.insert(init.name()).second) {
-          return ProgramError(init.expression().source_loc())
-                 << "Duplicate name `" << init.name()
-                 << "` in struct type literal";
+  return RunWithStackSpace<ErrorOr<std::optional<ValueNodeView>>>(
+      [&]() -> ErrorOr<std::optional<ValueNodeView>> {
```
Comment (geoffromer) [inline explorer/interpreter/resolve_names.cpp]: In the cases where you're inserting a lambda in this PR, are you intending to make any non-whitespace changes inside the lambda body?

File: explorer/interpreter/type_checker.cpp [hunk 10]
```diff
@@ -2689,1319 +2690,1347 @@ auto TypeChecker::CheckAddrMeAccess(
 auto TypeChecker::TypeCheckExp(Nonnull<Expression*> e,
                                const ImplScope& impl_scope)
     -> ErrorOr<Success> {
-  if (trace_stream_->is_enabled()) {
-    *trace_stream_ << "checking " << e->kind() << " " << *e;
-    *trace_stream_ << "\n";
-  }
-  if (e->is_type_checked()) {
+  return RunWithStackSpace<ErrorOr<Success>>([&]() -> ErrorOr<Success> {
```
Comment (zygoloid) [inline explorer/interpreter/type_checker.cpp]: It'd be nice to avoid this extra indentation. I think it's worth adding an extra `Impl` function to keep the indentation down.

File: explorer/parse_and_execute/parse_and_execute.cpp [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+#include "explorer/interpreter/stack_space.h"
+#include "explorer/syntax/parse.h"
+#include "explorer/syntax/prelude.h"
+#include "llvm/ADT/ScopeExit.h"
+
+namespace Carbon {
+
+// Returns a scope exit function for printing the timing of a step on scope
+// exit. Note the use prints step timings in reverse order.
+static auto PrintTimingOnExit(TraceStream* trace_stream, const char* label,
```
Comment (geoffromer) [inline explorer/parse_and_execute/parse_and_execute.cpp]: Here again, this seems pretty unrelated to the topic of the PR. Did you intend to include it, or did a merge go awry or something? If it's intentional, it should probably be mentioned in the PR description.

File: explorer/fuzzing/ast_to_proto.cpp (hunk 4 above)
Comment (jonmeow) [reply explorer/fuzzing/ast_to_proto.cpp]: In part -- they stem from addressing zygoloid's concern regarding ParseAndExecute refactoring: https://github.com/carbon-language/carbon-lang/pull/2799#discussion_r1177073161

As I was refactoring fuzzing's Carbon::ParseAndExecute to ParseAndExecuteProto, it seemed best to move it to the Testing workspace since it is expressly such (due to the proto dependency, I would not expect it to ever be non-testing), and can be disambiguated from the non-testing ParseAndExecute calls that way. Then I also have to fix calls, which led to me moving parts of this into the Testing namespace, which made me think the rest should be too.

Anyways, noted in the PR description.

File: explorer/parse_and_execute/parse_and_execute.cpp (hunk 11 above)
Comment (jonmeow) [reply explorer/parse_and_execute/parse_and_execute.cpp]: Added a note to the PR description explaining that ParseAndExecute was refactored.

File: explorer/interpreter/stack_space.h (hunk 5 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h:14]: I want to take advantage of the `Internal` namespace to reduce accidental misuse; the namespace should make it clear at call-sites, whereas comments are only visible if someone looks at the API (and "below" implies a contextual requirement when reading, which can be missed).

We use Internal namespaces similarly in [several places](https://github.com/search?q=repo%3Acarbon-language%2Fcarbon-lang+lang%3Ac%2B%2B+%2Fnamespace%5Cs.*Internal%2F&type=code) within Carbon, so I believe this is consistent.

File: explorer/interpreter/stack_space.h (hunk 7 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Per the discussion at https://github.com/carbon-language/carbon-lang/pull/2799#discussion_r1177048190, zygoloid's first comment was to consider Clang's approach. If my response there (specifically, that Clang's approach seems to be more scalable, as well as the follow-up comments comparing approaches that I've made given your question here) doesn't address your question, please follow up there so that we can keep discussion about approaches in one place.

File: explorer/interpreter/resolve_names.cpp (hunk 9 above)
Comment (jonmeow) [reply explorer/interpreter/resolve_names.cpp]: No, but zygoloid is having me redo this so the whitespace changes should vanish. 🤷

File: explorer/interpreter/stack_space.h (hunk 8 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Done

File: explorer/interpreter/resolve_names.cpp (hunk 1 above)
Comment (jonmeow) [reply explorer/interpreter/resolve_names.cpp]: Let me talk a little more here about the trade-offs, given @geoffromer's comment https://github.com/carbon-language/carbon-lang/pull/2799#discussion_r1181788134.

First, a stack depth tracker in ResolveNames does not mean that the _same_ AST in another place (e.g., type checking) could not also blow out the stack. There are a couple reasons for this:

1) ResolveNames can consume more stack than AST depth through intermediate function calls, as it does with member names.
2) Other functions may consume stack space beyond the AST depth, e.g. with Substitute in generics.

So first and foremost, I would posit any limitation based on AST depth is a _heuristic_. It would help, but other parts of the code would still need to be fixed.

The current approach is easy to inject into functions without significantly changing call-sites, and more significantly addresses the recursion problem by assigning a known stack space. I choice this mainly based on @zygoloid's comment, first paragraph ("It's pretty messy, but it works"). What I'm doing here is at least _similar_ to Clang's approach. There are a couple more factors to consider:

- Do we want to be able to take production code and run it through the interpreter, or treat the explorer's ParseAndExecute as an API? A limit on AST depth that keeps within the default stack size will impose some strict limits on such uses.

- Does an AST depth limit prevent a stack overflow within ResolveNames? ResolveNames can already do a couple function calls per AST depth, so making this approach work would require either constraining ResolveNames implementation to minimize use of helper functions in recursion or limiting the AST depth based on however many we decide to insert in the future, overall constraining the explorer architecture.

I'm not saying that a depth limit on the AST is bad, but it may not address the stack limit issue in the way you expect, and might be long-term undesirable.

geoffromer:

> Here's an alternative approach to consider: we could add an `int stack_depth` parameter to every function that we're worried could be involved in a stack overflow, and define a function `IncrementAndCheckStackDepth(int& depth, SourceLocation loc)` that behaves like `VerifyUnderLimit`, but also increments `depth`. We don't have to worry about decrementing it, because it's passed by value. We could also wrap `stack_depth` in a class that just provides an `IncrementAndCheckStackDepth` method, for better encapsulation etc.
> 
> This would mean we can use the same mechanism everywhere, and we don't need to use a macro at all. The main downside, of course, is that we have to add an extra parameter to a lot of functions.

This approach would require modifying most functions in the interpreter (not just name resolution). Type checking can have similar issues as name resolution, demonstrated with TypeCheckExp. As a consequence, I believe anything that requires passing parameters creates undesirable amounts of development overhead.

geoffromer:

> Alternatively, somewhere near the start of the program we could store the stack pointer in a global variable, and then define a `CheckStackSize` free function that compares the current stack pointer to the global variable. This approach is conceptually gross, but it's fully general (within the call tree where we wrote to the global variable), and doesn't require any changes to the application logic other than adding the checks. It measures stack size rather than stack depth, but that seems like it should be close enough for these purposes.

The current approach does something similar. The Init stores a stack pointer and sets a known stack size. The Run checks against it.

The only difference is in outcome: earlier code might have errored, while this code does not. From my perspective, this mainly a question of "do we want to do best effort handling of depth". I think the answer leans towards yes if it's not too high cost, otherwise the limits can seem arbitrary. Additionally, there are probably going to be more code structures rendered invalid by the stack limit, and it reduces the ability in the future to take production code and test in the explorer.

zygoloid:

> Clang uses the "compare the stack pointer" approach, and even has a fallback path that "allocates new stack space" (spawns a thread for the rest of the computation). It's pretty messy, but it works, even in the presence of one recursive function calling into another one.

This is now done, as noted above.

zygoloid:

> Another approach that perhaps we should consider would be to put a depth limit into the initial AST construction in the parser, and then only add explicit depth limits in places where we do recursion on something other than the structure of the AST (eg, template instantiation and impl selection).

This influenced the current approach -- Init is called when the AST is being constructed, Run can be called when recursion explicitly occurrs.

---

If this still doesn't make sense to either of you, maybe we can use one of the meetings to discuss trade-offs.

File: explorer/interpreter/stack_space.h (hunk 6 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: I've tried to adjust the comments to make this clearer: Init is used first because it's initialization, and mechanically it's necessary in order to know how much stack space remains.

File: explorer/interpreter/stack_space.h (hunk 8 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Done.

File: explorer/interpreter/type_checker.cpp (hunk 10 above)
Comment (jonmeow) [reply explorer/interpreter/type_checker.cpp]: Done.

File: explorer/interpreter/stack_space.h (hunk 5 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h:14]: I should add -- your suggestion would also require forward declarations for the template functions. I think separating declaration and definition is significant overhead for these short functions, and this header is pretty short to just skim through.

File: explorer/interpreter/exec_program.cpp [hunk 12]
```diff
@@ -21,57 +22,61 @@ namespace Carbon {
 auto AnalyzeProgram(Nonnull<Arena*> arena, AST ast,
                     Nonnull<TraceStream*> trace_stream,
                     Nonnull<llvm::raw_ostream*> print_stream) -> ErrorOr<AST> {
-  if (trace_stream->is_enabled()) {
-    *trace_stream << "********** source program **********\n";
-    for (int i = ast.num_prelude_declarations;
-         i < static_cast<int>(ast.declarations.size()); ++i) {
-      *trace_stream << *ast.declarations[i];
+  return RunWithStackSpace<ErrorOr<AST>>([&]() -> ErrorOr<AST> {
```
Comment (geoffromer) [inline explorer/interpreter/exec_program.cpp]: Here, too, should we split out an `Impl` function to avoid the whitespace changes?

File: explorer/interpreter/stack_space.h [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+// Initializes stack space information for RunWithStackSpace by creating a new
+// thread, and runs the function on the new thread. This only needs to be called
+// once within a given recursion.
+//
+// Usage:
+//   return InitStackSpace<ReturnType>([&]() -> ReturnType {
+//         <function body>
+//       });
+template <typename ReturnType>
+auto InitStackSpace(llvm::function_ref<ReturnType()> fn) -> ReturnType {
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: I suggest calling this something like `RunWithNewStack`, to emphasize the fact that this actually does run `fn`.

File: explorer/interpreter/stack_space.h [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+  std::optional<ReturnType> result;
+  Internal::RunWithStackSpaceHelper([&] { result = fn(); });
+  return std::move(*result);
+}
+
+// Runs a function. May start a new thread for the function if too much stack
+// space has been consumed since the last time a thread was spawned (by either
+// InitStackSpace or RunWithStackSpace). Require InitStackSpace be used first
+// within the recursion.
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: Could we drop this requirement by having this function behave like `InitStackSpace` if `bottom_of_stack == 0`? That way we wouldn't need two separate functions.

File: explorer/parse_and_execute/parse_and_execute.cpp [hunk 15]
```diff
@@ -0,0 +1,96 @@
...
+                           .count()
+                    << "ms\n";
+    }
+  });
+}
+
+static auto ParseAndExecuteHelper(std::function<ErrorOr<AST>(Arena*)> parse,
+                                  const std::string& prelude_path,
+                                  TraceStream* trace_stream) -> ErrorOr<int> {
+  return InitStackSpace<ErrorOr<int>>([&]() -> ErrorOr<int> {
```
Comment (geoffromer) [inline explorer/parse_and_execute/parse_and_execute.cpp]: Might it be cleaner to move the lambda wrapping to the callsites?

File: explorer/interpreter/stack_space.h (hunk 14 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: The current approach is helpful to prevent programming errors, which would otherwise be subtle and difficult to catch.

For example, if we weren't doing this validation, what you could end up with is someone calling type checking without hitting RunWithStackSpace first, and as a consequence getting one thread per TypeCheckExp call. That would technically work, but it would also be slower than intended and it's hard to catch when excess threads are being created (I had a bug creating too many threads while implementing, so I'm perhaps extra cautious on this).

This approach addresses that by making it an error with a clear fix, calling InitStackSpace first. It pushes callers towards supported entry points.

File: explorer/interpreter/exec_program.cpp (hunk 12 above)
Comment (jonmeow) [reply explorer/interpreter/exec_program.cpp]: Removing RunWithStackSpace from this file since ParseAndExecute is handling it. I think I'd added this early in implementation when I was still hashing out the approach.

File: explorer/parse_and_execute/parse_and_execute.cpp (hunk 15 above)
Comment (jonmeow) [reply explorer/parse_and_execute/parse_and_execute.cpp]: If it's not a strong preference for you, I'd like to keep it here. Moving it to callsites would mean copy-pasting it in two places, and it seems natural to me to use the shared helper to reduce boilerplate.

Alternately, I could do an `Impl` split -- let me know if you'd prefer that.

File: explorer/interpreter/stack_space.h (hunk 13 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: This made me think about the names a bit more -- how about ReserveStackAndRun versus ReserveStackIfExhaustedAndRun? I was thinking that's more explicit about what they do different, and the "AndRun" emphasizes the ordering a little more.

Also, this makes me feel less awkward about sharing implementation a little more.

**Comment by jonmeow** [comment]
Noticed I'd accidentally removed the llvm::nulls() use in #2784 (fixed now), mainly because I'm trying to redirect output as I restructure tests and realized I didn't have a way to redirect anymore. :)

File: explorer/parse_and_execute/parse_and_execute.cpp (hunk 15 above)
Comment (geoffromer) [reply explorer/parse_and_execute/parse_and_execute.cpp]: I think having both a `Helper` and an `Impl` would be too much, so if you don't want to duplicate the lambda boilerplate, it's probably best to leave it as is.

File: explorer/interpreter/stack_space.h (hunk 14 above)
Comment (geoffromer) [reply explorer/interpreter/stack_space.h]: Those bugs seem like they will be very rare -- they would only come up when you're calling this function from an an inner loop that's not nested inside the `ParseFileAndExecute` call that wraps nearly the entire program. If so, and given the fact that they're performance bugs rather than correctness bugs, I'm not convinced that preventing them is worth complicating this API by having two subtly-different functions that callers need to choose between.

Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: So, the best I can say here is that I feel defensive coding is appropriate here based on my own experiences of hitting these bugs. Note, performance can be severely impacted if too many threads are started, to the extent that it becomes a correctness issue, just not one that crashes in a typical manner.

I don't know how to convince you that this is worth a separate function. Maybe it'd be good to get a separate opinion here?

File: explorer/parse_and_execute/parse_and_execute.cpp (hunk 15 above)
Comment (jonmeow) [reply explorer/parse_and_execute/parse_and_execute.cpp]: SGTM, leaving as is.

File: explorer/interpreter/stack_space.h (hunk 14 above)
Comment (geoffromer) [reply explorer/interpreter/stack_space.h]: Yes, I think a second opinion is probably the best way to unblock this.

Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Noting that other potential voices are now on vacation, I've made your requested change. I may follow up separately. Can you please take another look?

File: explorer/interpreter/stack_space.h [hunk 16]
```diff
@@ -17,39 +17,24 @@ namespace Internal {
...
+// spawns a new thread when it didn't create the current thread.
 //
 // Usage:
-//   return RunWithStackSpace<ReturnType>([&]() -> ReturnType {
+//   return ReserveStackIfExhaustedAndRun<ReturnType>([&]() -> ReturnType {
 //         <function body>
 //       });
 template <typename ReturnType>
-auto RunWithStackSpace(llvm::function_ref<ReturnType()> fn) -> ReturnType {
+auto ReserveStackIfExhaustedAndRun(llvm::function_ref<ReturnType()> fn)
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: This name is pretty verbose, and leaks implementation details in a way that I think doesn't help readability. How about something like `RunWithExtraStack`?

File: explorer/interpreter/stack_space.h [hunk 17]
```diff
@@ -17,39 +17,24 @@ namespace Internal {
...
-  Internal::RunWithStackSpaceHelper([&] { result = fn(); });
-  return std::move(*result);
-}
-
 // Runs a function. May start a new thread for the function if too much stack
-// space has been consumed since the last time a thread was spawned (by either
-// InitStackSpace or RunWithStackSpace). Require InitStackSpace be used first
-// within the recursion.
+// space has been consumed since the last time a thread was spawned. Always
+// spawns a new thread when it didn't create the current thread.
```
Comment (geoffromer) [inline explorer/interpreter/stack_space.h]: How about something like this instead?

> Runs `fn` after ensuring there is a reasonable amount of space left on the stack for it to run in. This may run `fn` in a separate thread if there is not enough space left on the current stack.

File: explorer/interpreter/stack_space.h (hunk 16 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Done. This is different from what you'd requested at https://github.com/carbon-language/carbon-lang/pull/2799#discussion_r1182960089, but I'm assuming you prefer your new name.

File: explorer/interpreter/stack_space.h (hunk 17 above)
Comment (jonmeow) [reply explorer/interpreter/stack_space.h]: Done, with the note about the current thread (because the current thread may have enough space, but with no ability to verify that)

File: explorer/interpreter/stack_space.h (hunk 16 above)
Comment (geoffromer) [reply explorer/interpreter/stack_space.h]: Yeah, `RunWithNewStack` doesn't work here because this function doesn't necessarily create a new stack.

**Review by geoffromer — APPROVED** [review]
