### PR TITLE
fix alias resolved_declaration error

### LINKED ISSUE #2794: Alias resolved_declaration error
### Description of the bug:

Looks like the set_resolved_declaration code from #2720 has a crash. I was looking at this for #2792, seeing if there were edge cases to handle.

FYI @Maan2003 

### What did you do, or what's a simple way to reproduce the bug?

```
package ExplorerTest api;

class A {
  class B {}
  alias C = B;
}

fn Main() -> i32 {
  return 0;
}
```

### What did you expect to happen?

Error or nothing (i.e., successful compile).

### What actually happened?

```
CHECK failure at ./explorer/ast/declaration.h:1022: !resolved_declaration_.has_value()
```

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by maan2003**
Closes #2794

### CODE REVIEW

File: explorer/interpreter/resolve_names.cpp [hunk 1]
```diff
@@ -855,7 +855,9 @@ auto NameResolver::ResolveNames(Declaration& declaration,
       scope->MarkDeclared(alias.name().inner_name());
       CARBON_ASSIGN_OR_RETURN(auto target,
                               ResolveNames(alias.target(), *scope));
-      if (target && isa<Declaration>(target->base())) {
+      // Skip if declaration is already resolved in previous name resolution phase.
+      if (target && isa<Declaration>(target->base()) &&
+          !alias.resolved_declaration()) {
```
Comment (Maan2003) [inline explorer/interpreter/resolve_names.cpp:860]: this feels hacky, is there any other way to guard this from multiple phases?

File: explorer/interpreter/resolve_names.cpp [hunk 2]
```diff
@@ -855,7 +855,10 @@ auto NameResolver::ResolveNames(Declaration& declaration,
       scope->MarkDeclared(alias.name().inner_name());
       CARBON_ASSIGN_OR_RETURN(auto target,
                               ResolveNames(alias.target(), *scope));
-      if (target && isa<Declaration>(target->base())) {
+      // Skip if declaration is already resolved in previous name resolution
+      // phase.
+      if (target && isa<Declaration>(target->base()) &&
+          !alias.resolved_declaration()) {
         alias.set_resolved_declaration(&cast<Declaration>(target->base()));
       }
```
Comment (jonmeow) [inline explorer/interpreter/resolve_names.cpp]:
```suggestion
      if (target && isa<Declaration>(target->base())) {
        if (alias.resolved_declaration()) {
          // Skip if the declaration is already resolved in a previous name resolution
          // phase.
          CARBON_CHECK(*alias.resolved_declaration() == target->base());
        } else {
          alias.set_resolved_declaration(&cast<Declaration>(target->base()));
        }
      }
```

I think this is probably about as good as it gets, though maybe worth verifying the resolution doesn't change?

The problem I see is that the multiple passes seem to be for function resolution, to resolve the body after the signature. In a way, that's the hacky part (the specific bodies could instead be reserved for later resolution, instead of re-resolving through the tree).

Aliases in classes must be resolved in the first pass, because a function signature may refer to them. Aliases outside of classes must be resolved in later passes, because aliases aren't only in classes. In theory the entire pass setup could be re-thought with this in mind, because scope information could be cached and name resolution could _only_ resolve function bodies, but given the current approach I don't think you're getting much better.

My suggestion is only to verify that the result hasn't changed, because that'd seem a bug.

File: explorer/interpreter/resolve_names.cpp [hunk 3]
```diff
@@ -856,7 +856,13 @@ auto NameResolver::ResolveNames(Declaration& declaration,
       CARBON_ASSIGN_OR_RETURN(auto target,
                               ResolveNames(alias.target(), *scope));
       if (target && isa<Declaration>(target->base())) {
-        alias.set_resolved_declaration(&cast<Declaration>(target->base()));
+        if (alias.resolved_declaration()) {
+          // Skip if the declaration is already resolved in a previous name resolution
+          // phase.
+          CARBON_CHECK(*alias.resolved_declaration() == target->base());
```
Comment (jonmeow) [inline explorer/interpreter/resolve_names.cpp]:
```suggestion
          CARBON_CHECK(*alias.resolved_declaration() == &target->base());
```

I'm sure you'll figure this out on your own, but I think this fixes the build error. :)

(and maybe the suggestion will be easier to apply)

**Review by jonmeow — APPROVED** [review]
