### PR TITLE
[explorer] fix assert when aliasing interface as member

### LINKED ISSUE #2583: Carbon explorer crashes when aliasing an interface method as a class member
### Description of the bug:

See the code and crash on compiler explorer here:
https://carbon.compiler-explorer.com/z/e7xczWsT3

### What did you do, or what's a simple way to reproduce the bug?

See the link above.

### What did you expect to happen?

That the alias makes using the member name equivalent to using a *qualified* member name in a call. Basically, lines 30 and 31 should be equivalent:

```
  v.(Printable.PrintIt)();
  v.PrintIt();
```

### What actually happened?

It crashed.

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by lnihlen**
Note that this code still results in a compilation error pending the merge of #2628, this just prevents the assertion from happening.

Closes #2583.

### CODE REVIEW

**Review by jonmeow — COMMENTED** [review]
A test would be really helpful for me to understand the effect this change has, and to validate that it's working as intended. Can you please construct a test case, e.g. by using the example from the issue?

**Comment by lnihlen** [comment]
Sure thing. I wrote one, but didn't know if a test was wanted given compilation still fails.

File: explorer/interpreter/type_checker.cpp [hunk 1]
```diff
@@ -2843,6 +2843,11 @@ auto TypeChecker::TypeCheckExp(Nonnull<Expression*> e,
                 access.set_expression_category(ExpressionCategory::Value);
                 break;
               }
+              case DeclarationKind::AliasDeclaration: {
+                const auto* alias = cast<AliasDeclaration>(member);
+                access.set_expression_category(alias->expression_category());
+                break;
```
Comment (jonmeow) [inline explorer/interpreter/type_checker.cpp]:
```suggestion
                return ProgramError(member->source_loc()) << "Member access to aliases is not yet supported.";
```

**Review by jonmeow — COMMENTED** [review]
Working as intended doesn't necessarily mean working. 😉 

A compile error is better than a crash, and we can always adjust the test as support is added.  Glancing though, it seems like no other test is affected by this change. However, I'm still a little nervous about adding support that doesn't really work, because I'm unsure what other edge cases it might open up -- how about making this an error more directly? (suggestion attached)

File: explorer/interpreter/type_checker.cpp (hunk 1 above)
Comment (lnihlen) [reply explorer/interpreter/type_checker.cpp]: Good suggestion, thanks. I think `access.source_loc()` provides a clearer error message. Refactored to this.

**Review by jonmeow — APPROVED** [review]
Thanks, the changes look good!
